### ISSUE TITLE
Could not locate zlibwapi.dll. Please make sure it is in your library path!

### ISSUE THREAD

**Issue by gitihobo** [facefusion/facefusion#103]
where do I download that and where does it go?

**Comment by henryruhs** [comment]
> Be aware, the installation needs technical skills and is not for beginners. Please do not open platform and installation related issues on GitHub. We have a very helpful [Discord](https://join.facefusion.io) community that will guide you to install FaceFusion.

**Comment by gitihobo** [comment]
Understood, but I dont use discord, can you make an exception rn?

**Comment by firdauspidus** [comment]
just install discord.. all problem can ask inside that...

**Comment by henryruhs** [comment]
exactly... it would take forever to ping pong the troubleshooting here.
