### ISSUE TITLE
What to do after: To create a public link, set share=True in launch(). ?

### ISSUE THREAD

**Issue by heiheiheibj** [facefusion/facefusion#104]
i dont know how , where is this launch() and how can i change it

To create a public link, set share=True in launch()

thx..

**Comment by henryruhs** [comment]
If you like to customize that, create your own layout.

Create file `facefusion/uis/layouts/default-open.py` with content:

```
import gradio

from facefusion.uis.layouts import default


def pre_check() -> bool:
    return default.pre_check()


def pre_render() -> bool:
    return default.pre_render()


def render() -> gradio.Blocks:
    return default.render()


def listen() -> None:
    default.listen()


def run(ui : gradio.Blocks) -> None:
    ui.launch(show_api = False, share = True)
```

Run:

```
python run.py --ui-layouts default-open
```

**Comment by heiheiheibj** [comment]
> Create file `facefusion/uis/layouts/default-share.py` with content:
> 
> ```
> import gradio
> 
> from facefusion.uis.layouts import default
> 
> 
> def pre_check() -> bool:
>     return default.pre_check()
> 
> 
> def pre_render() -> bool:
>     return default.pre_render()
> 
> 
> def render() -> gradio.Blocks:
>     return default.render()
> 
> 
> def listen() -> None:
>     default.listen()
> 
> 
> def run(ui : gradio.Blocks) -> None:
>     ui.launch(show_api = False, share = True)
> ```
> 
> Run with shared link:
> 
> ```
> python run.py --ui-layouts default-share
> ```

thx !

**Comment by chuan19** [comment]
thank you！i know,they are gradio parameter
setting doc：https://www.gradio.app/docs/interface

**Comment by chuan19** [comment]
![image](https://github.com/facefusion/facefusion/assets/57824272/f043d768-f946-42e5-ab16-cddf77890c74)

Modify the default.py file is okk

def run(ui : gradio.Blocks) -> None:
	ui.launch(show_api = False,share = True,server_name="0.0.0.0", server_port=6006)

**Comment by henryruhs** [comment]
@chuan19 Don't post examples to modify the original files... there is a reason I don't
