### ISSUE TITLE
GPU is not used for the processor

### ISSUE THREAD

**Issue by Okkband** [facefusion/facefusion#105]
I run this command: python run.py --execution-providers cuda. but the processing speed is very slow. and the GPU is not used for the processor while CPU‘utilization rate is full.
Ubuntu22.0, NVIDIA-GeForce 4090. CUDA12.1, python3.10, torch-2.0.1+cu118. 
![image](https://github.com/facefusion/facefusion/assets/52487802/2ea3ed67-77eb-4302-b564-e4a35dcbcd31)

![image](https://github.com/facefusion/facefusion/assets/52487802/62a53caa-b51e-4d79-b931-6a9131e28c03)

![image](https://github.com/facefusion/facefusion/assets/52487802/902e3d4b-821a-4bea-bbfd-f78de95dc475)

**Comment by henryruhs** [comment]
You need CUDA 11.8

**Comment by Okkband** [comment]
> You need CUDA 11.8

11.8's torch can be run on the CUDA12.1。。So this is not the problem.

**Comment by henryruhs** [comment]
Join Discord and reach out to Ivan... he will help you 100%
