### ISSUE TITLE
Target mask control

### ISSUE THREAD

**Issue by Colliwomple** [facefusion/facefusion#106]
Sometimes the target mask is too big so that on the forehead or on the sides hair beiing cut off. An option to control the size/blending of the mask would be nice.

**Comment by henryruhs** [comment]
Sorry, there is no plan to implement such edge case features. You are free to send a pull request.

**Comment by henryruhs** [comment]
What you are asking for is not a trivial task. Every target frame needs a different alignment and blending. That means a potential solution needs to be based on face landmarks.

I found a project that could either help or inspire: https://github.com/tsen-dev/face-cropper

I don't plan to implement this but pull request are welcome.

**Comment by henryruhs** [comment]
> We are not currently planning to implement this ourselves, but we welcome pull requests from our community. Therefore, I am closing this issue to prevent the issue tracker from being cluttered with unresolved issues.
