### ISSUE TITLE
Use this technology for clothes swapping 

### ISSUE THREAD

**Issue by sudip550** [facefusion/facefusion#109]
Can we use this technology for clothes swapping ? And if yes then how?

**Comment by henryruhs** [comment]
You just create a new frame processor that implements one of the following: ClothingGAN, POLY-GAN or Fashion-Conditional-GAN
See the docs: https://docs.facefusion.io/workshop/frame-processor

**Comment by henryruhs** [comment]
We are not currently planning to implement this ourselves, but we welcome pull requests from our community. Therefore, I am closing this issue to prevent the issue tracker from being cluttered with unresolved issues.
