### ISSUE TITLE
GPU setting don't use or detect P40 Tesla

### ISSUE THREAD

**Issue by gandolfi974** [facefusion/facefusion#112]
hi,
i use face fusion with cuda and tensorrt.
I don't understand why my Tesla P40 is not used by the program during frame processing. all settings seems ok. no error when i launch the program

**Comment by henryruhs** [comment]
> Please do not open platform and installation related issues on GitHub. We have a very helpful [Discord](https://join.facefusion.io/) community that will guide you to install FaceFusion.
