### ISSUE TITLE
adding a public link argument 

### ISSUE THREAD

**Issue by Kaneki010** [facefusion/facefusion#12]
something like " --share " or " --listen " to generate a public gradio link beside the local one

**Comment by morisuba** [comment]
yes please

**Comment by henryruhs** [comment]
Just for the records, the environment variables `GRADIO_SERVER_NAME`, `GRADIO_SERVER_PORT` and `GRADIO_ROOT_PATH` are official documented on the Gradio website.

**Comment by henryruhs** [comment]
Who said to apply it globally? You set it before running the command.

**Comment by henryruhs** [comment]
I explained everything already and my opinion did not change: https://github.com/facefusion/facefusion/issues/12#issuecomment-1690160282
