### ISSUE TITLE
plz this issue

### ISSUE THREAD

**Issue by daarkwulf** [facefusion/facefusion#120]
/roop/facefusion/facefusion/run.py
Using TensorFlow backend
Traceback (most recent call last):
  File "f:\roop\facefusion\facefusion\run.py", line 6, in <module>
    core.run()
  File "f:\roop\facefusion\facefusion\facefusion\core.py", line 211, in run
    parse_args()
  File "f:\roop\facefusion\facefusion\facefusion\core.py", line 35, in parse_args
    program.add_argument('--frame-processors', help = wording.get('frame_processors_help').format(choices = ', '.join(list_module_names('facefusion/processors/frame/modules'))), dest = 'frame_processors', default = ['face_swapper'], nargs = '+')
                                                                                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: can only join an iterable

**Comment by henryruhs** [comment]
This looks either like a modified or false merge codebase. It works for everyone...

**Comment by daarkwulf** [comment]
just to confirm that last time i used it 2 weeks ago i was having python version 3.10.6 specifically as someone told me that roop was also able to work on that version only.. but  now i updated the python to 3.11 ..

is thats why error is coming ???
should i reinstall 3.10.6

**Comment by henryruhs** [comment]
Just use 3.10...

**Comment by daarkwulf** [comment]
sir plzz help
i used the same version u told.. still giving same eroor

**Comment by daarkwulf** [comment]
and then after again running the run.py it came

Using TensorFlow backend
Traceback (most recent call last):
  File "f:\roop\facefusion\facefusion\run.py", line 6, in <module>
    core.run()
  File "f:\roop\facefusion\facefusion\facefusion\core.py", line 211, in run
    parse_args()
  File "f:\roop\facefusion\facefusion\facefusion\core.py", line 35, in parse_args
    program.add_argument('--frame-processors', help = wording.get('frame_processors_help').format(choices = ', '.join(list_module_names('facefusion/processors/frame/modules'))), dest = 'frame_processors', default = ['face_swapper'], nargs = '+')
TypeError: can only join an iterable

**Comment by daarkwulf** [comment]
also brother u changes the code yesterday only thast why new one are not getting this error soon..
old giys are still using the old ways code..

**Comment by daarkwulf** [comment]
and also after ur changing code many files like
jax 
jaxlib
psutil
tensorflow
insightface

so much files we have to install one by one cause of error coming

**Comment by daarkwulf** [comment]
this error also comes 

[?] select the onnxruntime to be installed: cpu
 > cpu
   cuda
   coreml-legacy
   coreml-silicon
   directml
   openvino

WARNING: Skipping torch as it is not installed.
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'

**Comment by daarkwulf** [comment]
bro better u yourself see the code u changes or updates yesterday

**Comment by daarkwulf** [comment]
despitte running and install tensorflow files from requirements txt and still when running the installer it saying to install tensorflow..

**Comment by daarkwulf** [comment]
yes its working.. i find the way myself somehow.. plz close this ticket
