### ISSUE TITLE
No source face detected 

### ISSUE THREAD

**Issue by venshine** [facefusion/facefusion#124]
![image](https://github.com/facefusion/facefusion/assets/1456580/08d8fa93-d66d-4926-b63e-0c6f89aa8bff)
I used the image above as the original image to change faces, but prompted me “No source face detected”, What should I do?

**Comment by henryruhs** [comment]
Face is too cropped in and cannot be detected.

**Comment by venshine** [comment]
> Face is too cropped in and cannot be detected.

Can you provide a parameter about the boundary of face detection, this image can be successfully changed with roop.

**Comment by henryruhs** [comment]
I doubt this... nothing changed in terms of face detection.
