### ISSUE TITLE
No Button or Icon to download

### ISSUE THREAD

**Issue by ThisisDennis** [facefusion/facefusion#131]
The result seems to be done, but there is nothing in the target folder, as well there is no download button or icon.
I have no clue how to get the result or at least the result-images.

Does anyone has an idea, what might be the problem?

**Comment by henryruhs** [comment]
The download icon is in the upper right corner..

**Comment by ThisisDennis** [comment]
It doesnt appear there. I know where it should be.

**Comment by henryruhs** [comment]
What do you expect me todo about that?

**Comment by henryruhs** [comment]
Please join Discord for help...
