### ISSUE TITLE
Batch File Processing

### ISSUE THREAD

**Issue by Atopona** [facefusion/facefusion#132]
Would be great if you could develop the feature to batch process files (targets mainly). User would select source image and multiple target files. The user should be able to select specific face from the multiple target files. Great work so far!

**Comment by henryruhs** [comment]
Many people asked for this the past months.

I made up a plan already on how to implement this feature in the most clean and extendable way.

1. Introduce a ARGS <> JSON parser
1. Save each job in a .jobs/{hash}.json
1. Hash is generated from the ARGS object
1. CLI argument `--run-jobs`
1. CLI argument `--run-job {hash}`
1. Job file contains metadata
    - version
    - label
    - status
    - args
1. Deleted job files after a successful run?
1. Add, edit and delete jobs from the UI

**Comment by Atopona** [comment]
Excuse me, is there any sample code?

**Comment by henryruhs** [comment]
I did not work on that, just defined the requirements.

**Comment by ocpinfo** [comment]
This feature is very necessary, Hope to be developed ASAP!!!

**Comment by henryruhs** [comment]
Either hire a developer or become a sponsor... otherwise there is no ASAP!!! ... This kind of requests on a open source project are kind of rude. Your comment will be deleted.

**Comment by henryruhs** [comment]
@Atopona I have different plans with FaceFusion, this is not a priority for me.

**Comment by henryruhs** [comment]
Planned for the next release.
