### ISSUE TITLE
Where is the location of the temp folder?

### ISSUE THREAD

**Issue by TanvirHafiz** [facefusion/facefusion#135]
For enhancement purpose, I need to use the raw images in the temp file. May I know where is the temp folder? I have checked "keep temp" button.

**Comment by henryruhs** [comment]
It's located in `.facefusion` of the temp directory of the operating system.

**Comment by ZedeX** [comment]
> It's located in `.facefusion` inside the temp directory of your operating system.

How could I change the setting of temp folder? I didn't find settings in facefusion.ini. It takes too much of my C:\

Thank you!

**Comment by gzw13999** [comment]
> > 它位于操作系统的临时目录中。`.facefusion`
> 
> 如何更改临时文件夹的设置？我在facefusion.ini中没有找到设置。它占用了我的 C：\
> 
> 谢谢！

Have you found a solution? My current problem is not that the C drive is occupied, but that the C drive is not big enough and processing video files takes up a lot of space

**Comment by ZedeX** [comment]
> > > 它位于操作系统的临时目录中。`.facefusion`
> > 
> > 
> > 如何更改临时文件夹的设置？我在facefusion.ini中没有找到设置。它占用了我的 C：\
> > 谢谢！
> 
> Have you found a solution? My current problem is not that the C drive is occupied, but that the C drive is not big enough and processing video files takes up a lot of space

nope
