### ISSUE TITLE
Face enhancer model is not downloaded

### ISSUE THREAD

**Issue by TanvirHafiz** [facefusion/facefusion#136]
The face enhancer model or checkpoint is not downloaded. I tried manually putting the gfpgan weights in the folder and still the issue exists. How to fix? thanks.

**Comment by henryruhs** [comment]
I assume you are under Windows and have a firewall or virus scanner enabled. This has been "fixed" in the next branch via https://github.com/facefusion/facefusion/blob/next/facefusion/utilities.py#L190
