### ISSUE TITLE
cublas and cudnn could be installed with pip

### ISSUE THREAD

**Issue by metal3d** [facefusion/facefusion#137]
Hi,

First, thanks for the done work.

I had many warnings, and even errors when I installed myself CuDNN on my Linux Fedora. And I finally found a "better solution" that makes everything OK.

CuDNN installed, the problem is that `libcublasLt.so.12` was not found. And on Fedora, there is no package to install this (because we're using the latest 11). I don't know why onnx wants the v12 version, but, anyway, there is a solution 😄 

Using a virtualenv (but it is OK with pipenv of course), we can do:

```
# as usual
python install.py

# and then
pip install nvidia-cublas-cu12 nvidia-cudnn-cu12
```

Afterward, I could launch the interface with:

```
LD_LIBRARY_PATH=./.venv/lib/python3.11/site-packages/nvidia/cublas/lib:./.venv/lib/python3.11/site-packages/nvidia/cudnn/lib:$LD_LIBRARY_PATH python run.py
```

Of course, that's a workaround, and I'm pretty sure that the path could be automatically set.

I don't know if it affects the performance, but there is no error, and it seems that my tests are now a bit faster. Maybe you can adapt the installer / runner (or maybe I can take some time to propose something)

**Comment by henryruhs** [comment]
> Please do not open platform and installation related issues on GitHub. We have a very helpful [Discord](https://join.facefusion.io) community that will guide you to install FaceFusion.
