### ISSUE TITLE
cannot load the GPU option, but Torch detects that CUDA is installed successfully.无法使用GPU,但是PyTorch已经检测到CUDA,并且可以调用GPG

### ISSUE THREAD

**Issue by HiColinn** [facefusion/facefusion#138]
My graphics card model is NVIDIA 3070 Laptop. I've written a Python script to check the Torch environment. Within the FaceFusion virtual environment, the script has detected CUDA and can successfully utilize GPU resources internally. However, after starting FaceFusion, it still cannot load the GPU option.
(我的显卡型号是 英伟达3070 移动版,我编写了一个python文件去检测torch环境,在facefusion的虚拟环境中,脚本已经发现了CUDA,并且在脚本内部可以成功调用GPU资源,但是facefusion启动以后仍然无法加载GPU选项)
The results of my script's execution are as shown in the following image:
(我的脚本运行结果如下图):
![10月04日002](https://github.com/facefusion/facefusion/assets/65964332/2aa0dbfe-f046-466c-824b-62ff065e7f77)
However, when I start FaceFusion, it still cannot detect the GPU. The screenshot of the execution is as follows:
(但是当我启动facefusion的时候,亦然无法发现GPU,运行截图如下):
![10月04日003](https://github.com/facefusion/facefusion/assets/65964332/e39332eb-180b-4c9c-8be3-8cfa3350fb49)
![10月04日004](https://github.com/facefusion/facefusion/assets/65964332/eca73849-0923-44c1-86f1-c47f354cc6bb)

**Comment by henryruhs** [comment]
> Please do not open platform and installation related issues on GitHub. We have a very helpful [Discord](https://join.facefusion.io) community that will guide you to install FaceFusion.
