### ISSUE TITLE
[FACEFUSION.CORE] Temporary frames not found

### ISSUE THREAD

**Issue by achiever1984** [facefusion/facefusion#147]
Hello.

When I click on the "Start" button, the program analyzes all the frames and afterwards it gives the following:
100%|████████████████████████████████████████|| 910/910 [00:05<00:00, 174.53it/s]
[FACEFUSION.CORE] Creating temporary resources
[FACEFUSION.CORE] Extracting frames with 25.0 FPS
[FACEFUSION.CORE] Temporary frames not found

That's the end of it. But in the preview everything is displayed as it should be.

What am I doing wrong that I can't start the video creation process?

**Comment by henryruhs** [comment]
Path of ffmpeg might is usually not correct on that error. Join our Discord for help.
