### ISSUE TITLE
Some videos will report this error when switching to the end.

### ISSUE THREAD

**Issue by guahunyo** [facefusion/facefusion#148]
Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\ProgramData\anaconda3\lib\asyncio\proactor_events.py", line 165, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。

**Comment by henryruhs** [comment]
ReadError: [WinError 10054] An existing connection was forcibly closed by the remote host.

**Comment by guahunyo** [comment]
> 不是 FaceFusion 问题。
> 
> ReadError: [WinError 10054] 现有连接被远程主机强制关闭。

I'm sorry, can I get your help, how can I solve this problem, I have succeeded before, but now towards the end it happens like this and I can't get the result.

**Comment by guahunyo** [comment]
> > 不是 FaceFusion 问题。
> > ReadError: [WinError 10054] 现有连接被远程主机强制关闭。
> 
> I'm sorry, can I get your help, how can I solve this problem, I have succeeded before, but now towards the end it happens like this and I can't get the result.
![ZBZB Y3KQ~ X5@Y1D }$B$N](https://github.com/facefusion/facefusion/assets/18573180/0b50a891-b4dd-41d6-960c-8b123a062bf5)

**Comment by guahunyo** [comment]
> Not a FaceFusion issue.
> 
> ReadError: [WinError 10054] An existing connection was forcibly closed by the remote host.

It may be an audio problem. I tried skip audio and it was successful.

**Comment by henryruhs** [comment]
Use Discord for help, this is a issue tracker for software and not a forum.
