### ISSUE TITLE
Frame processor frame_enhancer could not be loaded???

### ISSUE THREAD

**Issue by lanhebe** [facefusion/facefusion#153]
I followed the installation tutorial step by step on my Mac until the installation was successful. However, when I ran python run.py, an error message appeared: Frame processor frame_enhancer could not be loaded. How can I solve this problem?thank you!

**Comment by henryruhs** [comment]
Did you use the `install.py` and default for torch? Please join Discord as troubleshooting via a GitHub issue is painfully slow.
