### ISSUE TITLE
not have cuda and tensorrt

### ISSUE THREAD

**Issue by gameandwhk111111111111111111** [facefusion/facefusion#156]
1.3.1   EXECUTION PROVIDERS only azure  and cpu,not have cuda and tensorrt

**Comment by ghostjk123** [comment]
Execute the following two commands
pip uninstall onnxruntime onnxruntime-gpu
pip install onnxruntime-gpu==1.15.1

**Comment by henryruhs** [comment]
Follow our guide https://docs.facefusion.io/installation

It's indeed
```
pyhton install.py --torch cuda --onnxruntime cuda
```

**Comment by SantiiRepair** [comment]
> Follow our guide https://docs.facefusion.io/installation
> 
> It's indeed
> 
> ```
> pyhton install.py --torch cuda --onnxruntime cuda
> ```
> 
> Follow the guide on Nvidia's document about installing CUDA afterwards. Get further help at our Discord as this can be a tough one.
```sh
usage: install.py [-h] [--onnxruntime {default,cuda-12.2,cuda-11.8,openvino,directml}] [--skip-conda] [-v]                                                                               
install.py: error: argument --onnxruntime: invalid choice: 'cuda' (choose from 'default', 'cuda-12.2', 'cuda-11.8', 'openvino', 'directml')
```

**Comment by henryruhs** [comment]
Well, arguments change over a period of 8 months.
