### ISSUE TITLE
--listen  instruction

### ISSUE THREAD

**Issue by king820616** [facefusion/facefusion#164]
Is it possible to add a --listen command like stable diffusion so that webui can be used on devices within the local network?

**Comment by henryruhs** [comment]
I don't plan to add this.

See https://github.com/facefusion/facefusion/issues/12#issuecomment-1690167541
See https://github.com/facefusion/facefusion/issues/104#issuecomment-1720089698

**Comment by d8ahazard** [comment]
> I don't plan to add this.
> 
> See [#12 (comment)](https://github.com/facefusion/facefusion/issues/12#issuecomment-1690167541) See [#104 (comment)](https://github.com/facefusion/facefusion/issues/104#issuecomment-1720089698)

Even if it can be set via exports...what is the actual harm in adding flags to accompany all of the other startup parameters?

It a trivial change that I've wrapped up with a big bow for you that will make things easier and less confusing for users. Just curious why not?

**Comment by henryruhs** [comment]
It has already been explained: https://github.com/facefusion/facefusion/issues/12#issuecomment-1690160282
