### ISSUE TITLE
Error on video conversion

### ISSUE THREAD

**Issue by crmdany** [facefusion/facefusion#167]
Hello, I am facing an issue on converting videos. Getting an error on the output box. I am using mac m1. Could you please help me with the issue. 

<img width="1728" alt="Screenshot 2023-10-22 at 2 34 16 PM" src="https://github.com/facefusion/facefusion/assets/136147716/038a8d70-4179-4cd3-aaa1-88451f54020a">
<img width="1728" alt="Screenshot 2023-10-22 at 2 31 26 PM" src="https://github.com/facefusion/facefusion/assets/136147716/5c60a5bd-7e71-4adc-a342-7ffbfffb7334">

**Comment by henryruhs** [comment]
The max memory you set are larger than the free memory... that is causing the issue.

**Comment by crmdany** [comment]
Alright. I set the optimum memory. Yet I am facing the same error stating that " Temporary frames not found ". Please help me
<img width="1728" alt="Screenshot 2023-10-22 at 3 51 50 PM" src="https://github.com/facefusion/facefusion/assets/136147716/afa90999-9dd5-48d4-b00d-0c618e51a435">

**Comment by henryruhs** [comment]
That's why I don't give support in GitHub issues... join us on Discord.
