### ISSUE TITLE
The output file size of FF Version 1.3.1 is too big!!!

### ISSUE THREAD

**Issue by ocpinfo** [facefusion/facefusion#170]
For example, My source file is only 70MB, But the output file became 2GB in version 1.3.1, But 1.1.0 is good, The output file size is same as the source file. I only chose face swapper

**Comment by henryruhs** [comment]
I checked it... that is a false statement. It's actual smaller.

![grafik](https://github.com/facefusion/facefusion/assets/1835397/cbf14e73-e8ac-4f1b-9b84-23a0c04f8939)

**Comment by ocpinfo** [comment]
I don't know why, I used same options,But the output file size is too big
[Uploading Screenshot 2023-10-24 at 22.56.49.png…]()

**Comment by henryruhs** [comment]
switch between the FaceFusion versions using `git checkout 1.1.0` and `git checkout 1.3.1` ... use the same CLI command for both and compare it.

**Comment by ocpinfo** [comment]
OK, I will try. Thanks
