### ISSUE TITLE
Why does run.py report an error orjson when running normally?

### ISSUE THREAD

**Issue by Titttzi** [facefusion/facefusion#173]
File "E:\MIXXXXXX\facefusion-master\venv\lib\site-packages\orjson\__init__.py", line 3, in <module>
    from .orjson import *
ModuleNotFoundError: No module named 'orjson.orjson'

**Comment by henryruhs** [comment]
> Please do not open platform and installation related issues on GitHub. We have a very helpful [Discord](https://join.facefusion.io/) community that will guide you to install FaceFusion.
