### ISSUE TITLE
GPU not showing after update from 1.0.0 to 1.3.1

### ISSUE THREAD

**Issue by lombarthus** [facefusion/facefusion#176]
Hi!
I just updated by extracting the latest files into my former folders and running the requirements.txt once more (on Windows 10). When starting FF I can only see "Azure" and "CPU" as Execution Providers. How can I include my NVIDIA graphics card under "Execution Providers" and use it accordingly? Any help is highly appreciated.

Lomb

![2023-11-01 15_18_21-Window](https://github.com/facefusion/facefusion/assets/80924095/d709625b-6ff2-4acd-8af1-03c47e3911b7)

**Comment by henryruhs** [comment]
Well, reading the docs might help...
