### ISSUE TITLE
How to change the .insightface folder's path

### ISSUE THREAD

**Issue by Spr-Peach** [facefusion/facefusion#180]
I put facefusion folder under C:\Users\username\, and when running python run.py it will check or download the .insightface folder with model under C:\Users\username path. If I cut it to facefusion\  it will re-download a new .insightface folder. could you please tell me how can I change the .insightface folder's path. I read those .py files and have not find where to change the path yet...thanks alot

**Comment by henryruhs** [comment]
Well, don't change it... I not gonna support this. Problem should be solved in "next" branch anyway.
