### ISSUE TITLE
Request for improvements

### ISSUE THREAD

**Issue by Mr-Nobody-dey** [facefusion/facefusion#183]
First of all, it is a great peace of code you guys have written and thank you for that. supper fast

I have found few limitations, improving those might improve the output:

Current problems:
1. The output is not good when the face is inverted (i.e., face orientation is upside down)

![Hollywood-actress-Anne-Hathaway-_185dec31e52_large](https://github.com/facefusion/facefusion/assets/71100716/c1bfcf7f-5019-4a5a-ba8e-14d12f1afcfb)
![Angelina_Jolie_by_Gage_Skidmore_3-e1691753600605i](https://github.com/facefusion/facefusion/assets/71100716/9d762c0a-6fe2-4b44-80df-4566e974cc50)
![image](https://github.com/facefusion/facefusion/assets/71100716/3049b3d0-9bc2-4508-961a-2d1ffe21f8ec)

2.  If their is some obstacle in front of the face then the obstacle do not come clearly in the output.

![Angelina_Jolie_by_Gage_Skidmore_3-e1691753600605](https://github.com/facefusion/facefusion/assets/71100716/7c1a8aa1-e8d5-49bc-a746-7960be02364a)
![istockphoto-1357936782-1024x1024jhg](https://github.com/facefusion/facefusion/assets/71100716/0871a6c5-bbb5-4c58-a251-4d45a7a8d683)
![image (1)](https://github.com/facefusion/facefusion/assets/71100716/31f2b732-6173-4211-ab3d-f1052c6580af)

**Comment by Mr-Nobody-dey** [comment]
If you look closely, the nose is visible above the mask.

**Comment by henryruhs** [comment]
Thanks for point out this issues.

1. I don't plan to implement false usage prevention for upside-down images
2. we recently start working on occlusion handling

If you have more suggestions, we have a channel for that on our Discord.
