### ISSUE TITLE
It errors if it can't find a face on the target image

### ISSUE THREAD

**Issue by luisiacc** [facefusion/facefusion#188]
I was using it thru replicate.com on https://replicate.com/okaris/facefusion?prediction=xlhybktbqydw5hj4cb6inmp6ha

The target image I uploaded was a picture of a dog, attaching it here so you can reproduce it. I'm not saying you should handle the dog faces as it's probably not possible, but to handle the error instead.
![b41c279d7c06b82cfb4253dc6d9327f1](https://github.com/facefusion/facefusion/assets/31720261/c2b79579-d705-4b64-a832-11f645f220bf)

This are the logs:

```
source:  /tmp/tmpcfc0mxnw3095452b137bca7c24e4c743b859608e.jpg
target:  /tmp/tmpzui8c4dcb41c279d7c06b82cfb4253dc6d9327f1.jpg
keep_fps:  True
No face found
printing shapes failed.
Traceback (most recent call last):
File "/root/.pyenv/versions/3.8.17/lib/python3.8/site-packages/cog/server/worker.py", line 222, in _predict
for r in result:
File "predict.py", line 82, in predict
output = process_img(source, target, enhance_face, paste_back=paste_back)
File "/src/core/processor.py", line 45, in process_img
result = face_swapper.get(frame, face, source_face, paste_back=paste_back)
File "/root/.pyenv/versions/3.8.17/lib/python3.8/site-packages/insightface/model_zoo/inswapper.py", line 47, in get
aimg, M = face_align.norm_crop2(img, target_face.kps, self.input_size[0])
AttributeError: 'NoneType' object has no attribute 'kps'
```

**Comment by henryruhs** [comment]
That replica is 1. not done by us and 2. will be down soon as InsightFace is chasing every commercial instance of their swapper model.
