### ISSUE TITLE
canr run with directml

### ISSUE THREAD

**Issue by Burane** [facefusion/facefusion#19]
When running whit directml i go this error 

`python run.py --execution-providers dml`

`run.py: error: argument --execution-providers: invalid choice: 'dml' (choose from 'tensorrt', 'cuda', 'cpu')`

**Comment by henryruhs** [comment]
> Please do not open platform and installation related issues on GitHub. We have a very helpful [Discord](https://join.facefusion.io/) community that will guide you to install FaceFusion.
