### ISSUE TITLE
[Feature request] Add upload progress bar

### ISSUE THREAD

**Issue by kamack38** [facefusion/facefusion#20]
Add a progress bar that shows file upload progress

**Comment by henryruhs** [comment]
What upload are you talking about?

**Comment by shobhit9957** [comment]
/attempt #20

I would like to contribute to it. Can you please help me.

**Comment by henryruhs** [comment]
I close the issue, add proper description next time.

**Comment by kamack38** [comment]
Looks like uploading to me
![Screenshot_2023-08-24-20-59-57-27_984e1414ae90666a90f12ff17ec14a7f.jpg](https://github.com/facefusion/facefusion/assets/64226248/88e32375-2f8e-4c6d-97e6-743e75ba596b)

**Comment by henryruhs** [comment]
There is nothing like that: https://www.gradio.app/docs/file
