### ISSUE TITLE
Is it possible to add a parameter setting function for the intensity of the face swap？

### ISSUE THREAD

**Issue by petercham** [facefusion/facefusion#200]
Is it possible to add a parameter setting function for the intensity of the face swap？
sometimes we don't necessarily want the face to look exactly like someone, but rather we want to create a new character with certain characteristics of the original character.
Especially in animation or some art styles, The current version of the face swap design reduces the original art style of the face.

**Comment by henryruhs** [comment]
The model has to provide that option but they don't. Sorry
