### ISSUE TITLE
conversion gets stuck

### ISSUE THREAD

**Issue by taleksan** [facefusion/facefusion#203]
Both on latest and 1.2.1

Tried changing different settings... preview frames work great. When I click start, the initial quick progress bar gets to 100% - and... nothing. Just hung forever, Start and Clear button in UX don't press anymore. Tried with different images, videos, various UI settings - like codec - nothing seems to help.

How do I even debug this?

Applied providers: ['CUDAExecutionProvider', 'CPUExecutionProvider'], with options: {'CUDAExecutionProvider': {'cudnn_conv_algo_search': 'EXHAUSTIVE', 'device_id': '0', 'cudnn_conv1d_pad_to_nc1d': '0', 'has_user_compute_stream': '0', 'gpu_external_alloc': '0', 'enable_cuda_graph': '0', 'gpu_mem_limit': '18446744073709551615', 'gpu_external_free': '0', 'gpu_external_empty_cache': '0', 'arena_extend_strategy': 'kNextPowerOfTwo', 'do_copy_in_default_stream': '1', 'cudnn_conv_use_max_workspace': '1', 'tunable_op_enable': '0', 'tunable_op_tuning_enable': '0', 'tunable_op_max_tuning_duration_ms': '0', 'enable_skip_layer_norm_strict_mode': '0'}, 'CPUExecutionProvider': {}}
inswapper-shape: [1, 3, 128, 128]
100%|████████████████████████████████████████████████████████████████████████████████| 871/871 [00:10<00:00, 83.50it/s]

Thanks!
Al

**Comment by henryruhs** [comment]
It is intentional that you cannot debug this, as this is the NSFW filter that kicked it...
