### ISSUE TITLE
Can't install on M1. Skipping onnxruntime-silicon as it is not installed.

### ISSUE THREAD

**Issue by mikheys** [facefusion/facefusion#210]
Good evening. Can't install on M1, 2021, memory 16GB
I do everything according to the instructions, when installing I select:
   default
- cpu
    cuda
    rocm

   default
   cuda
   coreml-legacy
 - coreml-silicon
   directml
   openvino

An error appears at the end:

Successfully uninstalled onnxruntime-1.16.0
WARNING: Skipping onnxruntime-silicon as it is not installed.
ERROR: Could not find a version that satisfies the requirement onnxruntime-silicon==1.16.0 (from versions: 1.11.1, 1.13.1, 1.14.1, 1.15.0)
ERROR: No matching distribution found for onnxruntime-silicon==1.16.0

**Comment by henryruhs** [comment]
We close installation requests instantly.
