### ISSUE TITLE
Frame processor frame_enhancer could not be loaded

### ISSUE THREAD

**Issue by vien-meng** [facefusion/facefusion#213]
PS D:\working\facefusion> .\venv\Scripts\python.exe .\run.py
WARNING:tensorflow:From D:\working\facefusion\venv\lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

Using TensorFlow backend
Frame processor frame_enhancer could not be loaded

**Comment by henryruhs** [comment]
Please do not open platform and installation related issues on GitHub. We have a very helpful [Discord](https://join.facefusion.io) community that will guide you to install FaceFusion.
