### ISSUE TITLE
 Implement Sorting of Detected Faces by Confidence Scores in detect_with_retinaface

### ISSUE THREAD

**Issue by JuniverseCoder** [facefusion/facefusion#217]
The current implementation of the `detect_with_retinaface` function in our face detection module processes and returns lists of bounding boxes, keypoints, and confidence scores (`bbox_list`, `kps_list`, `score_list`). However, it lacks a crucial step of sorting these detections based on the confidence scores. This sorting step is essential for subsequent processes like Non-Maximum Suppression (NMS), which assume that detections are sorted by their confidence levels.

Sorting detections by their confidence scores ensures that the most confident detections are processed first, which is a standard practice in object detection workflows. This approach improves the efficiency and accuracy of subsequent filtering steps, like NMS, where the order of processing can significantly impact the final results.

**Proposed Solution**:

I propose to add a sorting mechanism right before the return statement of the `detect_with_retinaface` function. This will rearrange `bbox_list`, `kps_list`, and `score_list` in descending order of confidence scores.

**Sample Code for Proposed Solution**:

```python
def detect_with_retinaface(...):  # existing parameters
    # existing code ...

    # sort detections by descending order of confidence scores
    sorted_indices = numpy.argsort(-numpy.array(score_list))
    bbox_list = [bbox_list[i] for i in sorted_indices]
    kps_list = [kps_list[i] for i in sorted_indices]
    score_list = [score_list[i] for i in sorted_indices]

    return bbox_list, kps_list, score_list
```

**Impact**:

Implementing this change will align our face detection process with standard practices, potentially improving the performance of subsequent steps like NMS and enhancing the overall accuracy of face detection.

**Comment by Chrisgghhjjjjjjjjjjhvff** [comment]
C’est nul

**Comment by henryruhs** [comment]
Thanks for analysing the code, I appreciate that.

> Sorting detections by their confidence scores ensures that the most confident detections are processed first, which is a standard practice in object detection workflows.

It seems to be a standard, correct. Still no benefit doing this as there is no logic to premature abort the NMS processing!?

Please correct me if I'm wrong but performance-wise it should be the same.

**Comment by henryruhs** [comment]
@JuniverseCoder Thanks, let me know if you find more room for improvements.
