### ISSUE TITLE
Issue with Code Execution on Colab's Free Tier

### ISSUE THREAD

**Issue by fuyang0811** [facefusion/facefusion#219]
Issue with Code Execution on Colab's Free Tier

Hello,

I've been encountering an issue on Colab over the past few days. The platform shows a message stating, 

"The code execution has been interrupted because it contains code that is not permitted on the free tier, and hence your runtime has been disconnected." 

Does this imply that I will no longer be able to use facefusion on Colab in the future?

Thank you.

**Comment by henryruhs** [comment]
Please don't open issues like that... what should I do about Colab blocking us?
