### ISSUE TITLE
Wrong preview frame when using the preview frame slider 

### ISSUE THREAD

**Issue by Ferocit** [facefusion/facefusion#221]
**Steps to reproduce:**
* Load a video file
* Use the preview frame slider to select a frame

**Expected behavior:**
* The preview frame is the frame number that was selected with the slider

**Actual behavior:**
* The preview frame (often) is a different frame

**Note:**
* The reference faces are taken from the correct frame
* Changing an option, like reference face distance, will reload the preview frame with the correct one

**Comment by henryruhs** [comment]
That's a known issue. Unfortunately I don't have a solution for that as this seems to be a timing issue within our components.

**Comment by Ferocit** [comment]
Okay. Thanks for the answer.

Sorry for the duplicate in this case, couldn't find it in the closed issues.

**Comment by Ferocit** [comment]
I did a small change locally that I think would work:

`PREVIEW_FRAME_SLIDER.change` to `PREVIEW_FRAME_SLIDER.release` in the preview.py. 

The preview frame will be the correct one, but of course you would lose the instant preview generation while using the slider.

**Comment by henryruhs** [comment]
yeah it's some event timing like that. send a PR once you solved it. 😁

**Comment by henryruhs** [comment]
Merged to next, please confirm it is working
