### ISSUE TITLE
compress_image,Is there a problem with this compression?

### ISSUE THREAD

**Issue by mfh19891114** [facefusion/facefusion#227]
The source code is as follows:

def compress_image(output_path : str) -> bool:
	output_image_compression = round(31 - (facefusion.globals.output_image_quality * 0.31))
	commands = [ '-hwaccel', 'auto', '-i', output_path, '-q:v', str(output_image_compression), '-y', output_path ]
	return run_ffmpeg(commands)

issue：
Why would the input and output paths be the same path, giving an error.

The error is as follows:

['ffmpeg', '-hide_banner', '-loglevel', 'error', '-hwaccel', 'auto', '-i', '/tmp/test.png', '-q:v', '6', '-y', '/tmp/test.png']  **debug info**
[FACEFUSION.CORE] Compressing image failed    **There's an error**
[FACEFUSION.CORE] Processing to image succeed

**Comment by henryruhs** [comment]
Sorry, but I cannot debug your platform via a GitHub issue. Therefore we ask people to join a troubleshooting channel on our Discord. Thanks

**Comment by mfh19891114** [comment]
> Sorry, but I cannot debug your platform via a GitHub issue. Therefore we ask people to join a troubleshooting channel on our Discord. Thanks

Now there is a problem here, ffmpeg will give an error if the input and output are the same path, is this not a problem?

for example:
ffmpeg -hide_banner -loglevel error -hwaccel auto -i /tmp/test.png -q:v 6 -y /tmp/test.png

ffmpeg return ERROR：
Output /tmp/test.png same as Input #0 - exiting

**Comment by henryruhs** [comment]
exactly it is your ffmpeg...
