### ISSUE TITLE
compress_image, There's something wrong with this approach

### ISSUE THREAD

**Issue by mfh19891114** [facefusion/facefusion#228]
The source code is as follows:

def compress_image(output_path : str) -> bool:
output_image_compression = round(31 - (facefusion.globals.output_image_quality * 0.31))
commands = [ '-hwaccel', 'auto', '-i', output_path, '-q:v', str(output_image_compression), '-y', output_path ]
return run_ffmpeg(commands)

The final command executed by the preceding code is as follows:

['ffmpeg', '-hide_banner', '-loglevel', 'error', '-hwaccel', 'auto', '-i', '/tmp/test.png', '-q:v', '6', '-y', '/tmp/test.png']

issue：
Why would the input and output paths be the same path, giving an error.

The error is as follows:

['ffmpeg', '-hide_banner', '-loglevel', 'error', '-hwaccel', 'auto', '-i', '/tmp/test.png', '-q:v', '6', '-y', '/tmp/test.png'] debug info
[FACEFUSION.CORE] Compressing image failed There's an error
[FACEFUSION.CORE] Processing to image succeed

**Comment by mfh19891114** [comment]
You want to help users solve problems, not just shut them down

**Comment by henryruhs** [comment]
See our README

> Be aware, the installation needs technical skills and is not for beginners. Please do not open platform and installation related issues on GitHub
