### ISSUE TITLE
which variant of Torch and onnxruntime to choose (on Apple Silicon) when running install.py ?

### ISSUE THREAD

**Issue by vesper8** [facefusion/facefusion#231]
I feel like this should be mentioned in the docs. In other apps I have to install the torch nightly.. here there's no such option.. tempted to pick default.. would like to avoid picking CPU as that's very slow.. which one is best for Mac right now? 

Same question for onnxruntime.. which variant to choose please? Please add this to the docs under the Mac section.

Thanks!

**Comment by henryruhs** [comment]
Already covered by "Operating system specific installer options" in next branch.
