### ISSUE TITLE
How to make sure CUDA is used?

### ISSUE THREAD

**Issue by SuperMaximus1984** [facefusion/facefusion#234]
I'm using CUDA 12.3 with Pytorch 2.0.1+cu117
`is_cuda_available` returns = `True`, 
But during video processing, my RTX4090 has no load (in Windows Task Manager).

Should this code be run with CUDA 11.8 in order to utilize the Nvidia GPU?
Thanks!

**Comment by SuperMaximus1984** [comment]
@henryruhs That's the question - how to run CUDA? 
Is there any special parameter for Gradio to run CUDA?
Thanks!

**Comment by cserpellZF** [comment]
You can try using the program arguments `--execution-providers cuda`.
