### ISSUE TITLE
How to Disable Preview on Images? Image Preview is Unnecessary and Consumes Double Time! 

### ISSUE THREAD

**Issue by TechVillain** [facefusion/facefusion#236]
FaceFusion is a one-stop-shop for face swapping, face-debugging, face-restoring, and frame-enhancement. Often, I use FaceFusion to enhance low resolution images with the built-in RealESRGAN and RealESRNET models.

The problem is, the preview takes too much time, and it's useless. I don't need to preview on a still image, it's unnecessary.

I would rather to disable the preview, so that I can start the image processing right away without waiting for the preview to generate.

How do I do this?

**Comment by henryruhs** [comment]
Write your own UI layout by removing the preview component.

https://docs.facefusion.io/workshop/ui-layout
