### ISSUE TITLE
How Do I Permanently Disable the NSFW Filters?

### ISSUE THREAD

**Issue by TechVillain** [facefusion/facefusion#237]
I am a body artist and I often study on many images of naked people presenting their bodies to the public for artistic purposes.

How do I permanently turn off the NSFW filters, so that the software doesn't interfere with my research and study?

**Comment by henryruhs** [comment]
> Users who seek to engage in such activities will face consequences, including being banned from our community. We reserve the right to report developers on GitHub who distribute unlocked forks of our software at any time.

https://docs.facefusion.io/introduction/disclaimer
