### ISSUE TITLE
Select multiple reference faces

### ISSUE THREAD

**Issue by vehanlankaja** [facefusion/facefusion#238]
How do you select multiple reference face, it isn't an issue, but that feature would be awesome. the issue is after selecting a face it doesn't detect in some locations due to it being deformed, selecting the new one make the rest of them unselected.

**Comment by henryruhs** [comment]
Thanks for the suggestion. I added it to the [roadmap](https://docs.facefusion.io/introduction/roadmap#3.0.0) for version 3.0.0.
