### ISSUE TITLE
Config File

### ISSUE THREAD

**Issue by gisu** [facefusion/facefusion#240]
Hi, maybe a feature request.

It would be quite nice if you could create a basic configuration in which you can store your own default settings, just like the output folder.

**Comment by Niiickel** [comment]
you can do this by using the arguments at the bottom of the github page.

**Comment by henryruhs** [comment]
I have to think about it... probably saving the latest changes without any UI.

**Comment by 2348754114579** [comment]
FaceFusion doesn't support Google Colab. It produces a broken localhost link, I lost quite a few units. Someone should fix it.

**Comment by Anonymous7860** [comment]
can i use it on colab
if yes please guide me with steps please..

**Comment by basudee** [comment]
> Added to roadmap for release 2.2.0... defaults via JSON based `.facefusionrc` file.
> 
> ```json
> {
> 	"output": ".",
> 	"execution-providers":
> 	[
> 		"cuda"
> 	],
> 	"execution_thread_count": 16
> }
> ```

HI there! Where can I find this file exactly please? Thank you
