### ISSUE TITLE
ModuleNotFoundError: No module named 'filetype'

### ISSUE THREAD

**Issue by Neplex42** [facefusion/facefusion#242]
I just pulled the project to get the latest version and now I can't launch the application...

![image](https://github.com/facefusion/facefusion/assets/76078411/b4f90451-78cc-4f06-905c-319259822eb9)

**Comment by henryruhs** [comment]
> Please do not open platform and installation related issues on GitHub. We have a very helpful [Discord](https://join.facefusion.io/) community that will guide you to complete the installation.
