### ISSUE TITLE
simswap_256.onnx

### ISSUE THREAD

**Issue by qiuyuzhao** [facefusion/facefusion#243]
hello,  Where the simswap_256.onnx came from ingithub, I want use this repo to infer video. thanks

**Comment by henryruhs** [comment]
See https://github.com/facefusion/facefusion-assets

**Comment by qiuyuzhao** [comment]
> See https://github.com/facefusion/facefusion-assets
hello,  is convert simswap_224_latest_net_G.pth to simswap_256.onnx? thanks

**Comment by henryruhs** [comment]
nope
