### ISSUE TITLE
[BUG] Detect FPS Imported Incorrectly in Core.py - Always Defaults to 25fps 

### ISSUE THREAD

**Issue by ganicus** [facefusion/facefusion#245]
I believe you imported detect_fps incorrectly in the core.py file. 

Shouldn't it be imported from the vision.py NOT utilities.py?

```python
from facefusion.vision import get_video_frame, read_image, detect_fps
from facefusion import face_analyser, content_analyser, metadata, wording
from facefusion.content_analyser import analyse_image, analyse_video
from facefusion.processors.frame.core import get_frame_processors_modules, load_frame_processor_module
from facefusion.utilities import is_image, is_video, compress_image, merge_video, extract_frames, get_temp_frame_paths, restore_audio, create_temp, move_temp, clear_temp, list_module_names, encode_execution_providers, decode_execution_providers, normalize_output_path, normalize_padding, create_metavar, update_status
```

Currently, this always default to 25fps

```python
fps = detect_fps(facefusion.globals.target_path) if facefusion.globals.keep_fps else 25.0
```

**Comment by henryruhs** [comment]
Thanks for pointing out this falsy import. It is technical not wrong but not intended .

Fixed it in the next branch: https://github.com/facefusion/facefusion/commit/8f11bf17c90cc90bbd440afa9ba4bbde54da8e6e

This defaults to 25.0 as of the condtion:

```
fps = detect_fps(facefusion.globals.target_path) if facefusion.globals.keep_fps else 25.0
```

**Comment by ganicus** [comment]
Ah, correct! Sorry, I should have looked closer - victim of too much multitasking. 

Keep up the good work!

**Comment by 2348754114579** [comment]
FaceFusion doesn't support Google Colab. It produces a broken localhost link, I lost quite a few units. Someone should fix it.

This cell produces the link. Probably.

%cd /content/facefusion
!python run.py --execution-providers cuda & ssh -R 80:localhost:7860 remote.moe
