### ISSUE TITLE
Merging video failed

### ISSUE THREAD

**Issue by BoragoCode** [facefusion/facefusion#252]
Nvidia A10，show this error Merging video failed
To create a public link, set `share=True` in `launch()`.
[FACEFUSION.FRAME_PROCESSOR.FACE_SWAPPER] Processing
[FACEFUSION.CORE] Compressing image
[FACEFUSION.CORE] Processing to image succeed
Analysing: 100%|===============================================================================================| 180/180 [00:00<00:00, 785.54frame/s, rate=0]
[FACEFUSION.CORE] Creating temporary resources
[FACEFUSION.CORE] Extracting frames with 25.0 FPS
[FACEFUSION.FRAME_PROCESSOR.FACE_SWAPPER] Processing
Processing: 100%|=======================| 151/151 [01:00<00:00,  2.51frame/s, execution_providers=['cpu'], execution_thread_count=4, execution_queue_count=1]
[FACEFUSION.CORE] Merging video with 25.0 FPS
[FACEFUSION.CORE] Merging video failed

**Comment by henryruhs** [comment]
Make sure not to have non-latin characters in filenames and paths, there is a bug in one of our third party dependencies.
