### ISSUE TITLE
i want know why "show_api = True" take effect  and where is the api/docs ?

### ISSUE THREAD

**Issue by toby911** [facefusion/facefusion#255]
**### The following is the output result of running run.py**
ui.launch(show_api = True,server_name="0.0.0.0",share=True)
Running on local URL:  http://0.0.0.0:7860

Could not create share link. Missing file: /home/mty/miniconda3/envs/facefusion/lib/python3.10/site-packages/gradio/frpc_linux_amd64_v0.2. 

Please check your internet connection. This can happen if your antivirus software blocks the download of this file. You can install manually by following these steps: 

1. Download this file: https://cdn-media.huggingface.co/frpc-gradio-0.2/frpc_linux_amd64
2. Rename the downloaded file to: frpc_linux_amd64_v0.2
3. Move the file to this location: /home/mty/miniconda3/envs/facefusion/lib/python3.10/site-packages/gradio

**Comment by henryruhs** [comment]
On the Gradio website...
