### ISSUE TITLE
onnxruntime error on google colab

### ISSUE THREAD

**Issue by azoksky** [facefusion/facefusion#256]
Using facefusion today but I am getting this strange error. It worked so well till 2 days ago..

[E:onnxruntime:Default, provider_bridge_ort.cc:1480 TryGetProviderInfo_CUDA] /onnxruntime_src/onnxruntime/core/session/provider_bridge_ort.cc:1193 onnxruntime::Provider& onnxruntime::ProviderLibrary::Get() [ONNXRuntimeError] : 1 : FAIL : Failed to load library libonnxruntime_providers_cuda.so with error: libcufft.so.10: cannot open shared object file: No such file or directory

Reinstalled everything and still getting the same error.. 
Then I thought this could be an issue with colab's updated torch version 2.1.1 cu121, so I uninstalled the torch and installed the correct veersion of the torch like below

!pip uninstall torch torchvision torchaudio -y
!pip install torch==2.1.0 torchvision==0.16.0 torchaudio==2.1.0 --index-url https://download.pytorch.org/whl/cu118

The error still shows up.. 

Can you help?

**Comment by henryruhs** [comment]
Wrong repo to open that issue and we are aware of it.

**Comment by rickychaka** [comment]
check a post, need new pytorch?

https://twitter.com/camenduru/status/1736755452552110478

![Screenshot 2023-12-19 134554](https://github.com/facefusion/facefusion/assets/125632086/3f15eb58-6db7-4a91-b5b8-651116f02633)

**Comment by henryruhs** [comment]
the problem on colab is not pytorch, it's the onnxruntime as FF basically is using that.
