### ISSUE TITLE
why cuda not use in the version of facefusion2.0(cuda in released verison1.3 is available)

### ISSUE THREAD

**Issue by toby911** [facefusion/facefusion#257]
this is my venv package
![cuda not use](https://github.com/facefusion/facefusion/assets/112366887/f4901d6a-4911-4e48-bfa9-d08e10ad025d)

**Comment by toby911** [comment]
![cuda not use web](https://github.com/facefusion/facefusion/assets/112366887/fae58e79-9131-4e63-936f-0ede3f804d01)

**Comment by henryruhs** [comment]
Please do not open platform and installation related issues on GitHub. We have a very helpful [Discord](https://join.facefusion.io) community that will guide you to complete the installation.
