### ISSUE TITLE
run with CLI, TypeError '--frame-processors' args

### ISSUE THREAD

**Issue by iKora128** [facefusion/facefusion#259]
Thanks great job!!
I pulled latest code ver 2.1.0.
run with CLI, then Error occurred.

in Ver 2.0, I have't this error, and this error happened whatever argument I set even I didn't set `--frame-processors`
Is this Error happened only in my environment??
Please help!

```
group_frame_processors.add_argument('--frame-processors', help = wording.get('frame_processors_help').format(choices = ', '.join(available_frame_processors)), default = [ 'face_swapper' ], nargs = '+')
TypeError: can only join an iterable
```

**Comment by henryruhs** [comment]
That is an issue on your end, it works for me both with UI and headless mode.
