### ISSUE TITLE
Unexpected token '<', "<html> <h"... is not valid JSON

### ISSUE THREAD

**Issue by venshine** [facefusion/facefusion#264]
Unexpected token '<', "<html> <h"... is not valid JSON
![image](https://github.com/facefusion/facefusion/assets/1456580/3d962443-454a-4745-a341-e5106415db62)
I have completed the video face change, but at the last moment I reported an error. How should I deal with it? Some videos can.

**Comment by henryruhs** [comment]
That happens when the Gradio server is no longer running but the Gradio client tries to access it.
