### ISSUE TITLE
The model download is stuck

### ISSUE THREAD

**Issue by darknesscho** [facefusion/facefusion#268]
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Downloading:   0%|                                                                 | 6.97M/1.55G [00:30<3:57:27, 116kB/s]

Maybe there's something wrong with my network, but the http download is fine.
Could you please provide other ways to download the model or huggingface address

**Comment by henryruhs** [comment]
We don't use GitHub for support tickets. Use Discord, thanks.
