### ISSUE TITLE
Cuda and tensort keep disappearing as EXECUTION PROVIDERS

### ISSUE THREAD

**Issue by JJRobertsSex30** [facefusion/facefusion#269]
Had this problem when I upgraded to 2.0 but Cuda and tensort keep disappearing as EXECUTION PROVIDERS despite the fact that they are both installed correctly and are in the PATH leaving only Azure and CPU as the EXECUTION PROVIDERS both of which are slow as hell

Cuda is the fastest for me and with 2.0 I got around this problem by doing this

pip uninstall onnxruntime onnxruntime-gpu
pip install onnxruntime-gpu==1.16.0

And yes in both 2.0 and 2.1.1 this restores Cuda and tensorrt as option and gets rid of azure but in 2.0 this produced no errors but with 2.1.1, doing this to get Cuda back actually produces errors when start to try processing.

How can I fix this and get back to using Cuda with 2.1.1 ?

**Comment by henryruhs** [comment]
Please do not open platform and installation related issues on GitHub. We have a very helpful [Discord](https://join.facefusion.io) community that will guide you to complete the installation.
