### ISSUE TITLE
Trouble while using muliple source files

### ISSUE THREAD

**Issue by vduck** [facefusion/facefusion#270]
Try many ways to call cli cmd to use muliple source files,
but the output always says can't take it.

Please write more details about while calling cli cmd ( --headless ) use muliple source files in your help document, i can't find anything about that. How to built a commond string for passing to RUN.PY to running!

**Comment by henryruhs** [comment]
Just combine the `-s`arguments.

```
python run.py -s face1.jpg -s face2jpg -s face3jpg
```
