### ISSUE TITLE
Why does the processing of a video pause and not resume?

### ISSUE THREAD

**Issue by kof02guy** [facefusion/facefusion#275]
I'm using facefusion 2.1.2 and find that some video couldn't be processed successfully.
The process will be paused and never resume again.

`To create a public link, set `share=True` in `launch()`.
Analysing: 100%|====================================================| 3707/3707 [00:11<00:00, 329.99frame/s, rate=17.8]`

So it seemed that after Analysing, nothing would happen.
So how can I debug this or is there anything that I can do to solve this problem?

**Comment by henryruhs** [comment]
That is the NSFW filter being triggered.
