### ISSUE TITLE
facefusion EXECUTION PROVIDERS NOT cuda options?

### ISSUE THREAD

**Issue by chwshuang** [facefusion/facefusion#278]
facefusion EXECUTION PROVIDERS NOT cuda options?

my pc is windows10, 2080Ti  install facefusion 2.1.3 version

My problem has been resolved, solution:
step 1:
python -m pip uninstall onnxruntime onnxruntime-gpu
step2:
python -m pip install onnxruntime-gpu==1.15.1

**Comment by henryruhs** [comment]
Please use Discord for that, we don't provide support here.
