### ISSUE TITLE
Please tell me how to solve this problem

### ISSUE THREAD

**Issue by wibur0620** [facefusion/facefusion#281]
Is it because my c drive directory contains Chinese folders?

Currently, my folder is my win system username folder and I cannot change it.

how can i solve this problem

https://github.com/facefusion/facefusion/assets/131615326/3cef0e98-a115-4350-95aa-d72c96bcadbf

Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
[ WARN:0@39.973] global loadsave.cpp:248 cv::findDecoder imread_('C:\Users\绌虹伒\AppData\Local\Temp\gradio\2a81bb02c2b4ae917c3fa3f47080427d7b9ddd3a\225.png'): can't open/read file: check file path/integrity
[FACEFUSION.PROCESSORS.FRAME.MODULES.FACE_SWAPPER] No source face detected!
[FACEFUSION.PROCESSORS.FRAME.MODULES.FACE_SWAPPER] No source face detected!
[FACEFUSION.PROCESSORS.FRAME.MODULES.FACE_SWAPPER] No source face detected!
[FACEFUSION.PROCESSORS.FRAME.MODULES.FACE_SWAPPER] No source face detected!

**Comment by henryruhs** [comment]
Via Discord please.
