### ISSUE TITLE
can i know how can i send requests to this api 

### ISSUE THREAD

**Issue by baselqt** [facefusion/facefusion#287]
can i know how can i send requests to this api from an external python script using the requests module? i can't figure it out

**Comment by henryruhs** [comment]
sorry there is no api.

**Comment by NyanCetch** [comment]
> can i know how can i send requests to this api from an external python script using the requests module? i can't figure it out

If this is still relevant to you, you can make request directly in gradio. This is how I solved this problem, using the requests library.  The required parameters for requests can be found through Postman.  Basically, 2 fields are used: data and fn_index with the number of the desired action
