### ISSUE TITLE
FaceFusion not swaping faces

### ISSUE THREAD

**Issue by innovationaz** [facefusion/facefusion#289]
I installed all requirements and even few models, I can use Cuda or CPU, I used famous faces to make it easy to see the results. But unfortunately, the preview is not updating and the output is not updating the face as well. I changed back and fort all parameters with no success. Please advise.
![Screenshot 2024-01-02 082116](https://github.com/facefusion/facefusion/assets/138234346/6463019f-9a45-4bb7-8bd8-7ada3d70769a)

**Comment by henryruhs** [comment]
We don't give support via GitHub.

**Comment by innovationaz** [comment]
> We don't give support via GitHub.

Where can I get support then?

**Comment by henryruhs** [comment]
On our Discord: https://join.facefusion.io
