### ISSUE TITLE
CodeFormer parameters ?

### ISSUE THREAD

**Issue by psykokwak-com** [facefusion/facefusion#290]
Hi all,
Is there a way to set some codeformer parameters ?
Like upscale factor and fidelity factor ?
Thanks.

**Comment by henryruhs** [comment]
Codeformer does not have a upscale input but fidelity input. We did not expose those to prevent confusion with other models.

**Comment by psykokwak-com** [comment]
Oh okay.
Is there a way to improve the resolution of enhanced faces?
I find that the result lacks resolution.
Thanks

**Comment by henryruhs** [comment]
Only with the frame enhancer which indeed upscales. Let's continue on our Discord if you have more questions.
