### ISSUE TITLE
FRAME PROCESSORS: face_enhancer misplaced

### ISSUE THREAD

**Issue by websepia** [facefusion/facefusion#291]
misplace face_enhancer in "FRAME PROCESSORS" panel.

![image](https://github.com/facefusion/facefusion/assets/130173756/87dd7a69-04a5-42aa-a6c7-cbb0aa6a8216)

**Comment by henryruhs** [comment]
What is misplaced?

**Comment by websepia** [comment]
UI elements are still misplaced in this panel. 

The modules folder is like below.

    Directory: D:\ai\facefusion\.assets\models


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----        2023/11/29     23:52      209789238 arcface_simswap.onnx
-a----        2023/11/29     23:51      174383860 arcface_w600k_r50.onnx
-a----        2023/11/30      0:35     1661432957 blendface_256.onnx
-a----          2024/1/3      3:57     1661432957 blendswap_256.onnx
-a----          2024/1/1     22:50      376822019 codeformer.onnx
-a----        2023/12/23      2:04       70324403 face_occluder.onnx
-a----        2023/12/23      2:05       53201152 face_parser.onnx
-a----        2023/11/29     17:59        1322532 gender_age.onnx
-a----          2024/1/2      1:37      340256690 gfpgan_1.2.onnx
-a----          2024/1/2      0:28      340256690 gfpgan_1.3.onnx
-a----         2023/12/2      1:49      340256690 gfpgan_1.4.onnx
-a----          2024/1/2      2:11       75715262 gpen_bfr_256.onnx
-a----        2023/10/26      4:47      554253681 inswapper_128.onnx
-a----        2023/11/29     22:03      277288649 inswapper_128_fp16.onnx
-a----        2023/11/29     17:23       23590724 open_nsfw.onnx
-a----          2024/1/1     20:17       67061725 real_esrgan_x2plus.pth
-a----          2024/1/2      0:25       67040989 real_esrgan_x4plus.pth
-a----          2024/1/2      0:57       67040989 real_esrnet_x4plus.pth
-a----         2023/12/2      2:00      292022041 restoreformer.onnx
-a----        2023/11/29     17:26       16923827 retinaface_10g.onnx
-a----        2023/11/29     23:55      220368724 simswap_256.onnx
-a----        2023/11/30      0:01      239249034 simswap_512_unofficial.onnx
-a----        2023/11/29     17:26         232589 yunet_2023mar.onnx


PS D:\ai\facefusion\.assets\models>
