### ISSUE TITLE
UI elements misplaced in FRAME PROCESSORS panel

### ISSUE THREAD

**Issue by websepia** [facefusion/facefusion#293]
1. I did a pull before trying this branch.

remote: Enumerating objects: 45, done.
remote: Counting objects: 100% (45/45), done.
remote: Compressing objects: 100% (18/18), done.
remote: Total 45 (delta 27), reused 38 (delta 27), pack-reused 0
Unpacking objects: 100% (45/45), 18.84 KiB | 107.00 KiB/s, done.
From https://github.com/facefusion/facefusion
 * [new branch]      feat/block-until-post-check -> origin/feat/block-until-post-check
   5661631..9f39da1  next       -> origin/next
Already up to date.

2. Found the UI elements were still misplaced.
![image](https://github.com/facefusion/facefusion/assets/130173756/b3898fb0-a4d4-4ad6-bd7f-34e1fb9139d5)

Steps to reproduce:
1. Click to untick face_swapper radio button.
2. Click to tick it back.
3. Tick face_enhancer.
4. Tick face_debugger.

**Comment by websepia** [comment]
Repeat tick or untick checkboxs, you might have figured it out how these UI elements work abnormally.
![image](https://github.com/facefusion/facefusion/assets/130173756/8b3046ab-8f73-4337-9285-7f0ba50979f0)

**Comment by henryruhs** [comment]
Stop opening issues like that. I have no idea what your problem is but everything is placed like it is supposed to be.
