### ISSUE TITLE
rate differs , and it only works when its 0

### ISSUE THREAD

**Issue by Nour871** [facefusion/facefusion#295]
![Untitled](https://github.com/facefusion/facefusion/assets/155954819/6c296ff1-ba46-4c57-972c-c438d1b169a2)
I am using facefusion for the past 3 months , almost everyday , but it suddenly stopped working ,it freezes after analysing ,  it only works when the rate is zero and I dont know what happened or what is the problem , I just tried some short clips randomly and I notified that it only works when the rate is zero , and I dont know what is the that I am a normal user ( not a programmer or something ) , I am using facefusion 2.0.0 , any help please

**Comment by henryruhs** [comment]
It does not work with NSFW content.

**Comment by Nour871** [comment]
> It does not work with NSFW content.

I dont user NFSW content

**Comment by henryruhs** [comment]
of course not... nobody does until I ask them for the example video.

**Comment by Nour871** [comment]
> of course not... nobody does until I ask them for the example video.

if you have a solution just say it !

**Comment by henryruhs** [comment]
post the video please.
