### ISSUE TITLE
Support for Gradio Sharing/Tunneling

### ISSUE THREAD

**Issue by zachweinstein** [facefusion/facefusion#3]
I am creating a Google Colab notebook and want to enable a public Gradio tunnel. This is done by setting `share=True` to [launch()](https://github.com/facefusion/facefusion/blob/master/facefusion/uis/core.py). I propose using a flag --public-url

I can add this feature myself if you assign me to it.

**Comment by henryruhs** [comment]
I don't plan to forward the Gradio options via our CLI arguments. Either you find another way of doing it (without share=True) or ask Gradio to introduce a new `GRADIO_SHARE=TRUE` variable.
