### ISSUE TITLE
"I have three images and I want to simultaneously replace the faces of three specific individuals in a video. How can I achieve this, and is it possible to develop this feature in post-production?

### ISSUE THREAD

**Issue by zhangjinyan888** [facefusion/facefusion#30]
"I have three images and I want to simultaneously replace the faces of three specific individuals in a video. How can I achieve this, and is it possible to develop this feature in post-production?

**Comment by henryruhs** [comment]
Do you know the difference between a title / headline and a description?

The feature you are asking for is not implemented (yet) ... run it 3 times then.
