### ISSUE TITLE
Hey brother, why did you kick me out of the Discord chat room?

### ISSUE THREAD

**Issue by toby911** [facefusion/facefusion#301]
Hey brother, why did you kick me out of the Discord chat room? My account is Toby_ 31226, what did I violate? Please tell me, I am very depressed
![image](https://github.com/facefusion/facefusion/assets/112366887/dc30484d-ec9a-4b70-a4c4-1d3974d7bd42)

**Comment by toby911** [comment]
I'm not a scammer, I'm so wrongly accused

**Comment by henryruhs** [comment]
we ban people asking how to disable NSFW - now you are banned here as well.
