### ISSUE TITLE
Opencv error

### ISSUE THREAD

**Issue by Tbrock8905** [facefusion/facefusion#302]
Installed the extension on automatic1111

Face recognition works and frame preview does too. 
When I click start, it gives me this error 

cv2.destroyAllWindows()  # pylint: disable=no-member
cv2.error: OpenCV(4.9.0) D:\a\opencv-python\opencv-python\opencv\modules\highgui\src\window.cpp:1266: error: (-2:Unspecified error) The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Cocoa support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script in function 'cvDestroyAllWindows'

**Comment by henryruhs** [comment]
We are not providing support here. It's kinda easy to find the error via Google or via our documentation.

https://docs.facefusion.io/troubleshooting#solution-to-most-opencv-errors
