### ISSUE TITLE
Slow performance inline cam mode, can't get other cam modes working

### ISSUE THREAD

**Issue by borick** [facefusion/facefusion#304]
using a NVidia graphics card. Any way to make it faster? Thanks

**Comment by henryruhs** [comment]
Gradio is the limiting factor, you have to use UDP.

**Comment by borick** [comment]
UDP is quite fast (in the console) but nothing actually shows up...

**Comment by henryruhs** [comment]
Join our [Discord](https://join.facefusion.io) for help - you have to load it in OBS or similar.
