### ISSUE TITLE
udp cam mode doesn't show up

### ISSUE THREAD

**Issue by borick** [facefusion/facefusion#305]
udp cam mode doesn't work

**Comment by borick** [comment]
<img width="573" alt="image" src="https://github.com/facefusion/facefusion/assets/10510235/631e41b0-4016-4359-abc6-91d3a7c76602">

**Comment by borick** [comment]
the inline mode works though

**Comment by henryruhs** [comment]
Use [Discord](https://join.facefusion.io) for further questions... this is intended behaviour as the inline rendering would slow down the performance.
