### ISSUE TITLE
Updated and installed version 2.1.3, facial enhancement doesn't work and can't connect to discord, begging for an answer!

### ISSUE THREAD

**Issue by petercham** [facefusion/facefusion#306]
Thank you very much for your great feat! I can't join the community to find a solution because China is blocking discord, so I'm begging to be able to help with the answer!

It feels like there's an error reported by onnx, hopefully you can print out the exception a bit more specifically in the console

**Comment by petercham** [comment]
Can I ask if this fix is the solution to this problem?
https://github.com/facefusion/facefusion/pull/229/commits/81cc3070a57471d627e3a1edd04916bcebe8e9f6

**Comment by petercham** [comment]
> Thank you very much for your great feat! I can't join the community to find a solution because China is blocking discord, so I'm begging to be able to help with the answer!
> 
> It feels like there's an error reported by onnx, hopefully you can print out the exception a bit more specifically in the console

Perhaps the new version needs to update the startup commands by adding the
 --frame-processors face_swapper face_enhancer to enable enhance

If it's not activated this way, sometimes clicking the switch on in the UI won't take effect.
I hope that in the case where the enhance is invalid due to a similar situation, you can print out the exception while returning the result of the fuzzy face swap, instead of ignoring the situation.

**Comment by henryruhs** [comment]
Sorry, but I will not have a troubleshoot conversation here - if everyone does this, my whole day gonna consists of GitHub issues like that.
