### ISSUE TITLE
WHY??

### ISSUE THREAD

**Issue by d8ahazard** [facefusion/facefusion#309]
WHY? Why the extra spaces where they don't belong?

<img width="365" alt="image" src="https://github.com/facefusion/facefusion/assets/1633844/0691c96c-2fcd-4dc2-a8e8-0336ccd0b71d">

Why ignore PEP standards and cram this thing full of tabs instead of spaces?

Why does every long line have no breaks?

Why do you insist on re-naming models every other week?

<img width="603" alt="image" src="https://github.com/facefusion/facefusion/assets/1633844/935facd2-568c-4bcc-8aab-e99202adf0f8">

Why are you constantly moving methods around, re-naming them, then moving them somewhere else a week later?

Do you use an IDE?

Like, please, if you just made an ATTEMPT at working with normal python standards, versus "No, I like doing whatever I want, regardless of what the rest of the sane world does.", you'd probably have a lot more contributors to this project...

Because I've said this before - I would LOVE to contribute to this project. But due to all of the above, and the attitude I get when I make any kind of suggestion...I'm just going to sit over here and silently shake my fist instead...

**Comment by d8ahazard** [comment]
https://peps.python.org/pep-0008/

**Comment by d8ahazard** [comment]
<img width="461" alt="image" src="https://github.com/facefusion/facefusion/assets/1633844/ff2ebb52-7024-4a0d-9206-62c1b5484798">

**Comment by d8ahazard** [comment]
<img width="611" alt="image" src="https://github.com/facefusion/facefusion/assets/1633844/99a576f2-f7b6-4fae-b9a3-81f77ff6256f">

**Comment by henryruhs** [comment]
We are doing this to piss you off...
