### ISSUE TITLE
it takes forever!

### ISSUE THREAD

**Issue by azamet90** [facefusion/facefusion#320]
![image](https://github.com/facefusion/facefusion/assets/44042178/cc0bf9be-9e48-44c0-9844-43a170e7e1d2)
![image](https://github.com/facefusion/facefusion/assets/44042178/4508a5d8-d92b-4432-9384-1799008b1728)
amd rx 6900 xt gpu and i can say it is not working. why am i doing wrong here? it is only 1 image!

and i cannot see any peak on gpu/cpu usage!

**Comment by henryruhs** [comment]
We don't use GitHub as a support ticket system. Join our Discord for help.

**Comment by azamet90** [comment]
> We don't use GitHub as a support ticket system. Join our Discord for help.

i did but no one of 405 online people wont answer...
