### ISSUE TITLE
Script not working

### ISSUE THREAD

**Issue by giricahunik** [facefusion/facefusion#326]
Hello! I installed everything based on the installation guide but the script ended up not working. when I try to input photos and press start it says error and the CLI says something like in the screenshot 1. After that, I relaunched it with py run.py --execution-providers cuda and try changing face swapper model (download already finished) also resulting in error message "connection errored out" and the script stopped. I am pretty sure doing everything based on installation suggestion. even reinstalling it but no change.

![error face fusion 1](https://github.com/facefusion/facefusion/assets/12237797/85b8cff1-c3a4-4f75-ab66-83e47539baf6)
![error face fusion 2](https://github.com/facefusion/facefusion/assets/12237797/952738a9-b949-4085-9b87-6e575752c460)

**Comment by henryruhs** [comment]
We don't give support here. Join Discord for help.
