### ISSUE TITLE
[FACEFUSION.PROCESSORS.FRAME.MODULES.FACE_ENHANCER] Download of the model is not done!

### ISSUE THREAD

**Issue by tankzhangying** [facefusion/facefusion#331]
[FACEFUSION.PROCESSORS.FRAME.MODULES.FACE_ENHANCER] Download of the model is not done!

**Comment by tankzhangying** [comment]
how can i get the FACE_ENHANCER model ?

**Comment by henryruhs** [comment]
I think you either did not activate venv or need to update pip itself.

More help in our Discord.
