### ISSUE TITLE
Can Facefusion support DirectMLExecutionProvider in the future，

### ISSUE THREAD

**Issue by zhangjinyan888** [facefusion/facefusion#340]
def map_torch_backend(execution_providers: List[str]) -> str:
    if 'CoreMLExecutionProvider' in execution_providers:
        return 'mps'
    if 'CUDAExecutionProvider' in execution_providers or 'ROCMExecutionProvider' in execution_providers:
        return 'cuda'
    if 'OpenVINOExecutionProvider' in execution_providers:
        return 'mkl'
    if 'DirectMLExecutionProvider' in execution_providers:  
        return 'dml'
    return 'cpu'
Can Facefusion support DirectMLExecutionProvider in the future，

**Comment by henryruhs** [comment]
Hey, excuse me but FF does.

**Comment by zhangjinyan888** [comment]
Does torch_directml also support Windows systems?

**Comment by henryruhs** [comment]
Only Windows... btw. you are talking with a Linux person.

Join our Discord for more questions.
