### ISSUE TITLE
cannot import name 'Any' from partially initialized module 'typing' (most likely due to a circular import) 

### ISSUE THREAD

**Issue by shenbushou** [facefusion/facefusion#343]
why?

Traceback (most recent call last):
  File "d:\chengxuheji\facefusion-master\facefusion\installer.py", line 1, in <module>
    from typing import Dict, Tuple
  File "d:\chengxuheji\facefusion-master\facefusion\typing.py", line 1, in <module>
    from typing import Any, Literal, Callable, List, Tuple, Dict, TypedDict
ImportError: cannot import name 'Any' from partially initialized module 'typing' (most likely due to a circular import) (d:\chengxuheji\facefusion-master\facefusion\typing.py)

**Comment by shenbushou** [comment]
this error from '  from onnxruntime.capi._pybind_state import get_available_providers  # noqa: F401',when the program import Any from typing. circular import happen ,because of you try to import ,so we can hardly find the reason why cuda not work .this error fonud in three of my friends...we dont know how to solve it.please check

**Comment by henryruhs** [comment]
Why? Because you are not reading...

From our README:

> Please do not open platform and installation related issues on GitHub. We have a very helpful [Discord](https://join.facefusion.io/) community that will guide you to complete the installation.
> 
> Get started with the [installation](https://docs.facefusion.io/installation) guide.

Our installation guide then will point you to install Python 3.10 - you have a version lower I guess.
