### ISSUE TITLE
Slowed processing rate towards end of video

### ISSUE THREAD

**Issue by lachlancahill** [facefusion/facefusion#348]
Firstly, thank you for this amazing tool. Just raising a minor performance issue I am hoping to understand further. 

At the start for the first half of the video it processes at approx 15-20 frames/s. This then drops to closer to 5 frames/s for the latter-middle quartile, and 2 frames/s for the last quarter (it is a more gradual decline in speed than described above).

During the periods of lower performance I have lower CPU utilisation (approx 50% vs 100% during faster processing) and GPU utilisation is more volatile during lower performance. A have a lot of spare system memory and video memory so these are not bottlenecks. 

System information:
GPU: RTX 3090 (24GB)
CPU: i9-9900k
RAM: 64GB
OS : Windows 11

Configuration:
Execution Thread Count: 128
Execution Queue Count: 10
System Memory Limit: 22GB
Target Video: 1080p, 24fps, 228505 frames total

**Comment by henryruhs** [comment]
Please understand, we are not using GitHub issues as a support ticket system. Join our [Discord](https://join.facefusion.io) to chat with us about your issues.

From I see, you have a wrong understanding of threads and queue count. It's way too high.
