### ISSUE TITLE
how to without the  [-s SOURCE_PATHS ] parameter

### ISSUE THREAD

**Issue by stonemason10** [facefusion/facefusion#349]
Processing video /root/autodl-tmp/temp/output/2023-09-12.mp4 
[FACEFUSION.PROCESSORS.FRAME.MODULES.FACE_SWAPPER] Select an image for source path!

How to use the cli command line without the  [-s SOURCE_PATHS ] parameter,only process the face-enhancer

**Comment by henryruhs** [comment]
By not enabling the face swapper... in the future you better join Discord for questions.
