### ISSUE TITLE
Run on local network and change port

### ISSUE THREAD

**Issue by jnpatrick99** [facefusion/facefusion#358]
Can you please provide clear instructions on how to run it on local network from another computer? Usually python projects allow to modify port and listen to 0.0.0.0. I can't seem to find it here! Thank you very much.
P.S. 7860 is busy on my end, also I usually have GPU on one computer and run UI from another, it's not a security threat, everything within same closed network.

**Comment by henryruhs** [comment]
Read the Gradio documentation.

**Comment by timvis** [comment]
export the according environment variable somehow or
just place it at the beginning of the command line to test the software in a headless system like this
GRADIO_SERVER_NAME=0.0.0.0 ./run.py
