### ISSUE TITLE
Headswap Models

### ISSUE THREAD

**Issue by quantarb** [facefusion/facefusion#359]
Hi there, it would be possible to add models that do headswaps?  While the standalone performance of the HeadSwap model is not the best, I've achieved remarkable results by first applying HeadSwap and then running output with another faceswap model like inswapper.

For reference, please see the following GitHub repositories:

https://github.com/e4s2023/E4S2023
https://github.com/LeslieZhoa/HeadSwap

**Comment by henryruhs** [comment]
We don't plan to integrate either of them.
