### ISSUE TITLE
Face change does not work for videos

### ISSUE THREAD

**Issue by chuyaowang** [facefusion/facefusion#372]
Hi, I am running the latest app on my M1 macbook. The face swapper works well for swapping faces on pictures, but whenever I chose a video as the target, it tells me to `select an image or video for the target path!`, as if the video is not recognized. What could be the issue?

**Comment by henryruhs** [comment]
Discord for help...

**Comment by chuyaowang** [comment]
Resolved. Video encoding issue.

**Comment by zhybangbang** [comment]
How was it solved?
