### ISSUE TITLE
[FACEFUSION.PROCESSORS.FRAME.CORE] Frame processor frame_enhancer could not be loaded

### ISSUE THREAD

**Issue by WHEREISSHE** [facefusion/facefusion#376]
Hi, there!
When I was trying to install FACEFUSION on my MacBook(M1), an error occurred with the note "[FACEFUSION.PROCESSORS.FRAME.CORE] Frame processor frame_enhancer could not be loaded".
I am wondering if you have any solution and I will be appreciated if there is any advice.

**Comment by henryruhs** [comment]
Help on Discord only.

**Comment by AmruthArunkumar** [comment]
where can I join the discord
Im also getting the same issue right now

**Comment by henryruhs** [comment]
https://join.facefusion.io
