### ISSUE TITLE
Can we swap hair with this?

### ISSUE THREAD

**Issue by sudip550** [facefusion/facefusion#385]
Can we swap hair at a same time with face swaping?

**Comment by henryruhs** [comment]
Nope

**Comment by aitarokyoyu1** [comment]
When trying to launch on Google Colab, the following problem occurs. Do you know how to solve it?

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
lida 0.0.10 requires kaleido, which is not installed.
llmx 0.0.15a0 requires cohere, which is not installed.
llmx 0.0.15a0 requires openai, which is not installed.
llmx 0.0.15a0 requires tiktoken, which is not installed.
sqlalchemy 2.0.25 requires typing-extensions>=4.6.0, but you have typing-extensions 4.5.0 which is incompatible.
pydantic-core 2.16.2 requires typing-extensions!=4.7.0,>=4.6.0, but you have typing-extensions 4.5.0 which is incompatible.
tensorflow-metadata 1.14.0 requires protobuf<4.21,>=3.20.3, but you have protobuf 4.24.2 which is incompatible.
