### ISSUE TITLE
Error.2024.2.16

### ISSUE THREAD

**Issue by aitarokyoyu1** [facefusion/facefusion#390]
When I launch it, the following problem occurs. Is there a solution?

ImportError: cannot import name '_initialize_variables' from 'keras.src.backend' (/usr/local/lib/python3.10/dist-packages/keras/src/backend/__init__.py)
connect_to localhost port 7860: failed.

**Comment by henryruhs** [comment]
We have to debug that one together on Discord.

**Comment by aitarokyoyu1** [comment]
Thanks!
