### ISSUE TITLE
cv2.error: OpenCV(4.9.0) 

### ISSUE THREAD

**Issue by wu-xiaochen** [facefusion/facefusion#395]
I am using  facefusion to swap face into a video (mp4), and there is an error "cv2.error: OpenCV(4.9.0) /Users/xperience/GHA-OpenCV-Python2/_work/opencv-python/opencv-python/opencv/modules/imgproc/src/resize.cpp:4152: error: (-215:Assertion failed) !ssize.empty() in function 'resize'"
Is there anyone know how to fix it please?

**Comment by wu-xiaochen** [comment]
Mac book 14 pro 16GB. M1

**Comment by henryruhs** [comment]
Discord

**Comment by francogrex** [comment]
Discord is a discussion forum/community, it doesn't replace Github, doesn't have the same functionalities for document management, search capacities and archiving etc.... It is indeed a pity that you opted to not tackle issues in here where it is 100% adapted for this very purpose.

**Comment by henryruhs** [comment]
@francogrex I respect your opinion, but having 1000 open issues would not help as well.
