### ISSUE TITLE
Any improvement behind roop?

### ISSUE THREAD

**Issue by zh-plus** [facefusion/facefusion#4]
Is the core function of this based on [roop](https://github.com/s0md3v/roop)? Have there been any improvements made to the algorithm or is it just focused on enhancing the UI? The code structure appears to be similar.

**Comment by henryruhs** [comment]
Changes made towards Roop:

- Dynamic UI based on Gradio
- Docker support for CPU and CUDA
- Replace --many-faces by --face-recognition that takes reference and many value
- Twin support: swap multiple faces by one face reference
- Introduce execution-queue-count to adjust processing per thread
- Rename execution-threads to execution-thread-count
- Global options direction, age and gender for face analyser
- Blur preview and processing hold when NSFW content has been detected
- Flip the quality best to worse from 0-100 to 100-0
- Built-in benchmark suite
- Intensive codebase cleanup

**Comment by USER62170** [comment]
error report

**Comment by slavakurilyak** [comment]
@henryruhs it would be great to see a list of FaceFusion features (aka changes) in the repo (README) or the docs (GitBook)
