### ISSUE TITLE
coreML not swapping.....remote access and batch processing

### ISSUE THREAD

**Issue by Itchy-Fingaz** [facefusion/facefusion#400]
Hi guys

first off all when I select CoreML or Azure it stops faceswapping in the temp and also the eventual output will not be swapped. Please advise. 

also:
I want to be able to reach my M1 when I am not home and put in new jobs. I managed to get the gradio interface on my phone and it also does the inference in preview which is great....but when I press the button it says it cant find the temporary files. and just halts. 

I would really also want to be able to do a batch overnight and wake up to them.

**Comment by henryruhs** [comment]
No need to open the issue here, I'm on the Discord and saw your message.

**Comment by Itchy-Fingaz** [comment]
that wasn't me but i'm glad i'm in good company :)

**Comment by Itchy-Fingaz** [comment]
how do I get in the discord?

**Comment by henryruhs** [comment]
https://join.facefusion.io
