### ISSUE TITLE
Washed out color when extracting frames from HDR videos

### ISSUE THREAD

**Issue by timlenardo** [facefusion/facefusion#401]
Videos shot on the recent iPhones use the [BT.2020](https://en.wikipedia.org/wiki/Rec._2020) color standard. This causes issues when extracting the frames for face swapping. Specifically, with the ffmpeg command currently implemented in FaceFusion, the colors become 'washed out': 
<img width="498" alt="Screenshot 2024-02-23 at 4 31 34 PM" src="https://github.com/facefusion/facefusion/assets/1915325/69398866-e06d-4d36-94e2-adf06eb91a86">

Per [this Reddit discussions](https://www.reddit.com/r/ffmpeg/comments/ob13k9/bad_colors_in_extracted_frames/) this is a common issue with BT.2020 videos. One commenter offers a [slew of options](https://www.reddit.com/r/ffmpeg/comments/ob13k9/comment/h3kwmzh/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button) you can add to the '-vf' param in the ffmpeg command. I've tested this within FaceFusion and confirmed that it helps quite a bit, although the colors still don't quite match the original input video. Specifically, the original color tone matches better, but the shadows are reduced significantly:

<img width="862" alt="Screenshot 2024-02-23 at 4 31 28 PM" src="https://github.com/facefusion/facefusion/assets/1915325/266725f8-d0e9-452c-b80d-36d93005bf56">

It feels like an improvement to me, and I'd be happy to submit a PR if the FaceFusion team would like. One slight catch is that these options require a version of ffmpeg with 'zscale' filter installed, so you have to check the ffmpeg installation. 

To implement this locally, I've added the following two functions to ffmpeg.py:

```
def has_zscale() -> bool:
	output = subprocess.check_output(['ffmpeg', '-filters'], text=True)
	if 'zscale' in output:
		return True
	return False

def is_hdr_video(target_path) -> bool: 
	output = subprocess.check_output(['ffprobe', '-v', 'error', '-select_streams', 'v:0', '-show_entries', 'stream=color_primaries,color_trc,colorspace', '-of', 'default=noprint_wrappers=1', target_path], text=True)
	if 'bt2020' in output:
		return True
	return False
```

And then used them in extract_frames():

```
def extract_frames(target_path : str, video_resolution : str, video_fps : Fps) -> bool:
	temp_frame_compression = round(31 - (facefusion.globals.temp_frame_quality * 0.31))
	trim_frame_start = facefusion.globals.trim_frame_start
	trim_frame_end = facefusion.globals.trim_frame_end
	temp_frames_pattern = get_temp_frames_pattern(target_path, '%04d')
	commands = [ '-hwaccel', 'auto', '-i', target_path, '-q:v', str(temp_frame_compression), '-pix_fmt', 'rgb24' ]
	
	vf_args = ""
	if trim_frame_start is not None and trim_frame_end is not None:
		vf_args = 'trim=start_frame=' + str(trim_frame_start) + ':end_frame=' + str(trim_frame_end) + ',scale=' + str(video_resolution) + ',fps=' + str(video_fps)
	elif trim_frame_start is not None:
		vf_args = 'trim=start_frame=' + str(trim_frame_start) + ',scale=' + str(video_resolution) + ',fps=' + str(video_fps)
	elif trim_frame_end is not None:
		vf_args = 'trim=end_frame=' + str(trim_frame_end) + ',scale=' + str(video_resolution) + ',fps=' + str(video_fps)
	else:
		vf_args = 'scale=' + str(video_resolution) + ',fps=' + str(video_fps)
#=== THIS IS WHERE WE ADD THE ARGS
	if is_hdr_video(target_path=target_path) and has_zscale():
		vf_args = vf_args + "zscale=t=linear:npl=100,format=gbrpf32le,zscale=p=bt709,tonemap=tonemap=hable:desat=0,zscale=t=bt709:m=bt709:r=tv"
	if vf_args != "":
		commands.extend([ '-vf', vf_args ])

	commands.extend([ '-vsync', '0', temp_frames_pattern ])
	return run_ffmpeg(commands)
```

Two points:
1. The params from the Reddit thread are a good start, but not quite right. I will continue to look better options. However, I figured I'd open a thread in the meantime, in case anyone in the community is a photo/video processing expert and knows a better solution. 
2. I suspect will be widespread with HDR video formats, and may well be solved by ffmpeg in due time. To that end, I'm not sure this is a change you'll want to implement. I'll defer to the team in charge. Let me know!

**Comment by henryruhs** [comment]
Hey, thanks for you investigation.

As you might figured out, this [colorspace](https://trac.ffmpeg.org/wiki/colorspace) topic is a minefield and quite hard to fix.  Some folks investigated duo [BT.601](https://en.wikipedia.org/wiki/Rec._601) mismatch and common statements are.

1. Removing acceleration

```
-hwaccel auto
```

2. CV2

> CV2 converts the image to RGB while reading and writing it

**Comment by henryruhs** [comment]
We are open for a pull request, but then we should fix the colorspace topic as a whole.

1. Implement a function that uses ffprobe with json output

```
ffprobe .assets/examples/target-240p.mp4 -print_format json -show_format -show_streams 
```

2. Parse that JSON and try to find the existing colorspace

3. Add it to the extract_frames() and merge_video()

4. Testing, testing, testing (this is not an easy task)

**Comment by ngoqquyen** [comment]
Thanks

**Comment by henryruhs** [comment]
I close that issue duo lack of response.

**Comment by timlenardo** [comment]
Fair enough. I don't have time to exhaustively test all different encoding formats at the moment, but will revisit if that changes. Thanks @henryruhs !
