### ISSUE TITLE
Expectations for the future "except for the front"

### ISSUE THREAD

**Issue by goumari** [facefusion/facefusion#406]
Good evening, facefusion is one of the easiest to use free software and one of the best treasures with beautiful images.
Request."
When I check the face when there is a lot of movement, more than 2 people, or when I change the face in profile, I get the following problems: "The face collapses like a jelly, when there are more than 2 people, both faces change and the face is blurred, when the face is in profile, the face is greatly blurred, the face does not blend with the intense movement".
If these problems are solved, it would be the best.
From now on, we will use the side view. Frontal view. I would like to see a mode that recognizes faces in all planes, including oblique side view.

**Comment by henryruhs** [comment]
We have a very helpful [Discord](https://join.facefusion.io) community that will guide you how to use FaceFusion.
