### ISSUE TITLE
select the variant of onnxruntime to install

### ISSUE THREAD

**Issue by Sevensleeper81** [facefusion/facefusion#409]
Hello! 

I have AMD 7900XTX GPU . 
At the install : [?] select the variant of onnxruntime to install: 
I hit default but its not working ..

![1](https://github.com/facefusion/facefusion/assets/89541210/c7f9a56f-92aa-45ed-af51-9354dd38760f)
![2](https://github.com/facefusion/facefusion/assets/89541210/af7bd91b-1fd9-4d86-b3ba-63d674a3ff36)
![3](https://github.com/facefusion/facefusion/assets/89541210/4493ce50-4622-4b3c-ba72-2127ba78afd6)

**Comment by henryruhs** [comment]
Well, read the docs...
