### ISSUE TITLE
Needs a pause and resume feature.

### ISSUE THREAD

**Issue by swianto** [facefusion/facefusion#412]
I know this is more of a request than an issue but I'm putting this here because I don't know the proper channel to put this into. 

Sometimes the process breaks due to hardware failure or other technical issues, and I can literally see the temp files in the temp folder but there's no way to resume progress.

Would be great if there was a "save progress" option, with regular autosaves.

**Comment by henryruhs** [comment]
Not sure we gonna implement this soon as I do not plan to save the "state of processing" including all the options.

**Comment by henryruhs** [comment]
Sorry, I gonna close that issue as this is not planned.
