### ISSUE TITLE
Video that becomes dark after face swapping

### ISSUE THREAD

**Issue by deallon** [facefusion/facefusion#415]
Hello, every time I swap a face the whole video becomes very dark.
so obviously when I try to change a second face the video is unwatchable.

I put screenshots so you can see

Are there any special adjustments to make? things to avoid?
rework the video in post-production.

<img width="895" alt="Screenshot 2024-03-01 160020" src="https://github.com/facefusion/facefusion/assets/32638702/7f04d977-3cbc-49b6-ace7-8e9423e9f7a5">
<img width="920" alt="Screenshot 2024-03-01 160151" src="https://github.com/facefusion/facefusion/assets/32638702/7e656b78-4eae-43e0-8f72-91670a799230">

**Comment by henryruhs** [comment]
Handling colorspace is a minefield that we try to avoid. Make sure source video is YUV422 and bt709.

**Comment by henryruhs** [comment]
![01](https://github.com/facefusion/facefusion/assets/1835397/04613637-f0e0-4eb6-8219-77da98a76591)
![02](https://github.com/facefusion/facefusion/assets/1835397/20ae0db2-e7e2-4007-9794-4a36acd4abdf)

Works on my machine.
