### ISSUE TITLE
output_video_fps missing default value

### ISSUE THREAD

**Issue by duantao74520** [facefusion/facefusion#417]
mayby blow is right

	group_output_creation.add_argument('--output-video-fps', help = wording.get('help.output_video_fps'), default = config.get_float_value('output_creation.output_video_fps', '25.0'), type = float)

**Comment by duantao74520** [comment]
and facefusion.ini should add this param

output_video_fps =

**Comment by henryruhs** [comment]
What are you talking about? https://github.com/facefusion/facefusion/blob/master/facefusion.ini#L53
