### ISSUE TITLE
Frequent crashes on 2.3

### ISSUE THREAD

**Issue by swianto** [facefusion/facefusion#418]
Breaks mid session, sometimes doesn't even start. 
![Screenshot (1)](https://github.com/facefusion/facefusion/assets/156164381/7374c71c-a9a9-4344-97f0-312bbae84d75)

**Comment by henryruhs** [comment]
We have a very helpful [Discord](https://join.facefusion.io) community that will guide you how to troubleshoot FaceFusion.

**Comment by swianto** [comment]
Ok thanks
