### ISSUE TITLE
new onnx of frame enhancer is so slow 

### ISSUE THREAD

**Issue by zhaoyun0071** [facefusion/facefusion#437]
1. in NEXT 

with esrgan x4 onnx 5s/frame

and temperature of PC is very HIGH

2. in master

with esrnet x4 pth 1.7frames/s

**Comment by henryruhs** [comment]
ONNX version is a bit slower but you compare different models. I'll try to optimize it more, but you have to live with it.

## 2.3.0

|  target_path                       |  benchmark_cycles   |  average_run   |  fastest_run   |  slowest_run   |  relative_fps   |
|------------------------------------|---------------------|----------------|----------------|----------------|-----------------|
|  .assets/examples/target-240p.mp4  |  5                  |  39.37         |  38            |  42.44         |  6.87           |


## 2.4.0

|  target_path                       |  benchmark_cycles   |  average_run   |  fastest_run   |  slowest_run   |  relative_fps   |
|------------------------------------|---------------------|----------------|----------------|----------------|-----------------|
|  .assets/examples/target-240p.mp4  |  5                  |  57.32         |  54.99         |  58.91         |  4.71           |

**Comment by henryruhs** [comment]
## FP16 @ 2.4.0

|  target_path                       |  benchmark_cycles   |  average_run   |  fastest_run   |  slowest_run   |  relative_fps   |
|------------------------------------|---------------------|----------------|----------------|----------------|-----------------|
|  .assets/examples/target-240p.mp4  |  5                  |  26.97         |  26.74         |  27.61         |  10.01          |
