### ISSUE TITLE
option --onnxruntime cuda-12.2 not working

### ISSUE THREAD

**Issue by ewwink** [facefusion/facefusion#439]
I run line below on kaggle which have cuda 12, but it still targeting cuda 11 and produce error
```
!python install.py --skip-venv --onnxruntime cuda-12.2
```

but solved by manual [install](https://onnxruntime.ai/docs/install/#install-onnx-runtime-gpu-cuda-12x)
```
pip install onnxruntime-gpu --extra-index-url https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/onnxruntime-cuda-12/pypi/simple/
```

need update the URL?

https://github.com/facefusion/facefusion/blob/1e2031e149af57e29caedf5eb612680588c9869f/facefusion/installer.py#L73-L74

**Comment by henryruhs** [comment]
Thanks for the report. I think it pulls the exact same wheel and your fix is related to something else.

> For Cuda 12.x, please use the following instructions to install from [ORT Azure Devops Feed](https://aiinfra.visualstudio.com/PublicPackages/_artifacts/feed/onnxruntime-cuda-12/PyPI/onnxruntime-gpu/overview)

This description referes to the URL that I use - they seem to change it every now and then. I updated the URL in the next branch but `aiinfra.pkgs.visualstudio.com` sounds also not correct to me. Like they have no final location where to provide their wheels.
