### ISSUE TITLE
onnxruntime error

### ISSUE THREAD

**Issue by TigerHH6866** [facefusion/facefusion#441]
[E:onnxruntime:Default, provider_bridge_ort.cc:1480 onnxruntime::TryGetProviderInfo_CUDA] D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1193 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "D:\facefusion\venv\lib\site-packages\onnxruntime\capi\onnxruntime_providers_cuda.dll

cannot use cuda

**Comment by henryruhs** [comment]
Please join our [Discord](https://join.facefusion.io) for help.

Deep link to the thread: https://discord.com/channels/1141812857462341693/1218512338928406529/1218686419594383491
