### ISSUE TITLE
*** ModuleNotFoundError: No module named 'inquirer'

### ISSUE THREAD

**Issue by Xxredz** [facefusion/facefusion#450]
Hello, I downloaded facefusion on StableDiffusion but immediately get this error when the install is complete:

*** Error running install.py for extension E:\Stable Diffusion\a1111\stable-diffusion-webui\extensions\facefusion.
*** Command: "E:\Stable Diffusion\a1111\stable-diffusion-webui\venv\Scripts\python.exe" "E:\Stable Diffusion\a1111\stable-diffusion-webui\extensions\facefusion\install.py"
*** Error code: 1
*** stderr: Traceback (most recent call last):
***   File "E:\Stable Diffusion\a1111\stable-diffusion-webui\extensions\facefusion\install.py", line 3, in <module>
***     from facefusion import installer
***   File "E:\Stable Diffusion\a1111\stable-diffusion-webui\extensions\facefusion\facefusion\installer.py", line 11, in <module>
***     import inquirer
*** ModuleNotFoundError: No module named 'inquirer'

I have Python 3.10.6 installed, why am I getting this error?

**Comment by henryruhs** [comment]
Please do not open platform and installation related issues on GitHub. We have a very helpful [Discord](https://join.facefusion.io) community that will guide you to complete the installation.

**Comment by Xxredz** [comment]
I can't join the discord.

**Comment by henryruhs** [comment]
Then you have to figure it out using ChatGPT or Google.
