### ISSUE TITLE
How do you enable tensorrt?

### ISSUE THREAD

**Issue by DIYMSG** [facefusion/facefusion#451]
I have it working with cuda but selecting tensorrt makes everything slower as if it's using the cpu. I installed tensorrt following this guide https://www.youtube.com/watch?v=cWFOKWIDFJ4

I'm using CUDA version 12.1

**Comment by henryruhs** [comment]
Please do not open platform and installation related issues on GitHub. We have a very helpful [Discord](https://join.facefusion.io) community that will guide you to complete the installation.
