### ISSUE TITLE
 Could not find a version that satisfies the requirement onnxruntime==1.17

### ISSUE THREAD

**Issue by gengxiz** [facefusion/facefusion#453]
macos10.15.5 
python3.11
error apeared when running python install.py
` [?] select the variant of onnxruntime to install:
 > default
`

`WARNING: Skipping onnxruntime as it is not installed.
ERROR: Could not find a version that satisfies the requirement onnxruntime==1.17.1 (from versions: 1.15.0, 1.15.1, 1.16.0, 1.16.1, 1.16.2, 1.16.3)
ERROR: No matching distribution found for onnxruntime==1.17.1
`

**Comment by henryruhs** [comment]
Read the docs.
