### ISSUE TITLE
MacOS, OSX, performance very slow

### ISSUE THREAD

**Issue by anubissbe** [facefusion/facefusion#462]
I have a Mac mini M2 pro with 24GB RAM.
Is it normal that the performance, to swap a face in a video of 7 min, is much slower then on a Geforce RTX3080 ?
And yes, I'm using both CPU and coreML together

**Comment by henryruhs** [comment]
That is the expected performance difference. NVIDIA is the AI leader and everyone optimized their software for CUDA. Apple on the other hand did not even enter the AI game - it's MicroSoft who added support for onnxruntime.
