### ISSUE TITLE
Skip "extracting frames" step when source video doesn't change? 

### ISSUE THREAD

**Issue by AlexTan08** [facefusion/facefusion#465]
I noticed that when I load a video, and then want to try multiple face images in sequence, facefusion runs the "[FACEFUSION.CORE] Extracting frames with a resolution of ..." step every time. For large videos it would be a big timesaver if it just knew that the source video & settings didn't change and it can reuse the frames. Is there a way for subsequent tries to reuse the initial extracted set? I realize that in that can you wouldn't be able to faceswap in place and would need to make a copy of each image, but could be ok (and a UX setting).

**Comment by henryruhs** [comment]
Why not send a pull request?
