### ISSUE TITLE
onnxruntime::python::CreateExecutionProviderInstance CUDA_PATH is set but CUDA wasn't  able to be loaded

### ISSUE THREAD

**Issue by qwerdf4** [facefusion/facefusion#469]
I can use facefusion 2.3.0 with cuda 12.3 cudnn9, but when i update to latest version, it cannot work for cuda, onnxruntime::python::CreateExecutionProviderInstance CUDA_PATH is set but CUDA wasn't  able to be loaded

**Comment by henryruhs** [comment]
Please us our latest install guide that includes the conda solution - for support GitHub is not the right place, we have Discord for that.
