### ISSUE TITLE
memory not freed on cuda?

### ISSUE THREAD

**Issue by cchance27** [facefusion/facefusion#47]
I haven't tested with the other processors but it seems when the preview is generated it takes up a few gigs of vram, and then when i run the generation it takes up ~1gb per thread or maybe little more, if i generate another video without closing the entire app it will climb to 16gb of vram in use (vram + shared ram), i think you may have forgot to either unload the models from vram after use, or to check if their already loaded before loading another copy.

**Comment by henryruhs** [comment]
You might send a love letter to Microsoft for not optimizing the onnxruntime - 1gb per thread is normal.

**Comment by cchance27** [comment]
That wasn’t the complaint, as I said on the second generation I’m seeing 16gb in use for 8 threads it doesn’t appear to be freeing vram between runs I believe

**Comment by petercham** [comment]
Yes, I've found the same problem, Vram is full after one fusion has been performed and doesn't release automatically
