### ISSUE TITLE
Unable to accept discord invite

### ISSUE THREAD

**Issue by Ccj0221** [facefusion/facefusion#471]
Hello, I would like to ask about discord's inability to accept invitations
Before I can through the link to the server, but recently a week or two I can't enter the server through the link https://discord.com/invite/daj9hrHHgF. I can access other servers like MJ normally, but I can't access this.
![image](https://github.com/facefusion/facefusion/assets/129196783/ffc7e9fc-06e0-48e3-b402-3d6d00812eb4)

My user name is chenjia_zh, was I accidentally added to the blacklist。

I am very sorry for raising the issue of this irrelevant program on the issue interface。

**Comment by henryruhs** [comment]
Use https://join.facefusion.io

**Comment by Ccj0221** [comment]
您好：        您的邮件已收到。         祝您学习进步，工作顺利，生活愉快！                                        ——陈朝佳

**Comment by henryruhs** [comment]
You are blocked for NSWF bypass request - that means no chance to get back on our server
