### ISSUE TITLE
Audio input UI element missing? 

### ISSUE THREAD

**Issue by wandrzej** [facefusion/facefusion#472]
I'm using Facefusion via the Pinokio launcher. When I select the lip_syncer, like this:
<img width="336" alt="image" src="https://github.com/facefusion/facefusion/assets/26924000/d8af8138-2b20-4978-b644-f5cdd5aaa1ad">

only new UI element I see is this 
<img width="330" alt="image" src="https://github.com/facefusion/facefusion/assets/26924000/729547da-eea4-4b8d-85b6-2776ab47b470">

When I click START, I get `[FACEFUSION.PROCESSORS.FRAME.MODULES.LIP_SYNCER] Select a audio for source path!` so it clearly is looking for a source of audio (for a second I thought the video is stripped into audio path).

**Comment by henryruhs** [comment]
Please use Discord for support, GitHub is a issue tracker for software - not a support ticket system.

**Comment by wandrzej** [comment]
> Please use [Discord](https://join.facefusion.io) for support, GitHub is a issue tracker for software - not a support ticket system.

sorry if I phrased it incorrectly, but I'm not asking how to use the app, I'm reporting a bug that leads to errors and unexpected behaviour.  That is what issue trackers are for, right?

**Comment by henryruhs** [comment]
> Select a audio for source path!
