### ISSUE TITLE
module 'backend_interagg' has no attribute 'FigureCanvas' [FACEFUSION.PROCESSORS.FRAME.MODULES.FACE_SWAPPER] Download of the model is not done!

### ISSUE THREAD

**Issue by hlz217057** [facefusion/facefusion#474]
module 'backend_interagg' has no attribute 'FigureCanvas'
[FACEFUSION.PROCESSORS.FRAME.MODULES.FACE_SWAPPER] Download of the model is not done!

**Comment by henryruhs** [comment]
Please join [Discord](https://join.facefusion.io) for troubleshooting.
