### ISSUE TITLE
[ONNXRuntimeError] : 7 : INVALID_PROTOBUF

### ISSUE THREAD

**Issue by rehanahamed240** [facefusion/facefusion#475]
sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from ff3cuda/facefusion/.assets/models/inswapper_128_fp16.onnx failed:Protobuf parsing failed.

getting this error in last three days and i am not able to resolve it please help me

**Comment by henryruhs** [comment]
From the announcement in our [Discord](https://join.facefusion.io) - I highly recommend to join.

> I updated the `inswapper_128.onnx` and `inswapper_128_fp16.onnx` today to support CUDA 12. Regrettably, this could lead to corrupted models due mixing remote and local versions instead of re-downloading them. Please remove both files in your `.assets/models` directory to resolve this issue. Sorry
