### ISSUE TITLE
The file name is incorrect

### ISSUE THREAD

**Issue by 15092368540** [facefusion/facefusion#479]
The file name is face_landmarker_68_5.onnx, but the downloaded file name is face_landmarker_5_68.onnx

**Comment by henryruhs** [comment]
Please update via `git pull` ... your code is outdated.

**Comment by henryruhs** [comment]
Are you sure? I don't have that problem on my side.

```python
'face_landmarker_68':
{
	'url': 'https://github.com/facefusion/facefusion-assets/releases/download/models/2dfan4.onnx',
	'path': resolve_relative_path('../.assets/models/2dfan4.onnx')
},
'face_landmarker_68_5':
{
	'url': 'https://github.com/facefusion/facefusion-assets/releases/download/models/face_landmarker_68_5.onnx',
	'path': resolve_relative_path('../.assets/models/face_landmarker_68_5.onnx')
}
```

![image](https://github.com/facefusion/facefusion/assets/1835397/9cd55bf4-c985-4851-986d-543e6d67f108)

**Comment by 15092368540** [comment]
When I manually download the model file, I get the error that the saved file name is inconsistent, can renaming the downloaded file solve the problem?
![error file name](https://github.com/facefusion/facefusion/assets/49462433/68276488-2659-45bd-8da4-3018389eadc8)

**Comment by henryruhs** [comment]
Honestly, I have no idea what you are doing.

Use `--force-download` to get all models downloaded at once.

**Comment by 15092368540** [comment]
thank you

**Comment by 15092368540** [comment]
thx

**Comment by 15092368540** [comment]
In some regions, GitHub can only be accessed through a proxy, Use --force-download Unable to download model, It can only be downloaded manually via the web page
