### ISSUE TITLE
error on cuda 

### ISSUE THREAD

**Issue by superhandishere** [facefusion/facefusion#48]
command with _python run.py --execution-providers cuda_
returns
run.py: error: argument --execution-providers: invalid choice: 'cuda' (choose from 'cpu')
installed cuda toolkit 12.2 and cuDNN for cuda 12.x, don't know if it's compatible

**Comment by henryruhs** [comment]
> Be aware, the installation needs technical skills and is not for beginners. Please do not open platform and installation related issues on GitHub. We have a very helpful [Discord](https://join.facefusion.io/) community that will guide you to install FaceFusion.

**Comment by 332123342** [comment]
pip uninstall onnxruntime -y
pip install onnxruntime-gpu==1.15.1

python run.py --execution-providers cuda

**Comment by henryruhs** [comment]
> Be aware, the installation needs technical skills and is not for beginners. Please do not open platform and installation related issues on GitHub. We have a very helpful [Discord](https://join.facefusion.io/) community that will guide you to install FaceFusion.
