### ISSUE TITLE
Run error

### ISSUE THREAD

**Issue by petercham** [facefusion/facefusion#485]
GPU server:
(facefusion) PS C:\Work\AI-Service\facefusion-webapi.2.5.0> python run.py
[FACEFUSION.PROCESSORS.FRAME.CORE] Frame processor face_swapper could not be loaded

Another notebook：
(facefusion) PS E:\work/python\facefusion-2.5.0> python run.py
Running on local URL: http://127.0.0.1:7860/
[FACEFUSION.PROCESSORS.FRAME.MODULES.FACE_SWAPPER] Download of the model is not done!

**Comment by henryruhs** [comment]
Help via [Discord](https://join.facefusion.io).
