### ISSUE TITLE
Discord is the bug ... I have logged in 3 times - never found anything I wanted ^^

### ISSUE THREAD

**Issue by kalle07** [facefusion/facefusion#488]
OK nevertheless
i run all install steps 
all runing fine
local server starts, UI in browser starts
i choose an image 
i choose a video
i can watch the preview with the swaped face
i press start

the conda window shows progress from 0 to 100 aprox 30sec
...
Analysing: 100%|====================================================| 9642/9642 [01:03<00:00, 151.00frame/s, rate=55.7]

after that cursor is flashing ,nothign happened ... 5min

**Comment by henryruhs** [comment]
does not work with porn
