### ISSUE TITLE
How to output the result of real-time processing webcam video stream to OBS?

### ISSUE THREAD

**Issue by 522933055** [facefusion/facefusion#490]
The UI of Facefusion displays the real-time face fusion effect, but I wish to import it into my camera or other OBS.

**Comment by henryruhs** [comment]
See https://docs.facefusion.io/usage/deepfake-webcam

**Comment by 522933055** [comment]
> See https://docs.facefusion.io/usage/deepfake-webcam

Thank you for your response. However, the three modes mentioned in the link seem to refer to the types of inputs for Facefusion, right? It doesn't seem to mention any output types.
