### ISSUE TITLE
Option to NOT using hardware accelerator for ffmpeg

### ISSUE THREAD

**Issue by ganicus** [facefusion/facefusion#494]
Using the defacto 'ffmpeg -hwaccel auto' at the beginning of each ffmpeg command for frame extraction/video decoding might actually be slower on systems running better CPUs.

**Comment by henryruhs** [comment]
@ganicus Can you prove that statement with benchmarks?

**Comment by ganicus** [comment]
I'll do some more in depth testing when I get a chance - I took some screenshots yesterday just trying out ffmpeg commands on the system I was running (runpod 4090 instance with epyc cpu). 

Please see the command at top of the screen and the speed at bottom:

![Screenshot 2024-04-15 at 4 33 28 PM](https://github.com/facefusion/facefusion/assets/1510161/86385d95-b2ad-414a-941f-1732425a9238)
![Screenshot 2024-04-15 at 4 32 43 PM](https://github.com/facefusion/facefusion/assets/1510161/5439bf0e-c27c-4b95-87dc-94dfff3d449d)

I'm working on another project today but will see if I have sometime to get more specifics on system and benchmarks when I can.

**Comment by henryruhs** [comment]
Okay, so we are talking about the frame extraction.

## Normal mode

```
time ffmpeg -i target-2160p.mp4 -vf "fps=25" frames/frame_%04d.png

frame=  270 fps= 92 q=-0.0 Lsize=N/A time=00:00:10.76 bitrate=N/A speed=3.67x    

real	0m3.037s
user	1m19.811s
sys	0m1.035s
```

## Acceleration mode

```
time ffmpeg -hwaccel auto -i target-2160p.mp4 -vf "fps=25" frames/frame_%04d.png

frame=  270 fps= 83 q=-0.0 Lsize=N/A time=00:00:10.76 bitrate=N/A speed=3.29x    

real	0m3.391s
user	1m22.000s
sys	0m1.094s
```

**Comment by ganicus** [comment]
Yes - only the frame extraction.

Also jpg extraction is much faster. 

Currently I believe that png is the default for the ui? Smaller file sizes with png though. I understand the trade off.

**Comment by henryruhs** [comment]
I used our benchmark suite - disabled all frame processors, so it does only ffmpeg processing.

## every accelerator enabled

![every-accelerator enabled](https://github.com/facefusion/facefusion/assets/1835397/e12d529a-182f-49e4-b180-49fcaf24d866)

## accelerator extract frames only
![accelerator-extract-frames-only](https://github.com/facefusion/facefusion/assets/1835397/4fc7036e-747e-4cc1-baa7-3ae40d64e103)


## accelerator merge video only
![accelerator-merge-video-only](https://github.com/facefusion/facefusion/assets/1835397/1779a3b9-9a4b-4096-a186-01874444a191)

## no accelerators at all
![no-accelerators-at-all](https://github.com/facefusion/facefusion/assets/1835397/d69c58bb-5c7a-4e04-9099-e86a50e1853c)

**Comment by henryruhs** [comment]
I now run it against ffmpeg 7.0 and that one has a similar effect - but overall slower in low resolution and faster on higher.

## every accelerator enabled
![every-accelerator-enabled](https://github.com/facefusion/facefusion/assets/1835397/92adf26a-ae86-421a-8937-526c1ca1f1a3)

## no accelerators at all
![no-accelerators-at-all](https://github.com/facefusion/facefusion/assets/1835397/9d76a947-437f-42bb-89d4-542710292d96)

**Comment by ganicus** [comment]
What are your system specs?

I ran mine on:
AMD EPYC 75F3 32-Core Processor
64GB RAM
RTX 4090

**Comment by henryruhs** [comment]
13900K
4090

I will ask in the community what their experience is, we might just remove it overall.

**Comment by henryruhs** [comment]
It turns out that `-hwaccel auto` results in an error on my platform. Not sure why this is slower as it should fallback to CPU.

```
[AVHWDeviceContext @ 0x60e748a07d00] libva: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[AVHWDeviceContext @ 0x60e748a07d00] Failed to initialise VAAPI connection: -1 (unknown libva error).
```

I asked my team mate - his results are faster using `-hwaccel auto`.

**Comment by henryruhs** [comment]
## 2.5.1
![image](https://github.com/facefusion/facefusion/assets/1835397/abf9b790-f10a-4437-85fe-21afd78c6da5)

## 2.5.1 without hwaccel auto
![image](https://github.com/facefusion/facefusion/assets/1835397/9024ed89-323e-46a4-a532-df98a5589cad)

I got another benchmark - therefore removed it from the ffmpeg.py - it just landed in the next branch and will be release via 2.5.2.

Thanks.

**Comment by ganicus** [comment]
It's worth exploring that the standard ffmpeg that ships with most package managers doesn't come compiled with nvidia cuda hardware acceleration support. See the following link about how ffmpeg can be compiled with cuda hw acceleration. 

https://docs.nvidia.com/video-technologies/video-codec-sdk/11.1/ffmpeg-with-nvidia-gpu/index.html#compiling-ffmpeg

Could be worth looking into to test and add documentation. I'll take a stab if my current workflow allows.

**Comment by henryruhs** [comment]
Everything that does not come pre-compiled will not be supported, easy as that.
