### ISSUE TITLE
[BUG]Frequent errors and lack of models

### ISSUE THREAD

**Issue by lckj2009** [facefusion/facefusion#498]
Hello, after running "Python run. py" and opening the webpage, it runs normally. However, I have noticed that at certain times, clicking the "start" button will result in the following error:

https://github.com/facefusion/facefusion-assets/releases/download/models/span_kendata_x4.onnx
[FACEFUSION.PROCESSORS.FRAME.MODULES.FACE_ENHANCER] Download of the model is not done!

I have downloaded all the plugin models under "facefusion/. sets/models"
To be on the safe side, I also created a models folder in the facefusion directory and put all these models in it. However, this error seems to still exist. How can I solve it? Where should I place the model better?
Here are all the models I downloaded from my end, all of which are placed in the models folder:

![cuowu1](https://github.com/facefusion/facefusion/assets/52185194/42f14e9a-af6e-45c6-89e2-2f7bb89cb601)
![cuowu2](https://github.com/facefusion/facefusion/assets/52185194/042dad83-bf4c-4abe-b5d2-ab95c49c6ce4)

**Comment by henryruhs** [comment]
I assume your internet connection is not the best. FaceFusion does remote lookups on GitHub and downloads models on the fly in the case those are not present.

The directory you picked is wrong. It is:

- facefusion/.assets/models
- facefusion/run.py

Our documentation includes a search, if you would have used it then you could prevent all the trouble.

1. `--force-download` to download every model and exit
2. `--skip-downloas` to prevent the remote lookups and downloads

**Comment by lckj2009** [comment]
> 2\. to prevent the remote lookups and downloads

Hello, may I ask if all the models in the picture above have been downloaded? So just put it in the "facefusion/. sets/models" folder?
Also, the startup command you suggested should be this one:
Python run. py -- skip downloads

**Comment by henryruhs** [comment]
Please read my post carefully... all has been said already
