### ISSUE TITLE
how to change ip and port of UI?

### ISSUE THREAD

**Issue by fansongy** [facefusion/facefusion#500]
I'd like to run the service in a linux server which has port limited, so I want to change url from  
http://127.0.0.1:7860 
to 
http://0.0.0.0:9988

how can I do that?

I tried

```
python run.py --listen
```

It seems not work

**Comment by henryruhs** [comment]
GRADIO_SERVER_NAME=0.0.0.0 GRADIO_SERVER_PORT=9988

We do not give support here, for more join Discord.
