### ISSUE TITLE
not found api-ms-win-appmodel-runtime-l1-1-2.DLL

### ISSUE THREAD

**Issue by pope-L** [facefusion/facefusion#51]
not found api-ms-win-appmodel-runtime-l1-1-2.DLL
Can anyone  upload the file,please

**Comment by henryruhs** [comment]
> Be aware, the installation needs technical skills and is not for beginners. Please do not open platform and installation related issues on GitHub. We have a very helpful [Discord](https://join.facefusion.io) community that will guide you to install FaceFusion.
