### ISSUE TITLE
Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)

### ISSUE THREAD

**Issue by MostafaBalba** [facefusion/facefusion#511]
i can't find any fix for this

(facefusion) D:\FaceFusion 2024\facefusion>python run.py
Running on local URL:  http://127.0.0.1:7860
Analysing: 100%|=========================================================| 161/161 [00:00<00:00, 465.10frame/s, rate=0]
[FACEFUSION.CORE] Extracting frames with a resolution of 478x850 and 30.0 frames per second
[FACEFUSION.CORE] Extracting frames failed
[FACEFUSION.CORE] Extracting frames with a resolution of 478x850 and 30.0 frames per second
[FACEFUSION.CORE] Extracting frames failed
Analysing: 100%|=========================================================| 452/452 [00:00<00:00, 455.72frame/s, rate=0]
[FACEFUSION.CORE] Extracting frames with a resolution of 576x1024 and 30.0 frames per second
[FACEFUSION.PROCESSORS.FRAME.MODULES.FACE_SWAPPER] Processing
Processing: 100%|=| 452/452 [00:24<00:00, 18.69frame/s, execution_providers=['cuda'], execution_thread_count=4, executi
[FACEFUSION.CORE] Merging video with a resolution of 576x1024 and 30.0 frames per second
[FACEFUSION.CORE] Processing to video succeed in 29.10 seconds
Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "C:\Users\devmo\miniconda3\envs\facefusion\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\devmo\miniconda3\envs\facefusion\lib\asyncio\proactor_events.py", line 165, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

**Comment by henryruhs** [comment]
Windows Firewall... you can ignore it
