### ISSUE TITLE
 Frame processor face_swapper could not be loaded

### ISSUE THREAD

**Issue by Raymond0529** [facefusion/facefusion#513]
for some reason, could not join the discord. :(((
would u please help give some basic idea to fix this issue, thx a lot.

//////////////////////////////////////////////////////
(base) D:\facefusion>python run.py
[FACEFUSION.PROCESSORS.FRAME.CORE] Frame processor face_swapper could not be loaded

//////////////////////////////////////////////////////
below is version info list =>>>>>

Facefusion Ver: latest zip file(downloaded@2024.4.25)
Python: 3.10.13
CUDA:  11.8.89
GPU: NIVIDIA p5000
.assets/models: 
2023/10/23  14:43       340,256,690 GFPGANv1.3.onnx
2023/10/23  14:51       348,632,874 GFPGANv1.3.pth
2023/10/23  14:29       340,256,690 GFPGANv1.4.onnx
2023/10/23  14:48       348,632,874 GFPGANv1.4.pth
2023/10/23  14:26       554,253,681 inswapper_128.onnx
2024/04/25  17:27       277,680,638 inswapper_128_fp16.onnx
2023/10/23  14:46        67,061,725 RealESRGAN_x2plus.pth
2023/10/23  14:49        67,040,989 RealESRGAN_x4plus.pth

**Comment by henryruhs** [comment]
Don't open such issues here... thanks
