### ISSUE TITLE
There appear to be 1 leaked semaphore objects to clean up at shutdown

### ISSUE THREAD

**Issue by MonkeyInWind** [facefusion/facefusion#52]
miniconda3/envs/py310/lib/python3.10/multiprocessing/resource_tracker.py:224: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown

warnings.warn('resource_tracker: There appear to be %d '

**Comment by henryruhs** [comment]
> Be aware, the installation needs technical skills and is not for beginners. Please do not open platform and installation related issues on GitHub. We have a very helpful [Discord](https://join.facefusion.io/) community that will guide you to install FaceFusion.
