### ISSUE TITLE
K-Lite CODEC pack

### ISSUE THREAD

**Issue by Looodon** [facefusion/facefusion#521]
Hey! 
I wanted to download Facefusion, but saw that the K-Lite CODEC pack is a requirement. I know that the K-Lite CODEC pack is for playing audio and video files, but I keep hearing people have problems with it where it causes different issues, where crashing is one of the many. I'm very sketched out from downloading it, do I need it? Is there a way to avoid it?
Thanks!

**Comment by henryruhs** [comment]
That codec pack is optional... if this brings a headache on your side, just skip it.
