### ISSUE TITLE
error for running the app

### ISSUE THREAD

**Issue by isacad1920** [facefusion/facefusion#522]
raise DeprecationWarning(
DeprecationWarning: concurrency_count has been deprecated. Set the concurrency_limit directly on event listeners e.g. btn.click(fn, ..., concurrency_limit=10) or gr.Interface(concurrency_limit=10). If necessary, the total number of workers can be configured via `max_threads` in launch().

**Comment by henryruhs** [comment]
I think you are using Gradio 4 which is not supported by FF.

```
pip list
```

Don't use global packages. For more support join Discord.
