### ISSUE TITLE
Wav2lip doesn't work, and I use a Mac, there is no instruction on installing codec

### ISSUE THREAD

**Issue by SauChi666** [facefusion/facefusion#532]
What Codec do I need? can you provide a link? Which directory do I put it under?

**Comment by henryruhs** [comment]
It's not upon us to fix your operating system.

**Comment by SauChi666** [comment]
[Linux](https://docs.facefusion.io/installation/platform/linux)
Codec

apt-get install mesa-va-drivers

[Windows](https://docs.facefusion.io/installation/platform/windows)
Codec

winget install -e --id CodecGuide.K-LiteCodecPack.Basic


Above is on your documentation... if MacOS is not supported then say it is not supported, what do you mean by fixing my operating system?  It is working ok...  Pls do add a line in on your home page saying Mac is not supported for this feature to advoid other mac user for install it and find out it doesn't work

**Comment by henryruhs** [comment]
Please do not open platform and installation related issues on GitHub.

That is from our README and still you opened as such an issue. We support MacOS, reading the documentation helps.
