### ISSUE TITLE
[feat.] Using Live Streaming as Input

### ISSUE THREAD

**Issue by MeowShe** [facefusion/facefusion#535]
As we know FaceFusion can `result-> udp`.

Is there any possible way to make a streaming (like WebRTC, SRT, RTMP) as input?

If `cv2` is used to process the input, is it possible to just modify the call of that for the purpose?

**Comment by henryruhs** [comment]
This is actually on our roadmap but has low priority. If you want to contribute code, reach out via Discord and I give guidance.
