### ISSUE TITLE
Future plans for additional lip sync models to implement?

### ISSUE THREAD

**Issue by cemgemelo** [facefusion/facefusion#537]
Hi. Great work!

My question was to ask if there is any plan to integrate further models for lip sync to the code base? 

A few example of other lip sync models:
- HyperLips
- GaussianTalker (gaussian splatting-based solutions)
- Some nerf-based solutions

**Comment by henryruhs** [comment]
Your contribution in form of a donation or code is welcome. Thanks

**Comment by mvoodarla** [comment]
Hi! I work at [Sieve](https://www.sievedata.com/) and we built an app that acts as a suite of lipsyncing models that you can pick and choose from. It's a hosted solution vs one that runs locally but would love feedback on it in-case it's interesting. Currently it supports MuseTalk and VideoReTalking which we found to be the best solutions for zero-shot lipsync at the moment.

https://www.sievedata.com/functions/sieve/lipsync
