### ISSUE TITLE
OUTPUT VIDEO QUALITY value range is wrong!

### ISSUE THREAD

**Issue by felixsanz** [facefusion/facefusion#54]
This value goes from 0 to 100. It's missleading because it makes you think that it goes from 0% quality to 100%, and some people will be happy with a quality of 85% because reduced filesize over 100%, but 85% is still a very high number because this is not how it works. This value is then mapped to ffmpeg's `crf` parameter, and it goes from 0-51. But it's **NOT** linear, and this is where the problem lives. A `crf` of 25 is not 50% perceived quality.

The formula that map the values is this:

```python
output_video_quality = round(51 - (facefusion.globals.output_video_quality * 0.5))
```

So this mapping produces:

output_video_quality 0 -------> crf: 51... ok?
output_video_quality 100  ---> crf: 1.... ok too? (can't be loseless?)

But other values are missleading!

If someone uses output_video_quality=85 thinking it will be a good tradeoff between quality and size.. that's insanely false! Because the crf value will be 8.5 and that is a waste! That's not even near to 85% quality, it's near perfect quality with huge disk space waste xD

 **ffmpeg's default crf value is 23!** And this number is probably what 85% quality should be.

Why create another scale from 0 to 100? Why not have the slider with the range of 0-51 and explain that this is ffmpeg's crf?

**Comment by henryruhs** [comment]
Not sure why you have to write your issue in such an angry tone, but in FaceFusion a value of 100 means indeed full quality. I flipped the range in comparison to Roop.

Whatever is wrong with the numbers in between can be solved by an hopefully less angry pull request.

**Comment by felixsanz** [comment]
> Not sure why you have to write your issue in such an angry tone, but in FaceFusion a value of 100 means indeed full quality. I flipped the range in comparison to Roop.
> 
> Whatever is wrong with the numbers in between can be solved by an hopefully less angry pull request.

Haha sorry, wasn't angry! I was somewhat surprised/confused. Do you accept a PR with a range from 0 to 51? Maybe we could have an icon/word next to it with a link pointing to https://trac.ffmpeg.org/wiki/Encode/H.264#a1.ChooseaCRFvalue

**Comment by henryruhs** [comment]
you can send a PR introducing

1. introduce `translate_quality_to_scale(quality : int, range : List[int]) -> int`
2. implement to create_video using 0 - 51
3. implement to extract_frames using 1 - 31
4. add testing to tests/test_utilities.py

Usage:

```
temp_frame_scale = translate_quality_to_scale(90, range(1, 32)))
```

I assume the non-linear factor is always 6 - if not it has to be another parameter.

**Comment by vizsumit** [comment]
output_video_quality = round(51 - math.log(facefusion.globals.output_video_quality, 100) * 51)

Linear Scale | Logarithm | CRF Scale
-- | -- | --
1 | 0 | 51
10 | 0.5 | 26
50 | 0.85 | 14
90| 0.95 | 5
100 | 1 | 0

ChatGPT

**Comment by henryruhs** [comment]
@vizsumit It is non-linear so what is the point of your post?

**Comment by felixsanz** [comment]
GPT:

> Unfortunately, there's no direct and simple formula to convert a quality value in percentage (from 1 to 100) to a CRF value in FFmpeg. The relationship between CRF value and visual quality is highly dependent on the video content and how the encoding is performed.

> The CRF value doesn't follow a linear or directly proportional scale in relation to visual quality. Therefore, any formula attempting to convert a quality value in percentage to a CRF value might not be accurate and could vary significantly based on the type of video content.

> The best approach to choosing a CRF value is to perform practical tests with different values and assess the resulting visual quality based on your own preferences and needs. This will allow you to fine-tune the CRF value according to your specific goals and the content of the video you're processing.

So.... can we just have the range slider showing real values from 0 to 51? Representing CRF not quality from 1% to 100%? (since it makes no sense to map that to crf!)

**Comment by henryruhs** [comment]
There is a reason I normalized it as the average user does not understand the concept of CRF. I don't plan to undo that.

> The range is exponential, so increasing the CRF value +6 results in roughly half the bitrate / file size, while -6 leads to roughly twice the bitrate. 

It can be done for sure.

**Comment by felixsanz** [comment]
That's why I proposed having [this link](https://trac.ffmpeg.org/wiki/Encode/H.264#a1.ChooseaCRFvalue) near the slider, because it explains it very good and very friendly.

Having 1-100 and mapping it to CRF will always be wrong :( It's not a challange, it's just not possible because crf depends on the input.

Closing as the direction here is to be most user-friendly possible and not having it accurate

**Comment by nivel99** [comment]
> No estoy seguro de por qué tienes que escribir tu problema en un tono tan enojado, pero en FaceFusion un valor de 100 significa calidad total. Cambié el rango en comparación con Roop.
> 
> Cualquier problema con los números intermedios se puede resolver mediante una solicitud de extracción, con suerte, menos enojada. Supongo que las escalas de calidad nunca son lineales.

si hablas caca
