### ISSUE TITLE
is there some bug in calculate total face frames?

### ISSUE THREAD

**Issue by BigFishDreamWater** [facefusion/facefusion#541]
i dealed a  27 seconds video  with 30 frame per second and size 720x1080 ,so video total frame shoule be   27X30=810，and video have some times almost blank which means no face in video,and i sure this video just  one face all the time ,so video total  face frame should less than 810。
and this picture show code proess video frame is 608,it's reasonable.
![image](https://github.com/facefusion/facefusion/assets/61278937/b54cf419-34a1-4ccd-97d1-93d2770cbd3c).
but on the end info ,it shows total_frames_with_faces  1037,which is more than video total frame,it's confused for me .
![image](https://github.com/facefusion/facefusion/assets/61278937/26322b36-ecbe-4760-8ac2-c10b45acac0c)

the most important thing is  too much face frame  makes the whole swap program slower than expect。
so how's the  face frame calculate?  
and if i want to reduce face frame in swap face,how can i do it ?
 
wish have your response soon,bro。

**Comment by henryruhs** [comment]
The statistics are using the face store - on multiple runs this causes indeed issues. Nothing more to say on that one, it is a bug.

**Comment by BigFishDreamWater** [comment]
so it's just statistics bug,and the swap process actually deal the right num face frames ,which in my case means 608 not the 1037,is it? and is there any suggestions to fast the swap time? i have used cuda and used multi threads in program.

**Comment by BigFishDreamWater** [comment]
> The statistics are using the face store - on multiple runs this causes indeed issues. It is a known bug.


so it's just statistics bug,and the swap process actually deal the right num face frames ,which in my case means 608 not the 1037,is it? and is there any suggestions to fast the swap time? i have used cuda and used multi threads in program.

**Comment by henryruhs** [comment]
total frames with faces... can you read?

this are not the total frames of the video

**Comment by henryruhs** [comment]
I lock this issue, GitHub is not for chatting. Use Discord for that.
