### ISSUE TITLE
New version not working

### ISSUE THREAD

**Issue by DiggyDre** [facefusion/facefusion#547]
There are so many things that are popping up yellow and saying that ... is not installed on PATH. There are so many AI setups in my system that have been working flawlessly and I know that things are on PATH. The previous versions of this program worked great but I never could get my 4080 to work with it, so I always had to work with it with my GPU. I see in the notes that there is a one click windows installer now but where? I don't see it. Maybe a one click installer would help get this thing working.

**Comment by henryruhs** [comment]
From our README

> Be aware, the [installation](https://docs.facefusion.io/installation) needs technical skills and is not recommended for beginners. In case you are not comfortable using a terminal, our [Windows Installer](https://buymeacoffee.com/henryruhs/e/251939) can have you up and running in minutes.

> There are so many AI setups in my system that have been working flawlessly and I know that things are on PATH

Don't blame others for not reading the [documentation](https://docs.facefusion.io/).
