### ISSUE TITLE
libpng error: Write Error

### ISSUE THREAD

**Issue by jiaxiaoren** [facefusion/facefusion#548]
When I perform a video face swap, once the video file size of mine is large, an error will appear during the FRAME_ENHANCE process: libpng error: Write Error

**Comment by jiaxiaoren** [comment]
![image](https://github.com/facefusion/facefusion/assets/96038503/580d50a6-f86e-44c6-90f6-4211ec31af8e)
then, the final fake video is just have 3-5 second.

**Comment by henryruhs** [comment]
Google is your friend, I found the issue within 20 seconds.
