### ISSUE TITLE
Videos are copied twice to RAM

### ISSUE THREAD

**Issue by felixsanz** [facefusion/facefusion#55]
When a new video is uploaded to the UI, it appears 2 times (with different folder names) inside `/tmp/gradio`, which is mounted to the RAM in my system, so the RAM usage is doubled. Any idea why this happen? I can't find where the problem is

**Comment by henryruhs** [comment]
Could you help me understanding the issue by providing some screenshots? I doubt it is loaded 2 times.

**Comment by felixsanz** [comment]
Sure. I deleted `/tmp/gradio` to make sure nothing exists.

![1693412793](https://github.com/facefusion/facefusion/assets/6182099/c80d3c53-71f8-4984-9823-11b0db71c037)

Then I drag and drop the video into the target zone.

![1693412744](https://github.com/facefusion/facefusion/assets/6182099/e448f9bb-64a6-4fa7-a51c-c7325efee432)

And if you check `/tmp/gradio` now...

![1693412797](https://github.com/facefusion/facefusion/assets/6182099/74919896-7d20-4907-a7d2-5b816fd7ce6d)

2 folders with different hash but the same video. Since this is mounted to RAM it's always consuming double RAM than needed.

I know I can move the temp folder to a disk but in RAM is fast and nice, it's just that it shouldn't be here duplicated.

**Comment by henryruhs** [comment]
This is indeed an issue cause by the my integration.

To have just one drop area for images and videos I use `gradio.File` instead of `gradio.Image` and `gradio.Video` next to each other. I didn't expect they load that file twice to the RAM.

**Comment by felixsanz** [comment]
It happens with every asset. The face image you upload to the "source" zone, it happens too

**Comment by henryruhs** [comment]
The `source.py` is made the same way like the `target.py` - not because it is needed but to have the same UI concept.

**Comment by henryruhs** [comment]
![grafik](https://github.com/facefusion/facefusion/assets/1835397/1b3b89c7-7573-45af-add8-f31afa605a4f)

Could be solved either with a Tab or be unloaded the File components.

**Comment by felixsanz** [comment]
Unloading the old "file" instance and keeping the "video" or "image" one seems to be a better solution to me, so the UI doesn't get more complex without needing

**Comment by henryruhs** [comment]
I agree... but that needs lot of refactoring

**Comment by felixsanz** [comment]
> I agree... but that needs lot of refactoring

why? just when the file is uploaded... there is already 2 times, remove the old one with os.remove()

**Comment by henryruhs** [comment]
Like I know the Gradio hash... anyway, I gonna fix that asap.

**Comment by C0untFloyd** [comment]
Perhaps it would make sense to create an issue @ Gradio. Lots of apps just run locally and don't need the temp mechanism (or uploading files), so it would be great to have a flag telling the components to just use the local paths without copying. This could even even be set with the "share" flag in launch parameters.

**Comment by henryruhs** [comment]
The good news: source_file and target_file are no longer used across the application. I use source_image, target_image and target_video now.

The bad news: unloading the file components does not result in the wanted behavior.

This might stay unfixed for 1.1.0 in case nobody sends a pull request until tomorrow.

**Comment by henryruhs** [comment]
I resolved this as wontfix... closed on the Gradio side - the decision is made that we move away from this framework.
