### ISSUE TITLE
Merging video failed

### ISSUE THREAD

**Issue by topskymonk** [facefusion/facefusion#559]
When I attempt to perform a video face swap, the console displays the following exception.
![微信图片_20240529084117](https://github.com/facefusion/facefusion/assets/38942502/bae1dd25-f962-4f92-9257-b5234190ba9d)

**Comment by henryruhs** [comment]
Please join our [Discord for](https://join.facefusion.io) help, we cannot debug errors via GitHub - this is a software tracker and not support system.
