### ISSUE TITLE
PR - Filepath problem with utf-8 paths are fixed.

### ISSUE THREAD

**Issue by FlowDownTheRiver** [facefusion/facefusion#566]
I tried to make a pr but failed.
Please check if this is compatible with your code base.

In cli -headless mode it was not allowing special chars in the path.with this it works.

[filesystem.zip](https://github.com/user-attachments/files/15541702/filesystem.zip)

chars to test if needed: ö ç ı ğ ü ş

**Comment by henryruhs** [comment]
Sorry, but I won't accept a ZIP file. Additional, this needs a unit test to prove there was an issue before, it should fail without your fix.

**Comment by FlowDownTheRiver** [comment]
[vision_filesystem.zip](https://github.com/user-attachments/files/15594059/vision_filesystem.zip)

The file I shared before still had problems.
I know you will not accept this and I am not a proper developer however I asked chatgpt about the problem for me to edit the code. I will share the full chatlog for you to determine and why it is giving hard time and you can properly understand and fix it in your own way if you like. I am not asking for you to merge these but just check it.

I have tested this in windows 10, it allowed me to use paths that was not allowed with opencv and how it handles the paths.

this is the chatlog with chatgpt :

https://chatgpt.com/share/3fb217f0-086b-494e-8e62-42e86d23ad86

@henryruhs

**Comment by henryruhs** [comment]
It had been fixed already in latest version - if it does not work, then it is your Windows which does not allow `GetShortPathNameW`.

Code: https://github.com/facefusion/facefusion/blob/master/facefusion/filesystem.py#L124-L135
Test: https://github.com/facefusion/facefusion/blob/master/tests/test_filesystem.py#L87-L90
