### ISSUE TITLE
colab error ssh: connect to host remote.moe port 22: Connection refused

### ISSUE THREAD

**Issue by putuoka** [facefusion/facefusion#57]
![image](https://github.com/facefusion/facefusion/assets/20880839/913a7bf8-40ad-46f9-94a7-29fcf1efda80)

**Comment by henryruhs** [comment]
This is something the author of the colab has to resolve. You are better of joining our Discord and talk with him, I forwarded the requests.

![grafik](https://github.com/facefusion/facefusion/assets/1835397/2255767b-6dc1-4696-b295-cfdce42b7f23)

**Comment by makusu720** [comment]
@putuoka I can't reproduce the error, is it still occurring for you?
