### ISSUE TITLE
Please support Intel hardware encoders

### ISSUE THREAD

**Issue by DDXDB** [facefusion/facefusion#571]
Since OpenVino is already supported to run on Intel Gpus, why not take it a step further?
Please support QSV to enable hardware coding on Intel Gpus!

**Comment by henryruhs** [comment]
Are you talking about ffmpeg using QSV? It does not come with that compiled, so no support from our side.

**Comment by DDXDB** [comment]
> Are you talking about ffmpeg using QSV? It does not come with that compiled, so no support from our side.

It looks like ffmpeg supports qsv.
![屏幕截图 2024-06-16 032027](https://github.com/facefusion/facefusion/assets/38449595/18cbb8df-b4fb-4b3a-b760-dc1d29b11bce)

**Comment by henryruhs** [comment]
Well, send a PR then.
