### ISSUE TITLE
Is CUDA toolkit 12.5 supported now?

### ISSUE THREAD

**Issue by chris890207** [facefusion/facefusion#574]
our [Windows Installer](https://buymeacoffee.com/henryruhs/e/251939) can have you up and running in minutes.

Does this link support CUDA toolkit 12.5?

**Comment by chris890207** [comment]
I see that the download option only supports 12.2

**Comment by henryruhs** [comment]
It works on CUDA 11.8 ... why is everyone crazy about using latest the version? It does not improve speed or anything.
