### ISSUE TITLE
Quick method for implementing queues

### ISSUE THREAD

**Issue by v8oholic** [facefusion/facefusion#576]
I think you said you have plans for some sort of batch or queue mechanism.

A quick and dirty way of doing it within the GUI might be to just find a way to output a headless command which is the contextual equivalent of what would happen if the user pressed the Start button. Just outputting it to the console the run.py is executing in would suffice. So instead of pressing Start, the user can simply copy that text manually into a shell script. They can repeat the exercise as often as they like, building up the shell script, then eventually quit the GUI and let the shell script rip.

Although this is hardly as sophisticated as say the Handbrake queue, it doesn't require many changes to the GUI either, because there would be no queue management or anything like that. That would be down to the user.

**Comment by henryruhs** [comment]
Thanks for suggesting this quick win but we already have the "jobs" feature done in our next branch.

It's CLI only for now, we are brainstorming about the UI right now. My PM are open, feel free to reach out on Discord.
