### ISSUE TITLE
About installing on the server and accessing the web page on another computer

### ISSUE THREAD

**Issue by BAK-HOME** [facefusion/facefusion#578]
About installing on the server and accessing the web page on another computer。
Because the default access IP is 127.0.0.1: 7860, I want to change it to another IP, for example: 192.168.1.2: 7860, then how to change it

**Comment by BAK-HOME** [comment]
I am deployed in ubuntu22.04 server, convenient with the local area network, then ask, to fix the IP address 127.0.0.1

**Comment by henryruhs** [comment]
```
GRADIO_SERVER_NAME=0.0.0.0
GRADIO_SERVER_PORT=8080
```
