### ISSUE TITLE
Not seeing GPU

### ISSUE THREAD

**Issue by WindowsNT** [facefusion/facefusion#580]
I'm doing the installation as follows:

1. Install midiconda manually
2. conda install cudatoolkit=11.8 cudnn=8.9.2.26 conda-forge::gputil=1.4.0
3. conda install conda-forge::zlib-wapi
4. conda install conda-forge::openvino=2023.1.0
5. git clone https://github.com/facefusion/facefusion
6. pip install -r facefusion/requirements.txt
7. pip install inquirer

when run.py is run, I only get "cpu" and "Azure" providers, no GPU.
What I am missing?

I'm trying to automate this for my users so the installation is transparent to them without the need to manually activate conda environment etc.

**Comment by henryruhs** [comment]
I have no interest to assist on that topic as we provide a Windows Installer ourselves.

**Comment by WindowsNT** [comment]
Well, I 'm a developer; I'm not interested for installers created for dummies. But I will eventually find out the way.
Thanks for the library.
