### ISSUE TITLE
Error when python install.py

### ISSUE THREAD

**Issue by xZiyech** [facefusion/facefusion#586]
Hi, im trying to use facefusion but when i do : python install.py , this message appears : gradio 3.50.2 requires numpy~=1.0, but you have numpy 2.0.0 which is incompatible.
Someone to help me please ? Thank you

MacOS, M1

**Comment by henryruhs** [comment]
Please join [Discord](https://join.facefusion.io) for help.

**Comment by chefjpg** [comment]
@xZiyech if you 'pip uninstall numpy' and then 'pip install numpy==1.26.4' it should fix the error. Numpy 2.0 was literally released today so that's what is causing the errors.
