### ISSUE TITLE
when I try to do the lip syncer,  return cv2.imwrite(image_path, vision_frame) error!!help!!!!

### ISSUE THREAD

**Issue by MatataZ** [facefusion/facefusion#588]
![Screenshot 2024-06-17 131337](https://github.com/facefusion/facefusion/assets/172449596/d75fd4fb-099f-40ca-bc38-ccfe4de6c0fd)
what should I do to make it right? help!!!!!

**Comment by henryruhs** [comment]
Please join [Discord](https://join.facefusion.io) for help.
