### ISSUE TITLE
Worked once, then never again, no errors shown.

### ISSUE THREAD

**Issue by JeltzProstetnic** [facefusion/facefusion#590]
I got it to run once using docker. Then something broke, I have no idea what. Now nothing can make it run again. I tried on Windows and Ubuntu, direct, with docker, and even with this js stuff, no luck. I tried many things, but it's hard to know where to start when there is no error message.

The GUI loads, just no more faceswapping. Help?

**Comment by henryruhs** [comment]
#
Please join [Discord](https://join.facefusion.io) for help.
