### ISSUE TITLE
how can I use multiple GPUs to compute the same task?

### ISSUE THREAD

**Issue by AndyPfp666** [facefusion/facefusion#591]
Hello, how can I use multiple GPUs to compute the same task? My machine has 6 GPUs, and I want to use them all to improve efficiency.

**Comment by henryruhs** [comment]
Hey,

I tried once to create a inference pool... so one thread + one GPU + one model get a instance. It did not turn out to be faster and I finally gave up and we now wait for official onnxruntime support.

Sorry that I don't have better news on that, I own just on GPU so no change for me for proper development and testing.
