### ISSUE TITLE
ModuleNotFoundError: No module named 'numpy._expired_attrs_2_0？why？

### ISSUE THREAD

**Issue by caoshuxian** [facefusion/facefusion#597]
ModuleNotFoundError: No module named 'numpy._expired_attrs_2_0
![屏幕截图 2024-06-24 171012](https://github.com/facefusion/facefusion/assets/163301559/175df412-eaca-4ac5-b6ec-12ce4a21d3c4)

**Comment by caoshuxian** [comment]
python run.py

**Comment by henryruhs** [comment]
Use FF 2.6.1
