### ISSUE TITLE
cuda provider not available under ubuntu when cuda 12

### ISSUE THREAD

**Issue by lycoch** [facefusion/facefusion#598]
hello

cat /etc/debian_version 
bookworm/sid

NVIDIA-SMI 555.42.02              Driver Version: 555.42.02      CUDA Version: 12.5

run.py: error: argument --execution-providers: invalid choice: 'cuda' (choose from 'azure', 'cpu')

is it because of cuda 12 ?
using a cloud VM with already installed driver, so no choice of cuda version
any workaround ?
thanks

**Comment by henryruhs** [comment]
Please join [Discord](https://join.facefusion.io) for help.
