### ISSUE TITLE
trim sliders not showing for big files

### ISSUE THREAD

**Issue by kuoj0926** [facefusion/facefusion#60]
sometimes the trim sliders (and also the preview window) would not show. May have something to do with the file sizes.

Example - same video but one is 720p and one is 1080p:
![trim_slider](https://github.com/facefusion/facefusion/assets/75271265/6997687b-9abd-4f9b-9e0e-81ee1ddb146d)
![no_trim_slider](https://github.com/facefusion/facefusion/assets/75271265/1084c00e-b5e9-4132-bee6-674f40ae4af5)

**Comment by henryruhs** [comment]
Are you on develop branch with latest code?

**Comment by kuoj0926** [comment]
i'm on master branch, lemme try with dev.

**Comment by kuoj0926** [comment]
just tried it and looks like the ~90mb one got fixed, but when I used something bigger ~200mb it has the same issue. 
![with_trim](https://github.com/facefusion/facefusion/assets/75271265/c054fab2-114d-4652-bff5-3a1cae19b749)
![no_trim](https://github.com/facefusion/facefusion/assets/75271265/303036f8-4537-4a5a-86c0-3d315fefcfb8)

**Comment by henryruhs** [comment]
I think that is related how long the "upload" event takes and our timeout hacks just don't work on different platforms as this upload takes different times. That being said, I refactored the codebase to be fully event driven.

Please give the branch `fully-event-driven-ui` and try an report bugs - it contains lot of changes and I was a bit in a hurry.

Who ever is a developer, please review the PR: https://github.com/facefusion/facefusion/pull/62

**Comment by henryruhs** [comment]
Merged... thanks for the report - I needed the motivation to finally resolve it :D
