### ISSUE TITLE
Facial reenactment feature.

### ISSUE THREAD

**Issue by jeffreyhaoau** [facefusion/facefusion#600]
This is just one idea, which is possible to implement in this great repo.
Firstly, the 1st input should support video format, and the 2nd input is also a video.
Then, the face and expression in the 1st video can be transferred to the face in the 2nd video.

This idea is to make the face in the generated video controllable.
Regards.

**Comment by jeffreyhaoau** [comment]
"Thin plate spline motion model" is one candidate for Facial reenactment, which could be run by CPU.

**Comment by henryruhs** [comment]
Thanks for the suggestion. We have this already on our roadmap.

> Introduce face animator for static images
