### ISSUE TITLE
typo in doc

### ISSUE THREAD

**Issue by magical-l** [facefusion/facefusion#602]
at the page `https://docs.facefusion.io/workshop/ui-layout#id-2.-implement`

`from facefusion.uis.components import example`

I think the 'example' would be 'execution'

**Comment by henryruhs** [comment]
nope, it is an example implementation.

**Comment by magical-l** [comment]
but there's no `example.py` in `facefusion.uis.components`, so compile failed. and when I change it to `execution`, the example worked (compile pass and run ok)!
