### ISSUE TITLE
concurrency_count deprecated inside facefusion\uis\layouts\default.py

### ISSUE THREAD

**Issue by catalingdiaconu** [facefusion/facefusion#603]
Hello!

First time trying to run "python run.py", I get:

```
Traceback (most recent call last):
  File "facefusion\run.py", line 6, in <module>
    core.cli()
  File "facefusion\facefusion\core.py", line 112, in cli
    run(program)
  File "facefusion\facefusion\core.py", line 234, in run
    ui.launch()
  File facefusion\facefusion\uis\core.py", line 93, in launch
    ui_layout_module.run(ui)
  File "facefusion\facefusion\uis\layouts\default.py", line 81, in run
    ui.queue(concurrency_count = concurrency_count).launch(show_api = False, quiet = True, inbrowser = facefusion.globals.open_browser)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "miniconda2\Lib\site-packages\gradio\blocks.py", line 2121, in queue
    raise DeprecationWarning(
DeprecationWarning: concurrency_count has been deprecated. Set the concurrency_limit directly on event listeners e.g. btn.click(fn, ..., concurrency_limit=10) or gr.Interface(concurrency_limit=10). If necessary, the total number of workers can be configured via `max_threads` in launch().
```

inside facefusion\uis\layouts\default.py.

I tried to remove it, but with no success

Current code:
`
def run(ui : gradio.Blocks) -> None:
	concurrency_count = min(8, multiprocessing.cpu_count())
	ui.queue(concurrency_count = concurrency_count).launch(show_api = False, quiet = True, inbrowser = facefusion.globals.open_browser)
`
	
My change:
`def run(ui: gradio.Blocks) -> None:
    concurrency_count = min(8, multiprocessing.cpu_count())
    ui.launch(show_api=False, quiet=True, inbrowser=facefusion.globals.open_browser, max_threads=concurrency_count)
`

Any help would be highly appreciated! 
Thanks!

**Comment by henryruhs** [comment]
Do not use Gradio 4 with FaceFusion 2.6.1
