### ISSUE TITLE
Numpy in FaceFussion

### ISSUE THREAD

**Issue by GoodbeBoss** [facefusion/facefusion#604]
Hello.

I installed FaceFussion from Pinokio.

Please, help me to fix this issue:

C:\Users\Admin\pinokio\api\facefusion-pinokio.git\facefusion>conda_hook && conda deactivate && conda deactivate && conda deactivate && conda

activate facefusion && python run.py

Traceback (most recent call last):

File "C:\Users\Admin\pinokio\api\facefusion-pinokio.git\facefusion\run.py", line 3, in <module>

from facefusion import core

File "C:\Users\Admin\pinokio\api\facefusion-pinokio.git\facefusion\facefusion\core.py", line 9, in <module>

import numpy

ModuleNotFoundError: No module named 'numpy'

(facefusion) C:\Users\Admin\pinokio\api\facefusion-pinokio.git\facefusion>
[Start proxy] Share local {{ input.stdout.match(/(http:\S+)/gi)[0] }}

I check my proxy on Google Chrome, but facefussion doesn't work, just white screen.

---

I added numpy on Windows 10 (pip install numpy). 

I see my version numpy in cmd.exe.

**Comment by henryruhs** [comment]
Please join [Discord](https://join.facefusion.io) for help.
