### ISSUE TITLE
How to access from another computer?

### ISSUE THREAD

**Issue by terry16** [facefusion/facefusion#614]
Hello,
I want to access the model from another computer. How can I do that?
I noticed that the IP is 127.0.0.1. I think changing it to 0.0.0.0 might work, but I'm not sure how to change it. Can anyone give me some advice?
Thanks.

**Comment by henryruhs** [comment]
Please join [Discord](https://join.facefusion.io) for help.

**Comment by anonymousz97** [comment]
i find the quick fix for this

You can change the file facefusion/uis/layouts/default.py line 79

`def run(ui : gradio.Blocks) -> None:
	concurrency_count = min(8, multiprocessing.cpu_count())
	ui.queue(concurrency_count = concurrency_count).launch(show_api = False, quiet = True, inbrowser = facefusion.globals.open_browser)`

into 

`def run(ui: gradio.Blocks) -> None:
    concurrency_count = min(8, multiprocessing.cpu_count())
    ui.queue(concurrency_count=concurrency_count).launch(
        show_api=False,
        quiet=True,
        inbrowser=facefusion.globals.open_browser,
        server_name='0.0.0.0'
    )
`

Just add server_name='0.0.0.0' and it helps.
