### ISSUE TITLE
Lip Synch not working for me

### ISSUE THREAD

**Issue by Pendragon51** [facefusion/facefusion#615]
Just that simple lip synch will not work, I add the audio, then image and it runs for a moment then generates the picture and that is it, am I missing something, I do have ffmpeg etc, i'm using 261?

**Comment by henryruhs** [comment]
GitHub != Support Ticket System

**Comment by Pendragon51** [comment]
NVM I just realized, unless I'm wrong lip synch only works on videos not still images

**Comment by henryruhs** [comment]
exactly, but it's on the roadmap: https://docs.facefusion.io/introduction/roadmap#id-3.1.0
