### ISSUE TITLE
eyes

### ISSUE THREAD

**Issue by Shoichii** [facefusion/facefusion#618]
how can you see: source is looking to the camera and target is looking to the camera, but result....
how i can fix it?

![result](https://github.com/facefusion/facefusion/assets/62342750/23c5ec54-ab2c-4f03-9a6e-fcb182d63e9e)
![source](https://github.com/facefusion/facefusion/assets/62342750/d469efb3-c65b-4d4e-b85d-b86ba4eb1f9d)
![target](https://github.com/facefusion/facefusion/assets/62342750/e7488a11-c2ed-4aa8-b4a7-f96c060ff11d)

**Comment by henryruhs** [comment]
You cannot... GitHub is not for chatting, use our [Discord](https//join.facefusion.io) instead.
