### ISSUE TITLE
What is the source of the OCCLUSION model?

### ISSUE THREAD

**Issue by GeneralShan** [facefusion/facefusion#620]
I see you have [face_occluder.onnx](https://github.com/facefusion/facefusion-assets/releases/download/models/face_occluder.onnx) , but you do not say where does it come from?

Where is this model from ? What is the original ?
THank you.

**Comment by henryruhs** [comment]
Please join [Discord](https://join.facefusion.io) for questions. This is a issue tracker, not a chat.
