### ISSUE TITLE
feature request: Select frame start; select frame end

### ISSUE THREAD

**Issue by samfisherirl** [facefusion/facefusion#621]
![image](https://github.com/facefusion/facefusion/assets/98753696/1f5e1162-5bfb-4258-9096-b9854a20d8d6)

simple illistration, port the preview frame to start:end

**Comment by henryruhs** [comment]
I have no idea what you mean...

**Comment by samfisherirl** [comment]
> I have no idea what you mean...

A button corresponding with both the "select trim frame start" and "select trim frame end" 

If you press the "trim frame start" button, it takes the frame number from the preview frame, and ports it to the trim frame start field.

**Comment by henryruhs** [comment]
Thanks for the suggestion but I don't plan on adding this.
