### ISSUE TITLE
Download time too long

### ISSUE THREAD

**Issue by tnxl** [facefusion/facefusion#622]
When I use commands “python run.py --execution-providers dml”
Is there a way to import the model offline if the download speed is slow or very slow? However, I cannot find which model it downloaded, the location where the model is stored, or can I change the download source?
![image](https://github.com/facefusion/facefusion/assets/31915062/ab938601-ed09-49d3-a887-8e8137508978)

**Comment by baka-9** [comment]
Use VPN or download models from [facefusion-assets](https://github.com/facefusion/facefusion-assets)

by the way
Please join [Discord](https://join.facefusion.io/) for questions. This is a issue tracker, not a chat.

**Comment by henryruhs** [comment]
See https://docs.facefusion.io/usage/cli-arguments/misc#force-download

**Comment by Jeru2023** [comment]
> facefusion-assets
This is a empty repo, I have same issue, run.py downloading extreamly slow(with or without VPN), waited for over 24 hours
