### ISSUE TITLE
(-215:Assertion failed) !ssize.empty() in function 'resize'

### ISSUE THREAD

**Issue by wisco24** [facefusion/facefusion#629]
OS: Mac 14.5 (M2 Max)

When clicking start after uploading source and target, I get this:  

<img width="1219" alt="Screenshot 2024-07-10 at 6 01 29 PM" src="https://github.com/facefusion/facefusion/assets/21183744/f3bd3721-78fa-4c03-9b04-40249571d95a">

**Comment by henryruhs** [comment]
Looks like a corrupt frame in the video. Nothing too much we can do about...

**Comment by wisco24** [comment]
Ok. Thanks.  I'll test with some others.   It plays fine in other tools, so didn't suspect that.

**Comment by henryruhs** [comment]
Join us on Discord, we help you out.
