### ISSUE TITLE
Windows installer still on 2.6.0

### ISSUE THREAD

**Issue by Lustwaffel** [facefusion/facefusion#636]
The face fusion windows installer is purchased for 22$ on the end of may is still on Version 2.6.0 so I cannot resolve the issue I posted this morning deemed "closed"

**Comment by henryruhs** [comment]
Go to your recent purchase history and reclaim the latest version.

**Comment by Lustwaffel** [comment]
Right got it. Sorry for being a incompetent ass clown.

**Comment by henryruhs** [comment]
Nope, they hide this actually... you will have free updates for FF 3.0.0 too... enjoy

**Comment by Lustwaffel** [comment]
You are going to laugh but I have no luck with the newer version. This is the error:

#Collecting numpy==1.26.4
  Using cached numpy-1.26.4-cp310-cp310-win_amd64.whl.metadata (61 kB)
Using cached numpy-1.26.4-cp310-cp310-win_amd64.whl (15.8 MB)
Installing collected packages: numpy
  Attempting uninstall: numpy
    Found existing installation: numpy 2.0.0
    Uninstalling numpy-2.0.0:
      Successfully uninstalled numpy-2.0.0#

then it goes on to say 
#ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
numba 0.57.0 requires numpy<1.25,>=1.21, but you have numpy 1.26.4 which is incompatible.
Successfully installed numpy-1.26.4#

I have uninstalled, tried downgrading numpy manually to 1.24 which it tells me was done succesfully but before the install but the installer installs a version that it THEN says is incompatible. I don't know what to do. Really. This sucks.

**Comment by henryruhs** [comment]
Please join [Discord](https://join.facefusion.io) for help.
