### ISSUE TITLE
failed：[FACEFUSION.CORE] Extracting frames failed

### ISSUE THREAD

**Issue by calonye** [facefusion/facefusion#638]
![image](https://github.com/user-attachments/assets/793f1806-45e6-4fc6-adc6-dca8a9c9f2cf)

![image](https://github.com/user-attachments/assets/4ecdb069-8381-4d6a-8672-ae8e1b136be1)

**Comment by henryruhs** [comment]
Please join [Discord](https://join.facefusion.io) for help.
