### ISSUE TITLE
use cuda as the execution provider occurred some question

### ISSUE THREAD

**Issue by wb9436** [facefusion/facefusion#639]
facefusion\face_helper.py:82: RuntimeWarning: invalid value encountered in cast
paste_vision_frame[:, :, 0] = inverse_mask * inverse_vision_frame[:, :, 0] + (1 - inverse_mask) * temp_vision_frame[:, :, 0]

only some image as source image in swapper face  occurred this question，for example:
[https://test-short-video-1251002159.cos.ap-guangzhou.myqcloud.com/103573/103573-20240718-1721265163443.jpg](url)

**Comment by henryruhs** [comment]
I cannot access this file but my assumption is that it's either corrupted or your GPU does not support fp16.

Best way to handle this: join us on [Discord](https://join.facefusion.io) and open a help thread there.

**Comment by wb9436** [comment]
> I cannot access this file but my assumption is that it's either corrupted or your GPU does not support fp16.
> 
> Best way to handle this: join us on [Discord](https://join.facefusion.io) and open a help thread there.

thanks, it's right !
