### ISSUE TITLE
FPS detection not working properly

### ISSUE THREAD

**Issue by rogerb831** [facefusion/facefusion#64]
## Title
Incorrect FPS Detection with `--keep-frames` Flag When `ffprobe` Outputs Multiple Lines

## Description
When using the `--keep-frames` flag (also known as "Keep FPS" in the GUI), the `detect_fps` function in `utilities.py` fails to accurately determine the video frame rate. This happens if `ffprobe` returns multiple lines of FPS information. The function expects a single line and does not handle multiple lines, leading to a parsing error.

## Steps to Reproduce
1. Run the Docker container using `docker-compose -f docker-compose.cuda.yml up`.
2. Run the application with a video file and use the `--keep-frames` flag or "Keep FPS" in the GUI.
3. Observe the error message or incorrect FPS detection in the console.

## Expected Behavior
The `detect_fps` function should accurately detect the FPS of the video, even when the `--keep-frames` flag is used and `ffprobe` returns multiple lines of output.

## Actual Behavior
The function fails to parse multiple lines and throws a parsing error when converting the FPS information to integers.

## Debug Information
- Debug logs show that the raw `ffprobe` output contains multiple lines, which is not handled by the existing code.
- Error Message: `Error in calculating FPS: invalid literal for int() with base 10: '1001\n30000'`

## Suggested Fix
Modify the `detect_fps` function to only consider the first line of the `ffprobe` output for FPS calculation. Add a line to split the raw output by newline characters and use only the first element for further processing.

```python
# Consider only the first line of the output
def detect_fps(target_path : str) -> Optional[float]:
    logging.basicConfig(level=logging.DEBUG)
    
    commands = [ 'ffprobe', '-v', 'error', '-select_streams', 'v:0', '-show_entries', 'stream=r_frame_rate', '-of', 'default=noprint_wrappers = 1:nokey = 1', target_path ]
    raw_output = subprocess.check_output(commands).decode().strip()
        
    # Consider only the first line of the output (Use spaces for indentation here)
    first_line_output = raw_output.split('\n')[0]

    output = first_line_output.split('/')  # Modified this line to use first_line_output
    try:
        numerator, denominator = map(int, output)
        calculated_fps = numerator / denominator
        logging.debug(f"Calculated FPS: {calculated_fps}")
        return calculated_fps
    except Exception as e:
        logging.error(f"Error in calculating FPS: {e}")
        return None
```

## Environment
- Operating System: Docker container (based on the image specified in `docker-compose.cuda.yml`)
- Python Version: 3.10.12
- Application Version: 1.0

**Comment by henryruhs** [comment]
I assume you are talking about multi stream files? Can you provide the file for testing?

If that is the case I prefer to use `-select_streams V:0` instead

**Comment by henryruhs** [comment]
Hopefully solved via https://github.com/facefusion/facefusion/commit/e01b556f18a4a26abbd4089d7e9a16fc60ed48ed

Please respond next time, I did not had a file to test again.
