### ISSUE TITLE
Patch for remote target videos does not work

### ISSUE THREAD

**Issue by unixman0x6576676C313531303933** [facefusion/facefusion#650]
Hello, I bought and installed the extension/patch. This is the output of the terminal (running on windows 10)

Running on local URL:  http://127.0.0.1:7860
[youtube] Extracting URL: https://www.youtube.com/watch?v=5NPBIwQyPWE
[youtube] 5NPBIwQyPWE: Downloading webpage
[youtube] 5NPBIwQyPWE: Downloading ios player API JSON
[youtube] 5NPBIwQyPWE: Downloading android player API JSON
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying (1/3)...
[youtube] 5NPBIwQyPWE: Downloading android player API JSON
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying (2/3)...
[youtube] 5NPBIwQyPWE: Downloading android player API JSON
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying (3/3)...
[youtube] 5NPBIwQyPWE: Downloading android player API JSON
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] Unable to download API page: HTTP Error 400: Bad Request (caused by <HTTPError 400: Bad Request>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[youtube] 5NPBIwQyPWE: Downloading player 3400486c
WARNING: [youtube] 5NPBIwQyPWE: nsig extraction failed: You may experience throttling for some formats
         n = i2h3JThWdKW8ofxPaW ; player = https://www.youtube.com/s/player/3400486c/player_ias.vflset/en_US/base.js
WARNING: [youtube] 5NPBIwQyPWE: nsig extraction failed: You may experience throttling for some formats
         n = jgWYjmurEqE6Wvkr0- ; player = https://www.youtube.com/s/player/3400486c/player_ias.vflset/en_US/base.js
[youtube] 5NPBIwQyPWE: Downloading m3u8 information
[info] 5NPBIwQyPWE: Downloading 1 format(s): 18
ERROR: unable to download video data: HTTP Error 403: Forbidden
[youtube] Extracting URL: https://www.youtube.com/watch?v=5NPBIwQyPWE
[youtube] 5NPBIwQyPWE: Downloading webpage
[youtube] 5NPBIwQyPWE: Downloading ios player API JSON
[youtube] 5NPBIwQyPWE: Downloading android player API JSON
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying (1/3)...
[youtube] 5NPBIwQyPWE: Downloading android player API JSON
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying (2/3)...
[youtube] 5NPBIwQyPWE: Downloading android player API JSON
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying (3/3)...
[youtube] 5NPBIwQyPWE: Downloading android player API JSON
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] Unable to download API page: HTTP Error 400: Bad Request (caused by <HTTPError 400: Bad Request>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[youtube] 5NPBIwQyPWE: Downloading player 3400486c
WARNING: [youtube] 5NPBIwQyPWE: nsig extraction failed: You may experience throttling for some formats
         n = pgQeyNRZsrDWGv0afX ; player = https://www.youtube.com/s/player/3400486c/player_ias.vflset/en_US/base.js
WARNING: [youtube] 5NPBIwQyPWE: nsig extraction failed: You may experience throttling for some formats
         n = eyBQ8-Hu6o0GoYgqgW ; player = https://www.youtube.com/s/player/3400486c/player_ias.vflset/en_US/base.js
[youtube] 5NPBIwQyPWE: Downloading m3u8 information
[info] 5NPBIwQyPWE: Downloading 1 format(s): 18
ERROR: unable to download video data: HTTP Error 403: Forbidden
[TikTok] Extracting URL: https://www.tiktok.com/@dons_latvija/video/7368894577400499489?lang=en
[TikTok] 7368894577400499489: Downloading video feed
WARNING: [TikTok] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 1 of 4)
[TikTok] 7368894577400499489: Downloading video feed
WARNING: [TikTok] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 2 of 4)
[TikTok] 7368894577400499489: Downloading video feed
WARNING: [TikTok] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 3 of 4)
[TikTok] 7368894577400499489: Downloading video feed
WARNING: [TikTok] 7368894577400499489: Failed to parse JSON (caused by JSONDecodeError("Expecting value in '': line 1 column 1 (char 0)")); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U; trying with webpage
[TikTok] 7368894577400499489: Downloading webpage
ERROR: [TikTok] 7368894577400499489: Unable to extract sigi state; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

**Comment by henryruhs** [comment]
There is nothing I can do about it right now, I will update that patch after the next release.
