### ISSUE TITLE
Super low res when swapping faces

### ISSUE THREAD

**Issue by yogotatara3** [facefusion/facefusion#654]
Heyy, thanks for your contribution of face fusion!

For some reason, the created output is super low res, tried inswapper, fp16 and normal deblurrred more but still super crappy results. Do u know whats the problem?

Best,
Milan
![image (3)](https://github.com/user-attachments/assets/730ca808-9440-403e-b1f5-784ed3a6a48b)
![image (4)](https://github.com/user-attachments/assets/3b1b4b33-874e-472a-ae50-c30da3f26bf1)

**Comment by henryruhs** [comment]
That is the limit of inswapper (128x128 pixel).
