### ISSUE TITLE
The Mac computer is unable to use the CoreML engine to accelerate facial enhancement？

### ISSUE THREAD

**Issue by abeliu1029** [facefusion/facefusion#657]
Analysing: 100%|==========================================| 11560/11560 [00:22<00:00, 525.05frame/s, rate=0]
[FACEFUSION.CORE] Extracting frames with a resolution of 1920x1080 and 30.0 frames per second
[FACEFUSION.PROCESSORS.FRAME.MODULES.FACE_SWAPPER] Processing
**Processing: 100%|=| 11560/11560 [21:53<00:00,  8.80frame/s, execution_providers=['coreml', 'cpu'], execution**
[FACEFUSION.PROCESSORS.FRAME.MODULES.FACE_ENHANCER] Processing
**Processing:  64%| | 7348/11560 [2:28:43<1:11:13,  1.01s/frame, execution_providers=['coreml', 'cpu'], execut**

“FACE_SWAPPER is significantly faster than FACE_ENHANCER. I believe FACE_ENHANCER doesn’t use the CoreML engine.”

**Comment by henryruhs** [comment]
Please join [Discord](https://join.facefusion.io) for help.
