### ISSUE TITLE
Read Chinese character path image correctly

### ISSUE THREAD

**Issue by lyraestar** [facefusion/facefusion#658]
The problem is dealing with Chinese character path, tested on Windows. "sanitize_path_for_windows(image_path)" does not do the job correctly.

I managed to modify the following windows image reading logic. In my test on Windows 10, "cv2.imdecode(numpy.fromfile(image_path, dtype=numpy.uint8), cv2.IMREAD_COLOR)" works well with non-English path.

In vision.py: 
```python
def read_image(image_path : str) -> Optional[VisionFrame]:
	if is_image(image_path):
#		if is_windows():
#			image_path = sanitize_path_for_windows(image_path)
#		return cv2.imread(image_path)
		return cv2.imdecode(numpy.fromfile(image_path, dtype=numpy.uint8), cv2.IMREAD_COLOR)
	return None
``` `

**Comment by henryruhs** [comment]
This is not a solution, the whole cv2 library is broken when it comes to unicode filename handling. Not just reading images.

If you like to contribute, then fix our method and don't work around it. Some users indeed reported that it does not work for them, but I assume this is platform related.
