### ISSUE TITLE
Can't use gifs as target

### ISSUE THREAD

**Issue by vkleinmp** [facefusion/facefusion#66]
mp4 and some other video formats work but not GIFs.

**Comment by henryruhs** [comment]
It's not supported.

**Comment by Sky-Bridge** [comment]
You can use ffmpeg change
gif to mp4：ffmpeg -f gif -i test.gif test.mp4
mp4 to gif：ffmpeg -i test.mp4 test.gif

**Comment by henryruhs** [comment]
I wonder why nobody is sending a pull request?

**Comment by henryruhs** [comment]
### UI

To ensure that the preview is working, we need to encode the `target.gif` file into a `preview-temp.mp4` file.
There needs to be **path-translator**, forwarding either to the `target.mp4` or `preview-temp.mp4`. Overriding the `target_path` with `preview-temp.mp4` would make everything worse in my opinion.

### CLI

Again, the `target.gif` needs to be encoded but this time to `process-temp.mp4`. Now we can perform the frame extraction. Finally we use a custom method to create the animated gif from the frames.

**Comment by henryruhs** [comment]
> I do not plan to implement this feature from my side - the community is ask to contribute

**Comment by henryruhs** [comment]
I apologize, but I have decided not to pursue that task as it does not align with my personal usage. I wrote down a potential solution just in case a community member is willing to implement it.
