### ISSUE TITLE
Inquiry about the Uniface Model

### ISSUE THREAD

**Issue by 1vanFan** [facefusion/facefusion#661]
I would like to extend my sincere gratitude for sharing the FaceFusion project with the community. This project is truly impressive.

As I was exploring the project, I came across the `uniface` model. I am particularly interested in understanding the origins and any relevant papers or publications associated with it. Could you please share some information about the `uniface` model?

**Comment by henryruhs** [comment]
I think it's that one

https://github.com/xc-csc101/UniFace
