### ISSUE TITLE
How to use AMD 7900XT graphics card ?

### ISSUE THREAD

**Issue by Focagem** [facefusion/facefusion#663]
How to use AMD 7900XT graphics card ?

I'm using 5800x3d Processor, and getting a weird results. Can I use my AMD card, if yes, how?
![image](https://github.com/user-attachments/assets/01f1454f-e9f9-4494-a372-13cab19b2e06)

**Comment by henryruhs** [comment]
# @
Please join [Discord](https://join.facefusion.io) for help.
