### ISSUE TITLE
Slow processing

### ISSUE THREAD

**Issue by Munee-sharaldai** [facefusion/facefusion#665]
![image](https://github.com/user-attachments/assets/c70f56f9-02a3-45a0-9082-0e9c26e1f491)
![image](https://github.com/user-attachments/assets/6aa3e4e5-8e74-447b-ac6d-8a1fc6b8d039)

The speed is so slow that it writes s/frame instead of frame/s
GPU works only on 10-30%, while cpu is on 80%. My Gpu is Rtx 4060 and im using facefusion through pinokio

**Comment by henryruhs** [comment]
Please join [Discord](https://join.facefusion.io) for help.
