### ISSUE TITLE
Conda is not Activated Error

### ISSUE THREAD

**Issue by drdancm** [facefusion/facefusion#675]
Conda is not Activated:

Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Version: v1.10.0
Commit hash: c19d04436496ab29ddca4758a792831ae41b31de
*** Error running install.py for extension D:\STABLEDIFF\Data\Packages\Stable Diffusion WebUI\extensions\facefusion.
*** Command: "D:\STABLEDIFF\Data\Packages\Stable Diffusion WebUI\venv\Scripts\python.exe" "D:\STABLEDIFF\Data\Packages\Stable Diffusion WebUI\extensions\facefusion\install.py"
*** Error code: 1
*** stdout: Conda is not activated
*** 
I'm running Facefusion in Stable Diffusion WEbUI v1.10.0 which runs under Stability Matrix, but I don't know if that should make a difference.

Since I have no idea how to install Conda, would you please have Facefusion install Conda ?
Many updates of Stable Diffusion ago, I ran Facefusion successfully, but at this point it installs but and the preview seems to work, but 

Thanks!

**Comment by henryruhs** [comment]
Hey, did you read the installation guide? It's all written in our docs.

Buy the installer otherwise, terminal is not for everyone...
