### ISSUE TITLE
No camera in --ui-layouts webcam

### ISSUE THREAD

**Issue by grizzzlyzzzombie** [facefusion/facefusion#683]
Greetings!
Thank you for such wonderful tool!

Would u kindly to help me with running this marvelous tool for live webcam?
I see only 
![image](https://github.com/user-attachments/assets/b0a00dcb-a856-4301-9f6a-ac8140e1c7d2)
Indicator on webcam is not active
All access given to camera and http://127.0.0.1:7860/

Would u kindly to help to resolve this issue? ^_^

**Comment by henryruhs** [comment]
Please join [Discord](https://join.facefusion.io) for help.
