### ISSUE TITLE
Abrupt processing speed drop after a certain progress

### ISSUE THREAD

**Issue by PrismSync** [facefusion/facefusion#686]
I think this is likely my settings' issue, but I couldn't find a helpful troubleshooting guide elsewhere. I'm really grateful if anyone can kindly help me out.

My setup: RTX 3080 10GB, 13600K, 48GB system memory
Goal: face swap a 2min long, 1920x1080, 50fps video
Symptom: the processing FPS starts off at around 20FPS, until about 60% done, then it drops to merely <2FPS.

I thought that since the video is being processed as frame sequence, only the batch size would affect processing speed but not the overall duration of the video, hence FPS would be stable through the process.

I tried to reduce the thread count from 64 to 32 to 16, but doesn't seem to alleviate the issue and only decreased the FPS initially. And VRAM usage has stayed around 9.5GB/10GB regardless of thread count setting. The system memory stayed at about 24GB/48GB overall.

I've attached a screenshot of other parameters (is there a way to find the runtime parameters in some file and copy&paste?). my apologies for the inconvenience.

Apart from the parameters, I noticed that when I preview some of the frames in the later (slow-processing) portions of the video, some frames would return "error". The server terminal returns the following:
`  File "C:\Experimental\Pinokio\api\facefusion-pinokio.git\facefusion\facefusion\vision.py", line 180, in resize_frame_resolution
    height, width = vision_frame.shape[:2]
AttributeError: 'NoneType' object has no attribute 'shape'`
This seems to mean no face is detected in that frame, is this correct? If this is the cause slowing down the face swap processing, is there a way to just skip the frames with no face detected?

![image](https://github.com/user-attachments/assets/79d9eb48-f2e2-4ad5-be4a-07a1719281b4)

**Comment by henryruhs** [comment]
# @
Please join [Discord](https://join.facefusion.io) for help.

**Comment by eiernacken5** [comment]
Is there a solution for this?
