### ISSUE TITLE
 merging video failed

### ISSUE THREAD

**Issue by MtYCNN** [facefusion/facefusion#688]
The message 'merging video failed' keeps appearing, but ffmpeg is installed and the output path is also the root directory. May I ask how to solve this problem?

**Comment by henryruhs** [comment]
Please join [Discord](https://join.facefusion.io) for help.

**Comment by MtYCNN** [comment]
> Please join [Discord](https://join.facefusion.io) for help.

I am unable to join your Discord here. Could you please not close this question and let someone else answer it

**Comment by henryruhs** [comment]
Nope, this is a software tracker - not a support forum.
