### ISSUE TITLE
GFPGAN onnxruntime?

### ISSUE THREAD

**Issue by hashnag** [facefusion/facefusion#70]
[https://github.com/xuanandsix/GFPGAN-onnxruntime-demo/tree/main](https://github.com/xuanandsix/GFPGAN-onnxruntime-demo/tree/main)

Just curious if this might be useful?

According to [RichardErkhov](https://github.com/RichardErkhov/Richard-roop) it may provide 2.5x speedup.

**Comment by henryruhs** [comment]
We have it as developer preview in our Discord.
