### ISSUE TITLE
png artifacts

### ISSUE THREAD

**Issue by Spirt51** [facefusion/facefusion#703]
png is essentially saved as jpg because a black fill appears in place of the transparent background, mostly with color artifacts.
![pngegg](https://github.com/user-attachments/assets/eb07ea76-2c9e-430b-a3c0-dbbc75f40ad9)
![pngegg-4884047f](https://github.com/user-attachments/assets/c7bc11a9-dc95-4b9a-8316-78fc9027a6bc)

**Comment by henryruhs** [comment]
Does not work with transparency.
