### ISSUE TITLE
When running in silent mode, and using --frame-processors face_enhancer, the -s option is required even though it doesn't do anything

### ISSUE THREAD

**Issue by Tam66662** [facefusion/facefusion#71]
I like to run facefusion in silent mode on the command line to do my swaps. But when I enhance the frames using "--frame-processors face_enhancer", I find that if I leave out the -s option, it opens facefusion in interactive UI mode. But if I specify a dummy parameter, say "-s dummy", it remains in silent mode and works as expected. 

I guess I can always use the workaround and specify "-s dummy", but it would be nice if the -s option was not required for face enhancements.

**Comment by henryruhs** [comment]
It is not called silent but headless mode. Already landed in develop branch and will be released this week.
