### ISSUE TITLE
Select model inswapper_128_fp16 error, [FACEFUSION.PROCESSORS.FRAME.MODULES.FACE_SWAPPER] Download of the model is not done!but not others

### ISSUE THREAD

**Issue by hybIsVeryCool** [facefusion/facefusion#713]
I have downloaded the model to the specified folder, but when I select model inswapper_128_fp16, an error occurs and the console outputs [FACEFUSION.PROCESSORS.FRAME.MODULES.FACE_SWAPPER] Download of the model is not done! I can generate other models normally
   I checked my model folder and found inswapper_128_fp16.onnx.Why？

**Comment by hybIsVeryCool** [comment]
![image](https://github.com/user-attachments/assets/e70385b2-249d-4d55-970f-dc63fded42b2)
![image](https://github.com/user-attachments/assets/ea485a67-5bc4-4903-8161-278f5aa17456)

**Comment by henryruhs** [comment]
Please join [Discord](https://join.facefusion.io) for help.
