### ISSUE TITLE
How to Uninstall entirely?

### ISSUE THREAD

**Issue by simplyexperimental** [facefusion/facefusion#718]
How to uninstall this?

Tried to install this and got a facefusion module not found error which FAQ says means something wasn't installed properly.
Saw after I put this line I lost 7GB and there is no trace of what it installed and where.
You don't have an un-installation guide on this and it's components.

The environment list for facefusion is only 140mb. I swear I already had cuda installed so it's likely this tool installed another in the wrong location:
The nvcc --version is not recognized so something definitely went wrong here and it's where the file size got increased by 7GB.
conda install conda-forge::cuda-runtime=12.4.1 conda-forge::cudnn=9.2.1.18 conda-forge::gputil=1.4.0

How can I reverse that and also remove whatever was installed?

I've already tried
conda env list
conda deactivate
conda remove --name facefusiom --all

and still missing 7GB

**Comment by henryruhs** [comment]
remove the facefusion directory? it contains a hidden .assets directory that contains the models which take a good amount of space.

hope that helped.

**Comment by simplyexperimental** [comment]
> remove the facefusion directory? it contains a hidden .assets directory that contains the models which take a good amount of space.
> 
> hope that helped.

Where is the face fusion directory?

I installed it via the command line and it never even ran the install.py line because that's what gave the error.
So far I've gained most of the GB back by running python cleaning commands but I think there's still some left.
conda clean --all

**Comment by henryruhs** [comment]
directory you are currently browsing... which contains the install.py and run.py

this is not a support forum but a software tracker for issues!
