### ISSUE TITLE
why only few videos are going into processing mode..

### ISSUE THREAD

**Issue by daarkwulf** [facefusion/facefusion#72]
hey.
i have multiple target videos dont know why only few of them are running to processing mode which is second step after calculating frames,,, also m not able to find the logic whether the size of video,frames, height ratio, or less frame,, or what.. sometimes its working and mostly note.. 
i have 20gb ram so its not system issue.. plus already ran roop that time also same thing happened..
and 1 in 4 times previews works otherwise keep sliding preview bar to have preview.. 

can u tell me. 
??

**Comment by henryruhs** [comment]
Nope, I cannot tell you.
