### ISSUE TITLE
[E:onnxruntime:Default, provider_bridge_ort.cc:1548 onnxruntime::TryGetProviderInfo_CUDA] D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1209 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "C:\Users\PC\miniconda3\envs\facefusion\lib\site-packages\onnxruntime\capi\onnxruntime_providers_cuda.dll"

### ISSUE THREAD

**Issue by codeolder** [facefusion/facefusion#730]
<img width="867" alt="image" src="https://github.com/user-attachments/assets/ebee37e3-3fb3-4944-93b5-2250b58042c7">

**I have successfully started the FaceFusion interface, but after uploading the source and target images, the command window prompts the error as shown in the attachment. Please help me find out how to solve this issues completely.**

**Comment by henryruhs** [comment]
Please join [Discord](https://join.facefusion.io) for help.

**Comment by StanislawKarnacky** [comment]
I am the second guy with the same error.
Windows 10 x64
GTX 1060 6Gb
