### ISSUE TITLE
ubuntu 22.04   install bug  numpy  dependency conflicts 

### ISSUE THREAD

**Issue by hsdfeng** [facefusion/facefusion#732]
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
gradio 3.50.2 requires numpy~=1.0, but you have numpy 2.1.1 which is incompatible.
openvino 2024.2.0 requires numpy<2.0.0,>=1.16.6, but you have numpy 2.1.1 which is incompatible.

**Comment by henryruhs** [comment]
Use `install.py`
