### ISSUE TITLE
Multiprocessing Implementation

### ISSUE THREAD

**Issue by smartechru** [facefusion/facefusion#736]
Thanks for the great repository.
I'd like to know if there is a way to feed multiple images as input.

**Comment by henryruhs** [comment]
simply drag and drop multiple images to the source area.

**Comment by smartechru** [comment]
Thanks for the quick reply.
Let's say I need to generate 20-30 images at once. In this case, I'd like to know if the engine processes the input images simultaneously or one-by-one.

**Comment by henryruhs** [comment]
No, batching is not supported.
