### ISSUE TITLE
Can't we use more ram in this progy

### ISSUE THREAD

**Issue by daarkwulf** [facefusion/facefusion#74]
Hii
I m using facefussion 
And it's only using 3gb ram .. despite having I have 20gb ram

Can u tell how can we increase python using more ram.. any idea or tweak ?

Thanx

**Comment by vizsumit** [comment]
You might be using running on CPU. Faces are processed sequentially which depends more on cores than ram, in CPU mode it will make smaller size batches to process.

**Comment by henryruhs** [comment]
Sorry, but I cannot think of an action item on my side. There is nothing you can actual tweak.
