### ISSUE TITLE
Analyzing 100%, but no results generated.

### ISSUE THREAD

**Issue by Ninjagg** [facefusion/facefusion#742]
I'm a fresh in using facefusion. I pulled the docker (version: 2.6.1) and run successfully. When I try to replace a face in a video, it says the analyzing 100%, but no result file is generated. Then, I did this task in console, but it still did NOT work. 
Code is:
```
python run.py -s /facefusion/output/example.png -t /facefusion/output/example.mp4 -o /facefusion/output/ --execution-providers cuda --execution-thread-count 6 --headless --ski
p-download --execution-queue-count 2 --log-level debug 2>&1
```

Result is:
![1](https://github.com/user-attachments/assets/800205aa-8afc-4450-849a-58e6d6762a34)

Thanks for your time.

**Comment by henryruhs** [comment]
Does not work with NSFW content.
