### ISSUE TITLE
Unable to run python install.py - error: the following arguments are required: --onnxruntime

### ISSUE THREAD

**Issue by chefjpg** [facefusion/facefusion#744]
This is not the first time I have had FaceFusion up and running, however I have upgraded to windows 11 and wanted a fresh install. I have followed all of the steps listed in the tutorial, however when running python install,py I am met with this error:

```
usage: install.py [-h] --onnxruntime {default,cuda,openvino,directml} [--skip-conda] [-v]
install.py: error: the following arguments are required: --onnxruntime
```

I have uninstalled and reinstalled everything from the tutorial as well as uninstalling onnxruntime and reinstalling my CUDA and cuDNN and have met the same result each time. Any ideas?

**Comment by henryruhs** [comment]
The documentation is currently on the transition to 3.0.0 - make sure you have checked out the next branch.

Please join [Discord](https://join.facefusion.io) for help.
