### ISSUE TITLE
Deleting corrupt source for open_nsfw

### ISSUE THREAD

**Issue by Koaxz** [facefusion/facefusion#749]
python run.py run
Downloading: 100%|==============================================| 8.00/8.00 [00:00<00:00, 8.86B/s, file=open_nsfw.hash]
Downloading: 100%|===========================================| 22.5M/22.5M [00:00<00:00, 8.66kB/s, file=open_nsfw.onnx]
[FACEFUSION.DOWNLOAD] Validating source for open_nsfw failed
[FACEFUSION.DOWNLOAD] Deleting corrupt source for open_nsfw

**Comment by henryruhs** [comment]
That is the expected behavior... FF 3.0.0 validates the models according to hashes. As you have the FF 2.x.x models it marks them as corrupt.

Delete your .assets/modules directory. Have fun with the new release.

**Comment by YZX-codesky** [comment]
> That is the expected behavior... FF 3.0.0 validates the models according to hashes. As you still have the FF 2.x.x models, it marks them as corrupt.
> 
> Delete your .assets/modules directory. Have fun with the new release.
Hello, I would like to ask where this folder is. I couldn't find it and running Python facefusion.py run still yields an error: [FACEFUSION. OWNLOAD] Validating source for open_nsfw failed

**Comment by henryruhs** [comment]
That directory is hidden under windows, that is the nature of files and directories with a leading point.

Anyways, you can just restart FF 3 multiple times until it removed and redownload every model.
