### ISSUE TITLE
Error reported after update

### ISSUE THREAD

**Issue by nullaix** [facefusion/facefusion#75]
i need help
hello
after update today
when i use:python run.py --execution_provider cuda
The following error occurred:run.py: error: unrecognized arguments: --execution_provider gpu
now
can only run：python run.py --execution_provider cpu

**Comment by henryruhs** [comment]
This CLI arguments are just wrong, as the error messages stated.

See: https://docs.facefusion.io/#usage

**Comment by nullaix** [comment]
i use 
python run.py --execution-providers cuda
the same result...

**Comment by henryruhs** [comment]
well, cuda is not installed then - follow the latest installation guide
