### ISSUE TITLE
error when trying to run "python install.py"

### ISSUE THREAD

**Issue by sdproweb** [facefusion/facefusion#755]
(facefusion) C:\Users\Goose\facefusion>python install.py
usage: install.py [-h] --onnxruntime {default,cuda,openvino,directml} [--skip-conda] [-v]
install.py: error: the following arguments are required: --onnxruntime

can you help please? thx

**Comment by henryruhs** [comment]
Did you read the message? :)

```
usage: install.py [-h] --onnxruntime {default,cuda,openvino,directml} [--skip-conda] [-v]
```

**Comment by sdproweb** [comment]
bless you
