### ISSUE TITLE
How do I create a bat file to run a neural network?

### ISSUE THREAD

**Issue by Kicher2006** [facefusion/facefusion#758]
I'm not a programmer, so I'm wondering how to speed up the startup of a neural network. Now I use this algorithm to launch a neural network, but it is long. 
Step 1. Go to the Conda command line in search. (Anaconda Prompt).
Step 2. Execute the command: conda activate facefusion.
3 step. Execute the command: cd facefusion (go to the desired folder).
4 step. Execute the command: python facefusion.py run (run)

**Comment by henryruhs** [comment]
Our windows installer does that.
