### ISSUE TITLE
Hash file missing for gfpgan_1.4 and wav2lip

### ISSUE THREAD

**Issue by DelaLlata** [facefusion/facefusion#760]
Hi, it seams that the hash files for the gfpgan_1.4 and wav2lip models are missing or not installed. In consequence can't download this models (Validating hash for xxxxx failed). Any idea how to have this files?

Grate work in this new version!!!!

Thank You

**Comment by henryruhs** [comment]
It will delete corrupted files and on next start try to load them. I recommend not to update from 2.6.1 or at least delete .assets/models after doing so.
