### ISSUE TITLE
Only CPU shows as execution provider for 3.0.0

### ISSUE THREAD

**Issue by SirHotcake** [facefusion/facefusion#771]
when installing version 3.0.0 only CPU shows for execution provider, when trying to validate with conda list cudatoolkit command it doesnt show anything. i already installed cuda 12.4.1, made sure of the variables reinstalled all of it again and still doesnt show cuda and tensort as options.

**Comment by henryruhs** [comment]
I think you did not run the `install.py` using `--onnxruntime cuda`.

If the issues remains, please join [Discord](https://join.facefusion.io) for help.
