### ISSUE TITLE
Conda CUDA packages not found

### ISSUE THREAD

**Issue by LoopControl** [facefusion/facefusion#772]
Based on the [Linux docs for installing the CUDA Accelerator](https://docs.facefusion.io/installation/accelerator/linux), I get this error about the Conda packages not being found:

```
> conda install conda-forge::cuda-runtime=12.4.1 conda-forge::cudnn=9.2.1.18

Channels:
 - pytorch
 - defaults
 - conda-forge
Platform: linux-64
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - conda-forge::cuda-runtime==12.4.1
  - conda-forge::cudnn==9.2.1.18

Current channels:

  - https://conda.anaconda.org/pytorch
  - defaults
  - https://conda.anaconda.org/conda-forge

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```

**Comment by henryruhs** [comment]
What Distro are you running?

**Comment by LoopControl** [comment]
Ubuntu 22

**Comment by henryruhs** [comment]
It cannot resolve your operating system, not sure how to solve it. Please join [Discord](https://join.facefusion.io) for help.

**Comment by archie-bal** [comment]
@LoopControl please check, if you have anaconda and miniconda installed at the same time. It seems like it, because of the listed channels.
Then, try to use miniconda only. At least, this worked for me.
