### ISSUE TITLE
Error when loading new model

### ISSUE THREAD

**Issue by asali9643** [facefusion/facefusion#773]
An error occurs when loading the model added in this update.
There was no model file in the folder, so I downloaded it manually, but it says that the hash file was not found and detection failed.
I copied and pasted the hash value listed on the hugging face and saved it with a hash extension, but it didn't work.

**Comment by henryruhs** [comment]
Disable VPN or local firewall to get the automated downloads running.

Please join Discord for help, this is not a support forum.
