### ISSUE TITLE
GPU graphics card

### ISSUE THREAD

**Issue by zhangxiaokang** [facefusion/facefusion#774]
How to specify which GPU graphics card to use

**Comment by henryruhs** [comment]
There is the concept of execution providers in the onnxruntime.

- DirectML (AMD, NVIDIA, Intel)
- ROCm (AMD under Linux)
- CoreML (Apple)
- OpenVINO (Intel)
- CUDA (NVIDIA)
- TensorRT (NVIDIA)

**Comment by zhangxiaokang** [comment]
What I mean is, if a server has 8 GPUs, is there a parameter to specify the use of GPU 1 or GPU 2

**Comment by henryruhs** [comment]
Via the device id: https://docs.facefusion.io/usage/cli-arguments/execution

**Comment by zhangxiaokang** [comment]
okay, thank you
