### ISSUE TITLE
An error occurred when uploading pictures.

### ISSUE THREAD

**Issue by goldx3** [facefusion/facefusion#777]
![Snipaste_2024-09-29_19-09-05](https://github.com/user-attachments/assets/d65f05ef-3998-4f0c-a1b6-44876de38c1f)
![Snipaste_2024-09-29_19-08-57](https://github.com/user-attachments/assets/01008a37-b559-4ce2-b400-a210fdf065d2)

**Comment by henryruhs** [comment]
Does not work with such chinese characters in filenames and paths. Known issue in cv2 since a decade.
