### ISSUE TITLE
Handle case when an extension is not supported by OpenCV

### ISSUE THREAD

**Issue by redrum-llik** [facefusion/facefusion#778]
OpenCV does not support certain extensions like .webp; on an attempt to write an image it will throw an exception:

```
  File "C:\FaceFusion\facefusion\facefusion\vision.py", line 41, in write_image
    return cv2.imwrite(image_path, vision_frame)
cv2.error: OpenCV(4.10.0) D:\a\opencv-python\opencv-python\opencv\modules\imgcodecs\src\loadsave.cpp:708: error: (-2:Unspecified error) could not find a writer for the specified extension in function 'cv::imwrite_'
```

To reproduce, use any .webp target image (in my case, the output path was `C:\Users\Rumi\AppData\Local\Temp\facefusion\1-shutterstock_588634790-825x465\temp.webp`). I suppose selecting output image format would be the best solution, but even catching the error and showing a user-friendly warning about the specific extension being unsupported would be rather useful.

**Comment by henryruhs** [comment]
Sorry but cv2 supports webp for sure.

Potential issues on your side.

1. missing file extension
2. cv2 compiled without webp support
