### ISSUE TITLE
something wrong when i install the facefusion?

### ISSUE THREAD

**Issue by MssaLL** [facefusion/facefusion#780]
The first time I installed facefusion3.0, I didn't know much about the code, I did it through a tutorial, but something happened. After I typed in:
 ** python install.py**
he told me there was an error: 
_usage: install.py [-h] --onnxruntime {default,cuda,openvino,directml}
[--skip-conda] [-v]
install.py: error: the following arguments are required: --onnxruntime_
I looked at the tutorial and said to use:
**python install.py --skip-conda**
when something else happens. But still no, the above error code will appear. So what shoud i do.   qwq

**Comment by henryruhs** [comment]
```usage: install.py [-h] --onnxruntime {default,cuda,openvino,directml}```

That means `--onnxruntime cuda` for example when owning a NVIDIA card.
