### ISSUE TITLE
How can I adjust the size of the preview area? In the new version, the preview area is too large, making it inconvenient to view the face-swapping effect in real time

### ISSUE THREAD

**Issue by yangying1205** [facefusion/facefusion#781]
![屏幕截图 2024-09-30 153721](https://github.com/user-attachments/assets/9a8686a1-8647-4de4-b598-af17ff31a5c9)
![屏幕截图 2024-09-30 153738](https://github.com/user-attachments/assets/3aaf8c89-31f3-4602-970b-bd7c811dacd7)

**Comment by henryruhs** [comment]
It should only be sticky on landscape images - check the metadata of this image, does not look correct.

**Comment by yangying1205** [comment]
When adjusting the parameters, I can't see the face swap effect in real-time. I have to scroll up to view it, which lowers the efficiency. Could the preview area be made smaller or possibly float separately at the top?

**Comment by henryruhs** [comment]
You are not responding to my question. Closing the issue.
