### ISSUE TITLE
FaceFusion 3.0 on MacOS m2 - OpenCV error !ssize.empty() in function 'resize'

### ISSUE THREAD

**Issue by Martin077** [facefusion/facefusion#783]
pinokio/api/facefusion-pinokio.git/facefusion/facefusion/content_analyser.py", line 99, in prepare_frame
    vision_frame = cv2.resize(vision_frame, model_size).astype(numpy.float32)
cv2.error: OpenCV(4.10.0) /Users/xperience/GHA-Actions-OpenCV/_work/opencv-python/opencv-python/opencv/modules/imgproc/src/resize.cpp:4152: error: (-215:Assertion failed) !ssize.empty() in function 'resize'

**Comment by Martin077** [comment]
I see in a closed issue that maybe the problem is a corrupt frame or frames in the target video?

**Comment by henryruhs** [comment]
Please join [Discord](https://join.facefusion.io) for help.
