### ISSUE TITLE
Unable to use cuda: LoadLibrary failed with error 126 "" when trying to load onnxruntime_providers_cuda.dll

### ISSUE THREAD

**Issue by timforsync** [facefusion/facefusion#784]
I was following installation guide here: https://docs.facefusion.io/installation

But after installation, I got following error

```
[E:onnxruntime:Default, provider_bridge_ort.cc:1548 onnxruntime::TryGetProviderInfo_CUDA] D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1209 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "C:\Users\xxx\miniconda3\envs\facefusion\lib\site-packages\onnxruntime\capi\onnxruntime_providers_cuda.dll"
```

Didn't have this problem before, just recently, when I reinstalled my win11 os, and tried to reinstall facefusion.

Can someone provide a solution? Thanks

**Comment by henryruhs** [comment]
GitHub is not a support forum. Please join Discord for help.
