### ISSUE TITLE
--skip-download seems not working with headless-run

### ISSUE THREAD

**Issue by mfrank0711** [facefusion/facefusion#786]
Hi, when i execute something like
`python facefusion.py headless-run -s "" -t "" -o "" --skip-download --log-level debug` the outcome is:

[FACEFUSION.CORE] Processing step 1 of 1
[FACEFUSION.DOWNLOAD] Validating hash for open_nsfw succeed
[FACEFUSION.DOWNLOAD] Validating source for open_nsfw succeed
[FACEFUSION.DOWNLOAD] Validating hash for fairface succeed
[FACEFUSION.DOWNLOAD] Validating source for fairface succeed
[FACEFUSION.DOWNLOAD] Validating hash for yoloface_8n succeed
[FACEFUSION.DOWNLOAD] Validating source for yoloface_8n succeed
[FACEFUSION.DOWNLOAD] Validating hash for fan_68_5 succeed
[FACEFUSION.DOWNLOAD] Validating hash for 2dfan4 succeed
[FACEFUSION.DOWNLOAD] Validating source for fan_68_5 succeed
[FACEFUSION.DOWNLOAD] Validating source for 2dfan4 succeed
[FACEFUSION.DOWNLOAD] Validating hash for dfl_xseg succeed
[FACEFUSION.DOWNLOAD] Validating hash for resnet_34 succeed
[FACEFUSION.DOWNLOAD] Validating source for dfl_xseg succeed
[FACEFUSION.DOWNLOAD] Validating source for resnet_34 succeed
[FACEFUSION.DOWNLOAD] Validating hash for arcface_w600k_r50 succeed
[FACEFUSION.DOWNLOAD] Validating source for arcface_w600k_r50 succeed
[FACEFUSION.DOWNLOAD] Validating hash for kim_vocal_2 succeed
[FACEFUSION.DOWNLOAD] Validating source for kim_vocal_2 succeed
[FACEFUSION.DOWNLOAD] Validating hash for inswapper_128_fp16 succeed
[FACEFUSION.DOWNLOAD] Validating source for inswapper_128_fp16 succeed
[FACEFUSION.DOWNLOAD] Validating hash for gfpgan_1.4 succeed
[FACEFUSION.DOWNLOAD] Validating source for gfpgan_1.4 succeed
[FACEFUSION.CORE] Clearing temporary resources
[FACEFUSION.CORE] Creating temporary resources
[FACEFUSION.CORE] Copying image with a resolution of 768x1364
[FACEFUSION.CORE] Copying image succeed
......

It seems, that `--skip-download` is only working for jobs? https://github.com/facefusion/facefusion/blob/0f4b3866054f6467f174d2fa6e773a65b5fed795/facefusion/download.py#L61

**Comment by henryruhs** [comment]
I don't see a download but hash validation there... can you delete a model and try again?

**Comment by mfrank0711** [comment]
Ah, sorry my bad. Thats only valid for the download, not the hashes.

I am currently checking how to speed up the process and checking the hashes is eating seconds in every execution. I might just add `if not state_manager.get_item('skip_download'): ` before the hash check as well. That should solve my problem with the speed

**Comment by henryruhs** [comment]
That breaks jobs as you might use a model in step 2 that you did not validate on step 1.

Everything is there for a reason.
