### ISSUE TITLE
Split 3.0.0 ChangeLog

### ISSUE THREAD

**Issue by blubbsy** [facefusion/facefusion#789]
Hi,

it would be much easier to keep track of the bugfixes and changes you did if you would could split up up the changelog of the 3.0.0 release with minor releases instead of releasing everything as 3.0.0 and to had to read the commits to see what happend. Of course this would mean that we had now FaceFusion 3.0.7 (or whatever convention you choose), but as you add minor and mayor improvements i think this is okay. 

BR

**Comment by henryruhs** [comment]
I'm aware of semantic versioning, just too busy to make official releases that trigger a chain of tasks.
