### ISSUE TITLE
lip sync audio upload window missing in gui

### ISSUE THREAD

**Issue by soans1994** [facefusion/facefusion#790]
hello devs,

in the browser gui, there is no option of uploading lip sync audio
it says,
[FACEFUSION.LIP_SYNCER] Choose a audio for the source!
please fix this,

thank you

**Comment by henryruhs** [comment]
Just drag and drop it to the source area... it's not the best UX to be honest.

**Comment by soans1994** [comment]
@henryruhs thank you

**Comment by Barnacules** [comment]
You have to do a lip sync and face swap on two separate passes since they share the source box right? This is where the jobs queue feature seems to come in handy! 👍

**Comment by henryruhs** [comment]
@Barnacules Nope, you can actual drag and drop multiple files (image and audio) at the same time to the source area.
