### ISSUE TITLE
How can I retain the glasses information from the source image?

### ISSUE THREAD

**Issue by aga2k1981** [facefusion/facefusion#792]
我是facefuison3.0的用户，在换脸视屏过程中，soruce图片带有眼镜信息，我想把他留下这样更换的视屏会更像目标人物，而输出结果往往会把soruce图片的眼镜信息抹去，请问是我设置问题还是需要什么条件？

"I am a FaceFusion 3.0 user, and when swapping faces in videos, the source image contains glasses information that I would like to keep so that the swapped video looks more like the target person. However, the output often removes the glasses information from the source image. Is this an issue with my settings, or are there specific conditions required?

**Comment by henryruhs** [comment]
Try the region mask and disabled glasses.

**Comment by aga2k1981** [comment]
I just tried unchecking the 'glasses' option under the 'region' settings, but the glasses still don't appear in the final result. I'm not sure how to use the 'occlusion' option. Could it be that there’s an issue with the glasses in my image, which makes them unrecognizable? Could you provide me with a template of an image with glasses that can be used normally for me to try?

**Comment by henryruhs** [comment]
GitHub is not a support forum. Join Discord to have a chat.
