### ISSUE TITLE
Repository not found 

### ISSUE THREAD

**Issue by Clicli99** [facefusion/facefusion#8]
Hello, I’ve been using Roop for a while with Google colab, unfortunately it stopped working because https://huggingface.co/henryruhs/roop/resolve/main/inswapper_128.onnx doesn’t exist anymore. Does FaceFusion have any type of colab ? Thanks

**Comment by henryruhs** [comment]
FaceFusion does indeed have a Colab... https://docs.facefusion.io/workshop/run-via-colab
