### ISSUE TITLE
False color normalization on webcam

### ISSUE THREAD

**Issue by catid** [facefusion/facefusion#84]
Running on Ubuntu Linux with a 4090 with an attached Opal C1 webcam. Colors look wrong, so seems to be a bug somewhere.

![img_0347_720](https://github.com/facefusion/facefusion/assets/252193/03c6a603-2a81-4b6c-a963-6895fe12c962)

**Comment by catid** [comment]
Making this edit in vision.py fixed the colors for me:

def normalize_frame_color(frame : Frame) -> Frame:
	return frame
	#return cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)

**Comment by zachysaur** [comment]
how do you use webcam on it?

**Comment by henryruhs** [comment]
@catid Sorry to say, but I cannot fix this.

1. `capture = cv2.VideoCapture(0)` should always return BGR
1. convert rgb flag had no effect on my webcam but probably on yours: `capture.set(cv2.CAP_PROP_CONVERT_RGB, 1)`
1. prop mode flag is missing the backend and failed: `capture.set(cv2.CAP_PROP_MODE, cv2.CAP_MODE_RGB)`
1. there is no chance to determine the color space via CV2 and conditional skip color nomalization


I spend a couple of hours on that and consider this a WONTFIX. If someone has a solution, I'm willing to accept a pull request.
