### ISSUE TITLE
Keep getting Errors in nvidia's cuda container

### ISSUE THREAD

**Issue by EricLeeaaaaa** [facefusion/facefusion#90]
Docker version 24.0.5
Container name `nvcr.io/nvidia/cuda:11.8.0-cudnn8-runtime-ubuntu22.04`
Executed commands:

1. `apt update`
2. `apt install python3-pip vim git ffmpeg`
3. `git clone https://github.com/facefusion/facefusion && cd facefusion`
4. `pip install pip -U`
5. `pip install -r requirements.txt --extra-index-url https://download.pytorch.org/whl/cu118`
6. `export GRADIO_SERVER_NAME=0.0.0.0`
7. `python3 run.py --execution-providers cpu cuda tensorrt`

_**Able to start webui but unable to process video**_
**Traceback** `cv2.error: OpenCV(4.8.0) /io/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'`

### Crash screenshot
![image](https://github.com/facefusion/facefusion/assets/98399372/87d28035-c739-4289-8095-19dc8bdd2f5d)

**Comment by henryruhs** [comment]
Please use the official dockerfile. Thanks
