### ISSUE TITLE
if .mov is used as TARGET you get two files in the output folder (.mp4 and .mov)

### ISSUE THREAD

**Issue by sheuronazxe** [facefusion/facefusion#91]
When i drag a Quicktime video (.mov) to TARGET the output folder show 1 video .mp4 and 1 video .mov. Both files are processed.

**Comment by henryruhs** [comment]
That file type is not even supported. I'll take a look into it.

**Comment by henryruhs** [comment]
Gradio is doing that as mov cannot be played within the browser. Nothing I can do about it, just use mp4.
