### ISSUE TITLE
No output

### ISSUE THREAD

**Issue by DrBlou** [facefusion/facefusion#92]
Hello,

First of all, thank you for your work, it looks great. 
However I encounter a problem, I have no video generated in output. 
The whole installation went perfectly, I use a .jpg as input and a .mp4 as target, I choose a destination path for the output, I select Cuda and face swap + face restoration. I can view the preview fine and the swap + enhance looks perfect on all the preview images, but when I click start, it progresses fine in the command prompt, but it stays at 100% and I I don't have any output files (see screenshot below)

![Capture d’écran 2023-09-10 150953](https://github.com/facefusion/facefusion/assets/92190077/a7659edc-5534-40d2-9f08-a1cf976b5876)

If anyone can help me that would be great, thanks in advance

**Comment by Steakache** [comment]
Hi, I have the same problem. how did you resolve it ?

**Comment by henryruhs** [comment]
NSFW filter kicked in
