### ISSUE TITLE
README.md is missing --frame-processors in the list of available parameters for run.py

### ISSUE THREAD

**Issue by TimothyAlexisVass** [facefusion/facefusion#99]
I've added 2 pull requests for this but you keep closing without implementing. 🤣 
```
--frame-processors {face_enhancer, face_swapper, frame_enhancer}                                 choose from the available frame processors
```

**Comment by henryruhs** [comment]
![grafik](https://github.com/facefusion/facefusion/assets/1835397/827f5395-ed50-41cf-b7c0-e19909aa6d3e)

Are you are blind?

**Comment by TimothyAlexisVass** [comment]
Oh, it was at the top and I was expecting it among the other parameters that start with f.
Thank you. 🍡
